const ex = (prompt, steps, answer, interpretation) => ({ prompt, steps, answer, interpretation });
const q = (prompt, answer, solution) => ({ prompt, answer, solution });

export const A0_PROFILES = {
  "A0.1": {
    purpose: "Use signed quantities to describe position and change across zero, then connect subtraction to adding an opposite.",
    prerequisites: [
      "Locate 0, 3, and 6 on a number line and describe which is farther right.",
      "Explain why the distance from 0 to 4 is 4 units.",
      "Evaluate 7 − 3 using a counting-back or missing-addend interpretation.",
    ],
    exposition: [
      "A signed number carries two pieces of information: its distance from zero and its direction from zero. Positive values lie to the right of zero and negative values lie to the left. The sign is not an instruction to subtract; it is part of the number’s name. Thus −5 is a single number five units left of zero.",
      "Order follows position. A number farther right is greater, so −2 > −7 even though 7 has the larger absolute value. Absolute value measures distance from zero and therefore cannot be negative: |−7| = 7. Opposites have equal absolute value and lie on opposite sides of zero.",
      "Subtraction asks for a difference or change. Rewriting a − b as a + (−b) makes the direction explicit and gives one reliable rule for every sign combination. For example, 4 − (−3) = 4 + 3 = 7. Check signed arithmetic by estimating direction and by reversing the operation.",
    ],
    definitions: [
      ["opposites", "Two numbers the same distance from zero on opposite sides, such as −6 and 6.", "Their sum is 0."],
      ["absolute value", "A number’s distance from zero on the number line.", "Distance is nonnegative, so |x| ≥ 0."],
      ["signed change", "A change whose sign records direction: positive for increase and negative for decrease.", "The ending value equals the starting value plus the signed change."],
    ],
    examples: [
      ex("Order −6, 2, −1, and 0 from least to greatest.", ["Place the negatives left of 0 and the positive right of 0.", "Among negative values, −6 lies left of −1.", "Read the points from left to right."], "−6 < −1 < 0 < 2", "Number-line position, not absolute value, determines order."),
      ex("A temperature is 3°C and falls 8°C. Find the new temperature.", ["Represent the fall as the signed change −8.", "Compute 3 + (−8).", "Move 8 units left from 3 on the number line."], "−5°C", "Crossing zero is ordinary signed addition."),
      ex("Explain why 5 − (−4) = 9.", ["Rewrite subtraction as addition of the opposite.", "The opposite of −4 is 4.", "Compute 5 + 4 and verify that 9 − 5 = 4."], "5 − (−4) = 5 + 4 = 9", "Subtracting a negative reverses its direction."),
    ],
    misconception: ["A larger absolute value always means a larger number.", "Absolute value ignores direction; −9 is farther from zero than −2 but is still smaller.", "Compare positions on a number line before comparing distances from zero."],
    questions: [
      q("Plot −4, 0, and 3 on a number line and order them.", "−4 < 0 < 3", "Points farther right are greater, so the order is −4, 0, 3."),
      q("Which is greater: −8 or −3? Explain with position.", "−3", "−3 lies to the right of −8 on a number line."),
      q("Find the opposite and absolute value of −12.", "Opposite 12; absolute value 12", "The opposite is across zero; the distance from zero is 12."),
      q("Evaluate −7 + 10.", "3", "Move 10 units right from −7 to reach 3."),
      q("Evaluate 6 + (−14).", "−8", "A change of −14 moves 14 units left from 6."),
      q("Rewrite 9 − 13 as addition and evaluate.", "9 + (−13) = −4", "Subtracting 13 is adding its opposite, −13."),
      q("Evaluate −5 − 7.", "−12", "Rewrite as −5 + (−7), then combine two leftward changes."),
      q("Evaluate −5 − (−7).", "2", "Rewrite as −5 + 7, then move 7 units right."),
      q("The balance is −$18 and a $25 deposit posts. What is the new balance?", "$7", "Compute −18 + 25 = 7."),
      q("An elevator is at floor 4 and moves down 9 floors. Where does it stop?", "Floor −5", "Represent down 9 as −9 and compute 4 + (−9)."),
      q("Complete the comparison: −11 ___ −15.", "−11 > −15", "−11 is to the right of −15."),
      q("Find the distance between −6 and 5.", "11 units", "Distance is |5 − (−6)| = |11| = 11."),
      q("A student says |−8| = −8 because the input is negative. Repair the claim.", "|−8| = 8", "Absolute value is distance from zero, and distance is nonnegative."),
      q("Choose a number x with |x| = 4 and x < 0.", "x = −4", "The two values at distance 4 are −4 and 4; the negative one is −4."),
      q("A temperature changes from −2°C to 6°C. Find the signed change.", "+8°C", "Ending minus starting gives 6 − (−2) = 8."),
      q("Evaluate −3 + 5 − (−2) and justify each direction change.", "4", "Compute −3 + 5 + 2 = 4; subtracting −2 adds 2."),
    ],
    takeaway: ["A sign records direction from zero; absolute value records distance.", "Rewrite subtraction as addition of the opposite before combining signed values."],
  },
  "A0.2": {
    purpose: "Use place value and estimation to compute accurately and catch implausible calculator output.",
    prerequisites: [
      "Write 4,305 as a sum of place-value parts.",
      "State the value of the digit 7 in 27,416.",
      "Round 348 to the nearest ten.",
    ],
    exposition: [
      "Our base-ten system assigns a value to each digit according to position. In 52,407, the 5 means 50,000, while the 5 in 5.24 means 5 ones. Regrouping in addition, subtraction, multiplication, and division preserves the total while exchanging ten units of one place for one unit of the next place.",
      "Estimation is a planned check, not a careless substitute for computation. Rounding each input to one useful place gives an expected size before exact work begins. For 198 × 31, the estimate 200 × 30 = 6,000 predicts a four-digit product near 6,000.",
      "A result is plausible when its sign, size, and units fit the original quantities. Exact algorithms, mental decompositions, and calculators should agree. If a calculator reports 613.8 for 198 × 31, the estimate exposes a misplaced decimal immediately.",
    ],
    definitions: [
      ["place value", "The value a digit receives from its position in a base-ten numeral.", "Moving one place left multiplies the place value by 10."],
      ["order of magnitude", "The approximate power of ten describing a quantity’s size.", "It is used to reject scale errors, not to replace exact work."],
      ["regrouping", "Exchanging equal place-value amounts, such as 10 ones for 1 ten.", "The total value must remain unchanged."],
    ],
    examples: [
      ex("Estimate and calculate 198 × 31.", ["Estimate 200 × 30 = 6,000.", "Decompose 31 as 30 + 1.", "Compute 198·30 + 198 = 5,940 + 198."], "6,138", "The exact product is close to 6,000, so its size is plausible."),
      ex("Compute 4,002 − 587 using regrouping.", ["Regroup 4,002 as 3 thousands, 9 hundreds, 9 tens, and 12 ones.", "Subtract each place.", "Add 587 back to check."], "3,415", "The inverse-operation check recovers 4,002."),
      ex("A calculator shows 24,816 ÷ 8 = 31,020. Diagnose the error.", ["Estimate 24,000 ÷ 8 = 3,000.", "The displayed answer is about ten times too large.", "Compute or use multiplication to check the quotient."], "Correct quotient: 3,102", "The order-of-magnitude estimate catches the place-value error."),
    ],
    misconception: ["An exact calculator result does not need estimation.", "Typing or place-value errors can produce exact-looking output of the wrong size.", "Estimate first and compare the final digit count and scale with that estimate."],
    questions: [
      q("Write 70,406 in expanded form.", "70,000 + 400 + 6", "The 7 is ten-thousands, the 4 is hundreds, and the 6 is ones."),
      q("Round 48,762 to the nearest thousand.", "49,000", "The hundreds digit is 7, so round 48 thousand up."),
      q("Estimate 397 + 2,048 using one leading place for each number.", "About 2,400", "Use 400 + 2,000 = 2,400."),
      q("Calculate 397 + 2,048 and compare with the estimate.", "2,445", "Column addition gives 2,445, close to 2,400."),
      q("Calculate 8,000 − 2,675.", "5,325", "Regroup across the zeros, then verify 5,325 + 2,675 = 8,000."),
      q("Estimate 612 × 49.", "About 30,000", "Use 600 × 50 = 30,000."),
      q("Calculate 612 × 49 using 49 = 50 − 1.", "29,988", "Compute 612·50 − 612 = 30,600 − 612."),
      q("Estimate 15,960 ÷ 32.", "About 500", "Use 16,000 ÷ 32 = 500."),
      q("Calculate 15,960 ÷ 32.", "498.75", "32·498 = 15,936 with 24 remaining; 24/32 = 0.75."),
      q("Evaluate 18 + 6·4 − 5.", "37", "Multiply first: 18 + 24 − 5 = 37."),
      q("Insert parentheses so 8 + 4·3 equals 36.", "(8 + 4)·3 = 36", "Grouping makes addition happen before multiplication."),
      q("A grocery estimate is $52, but the receipt says $502. Name the likely issue.", "A decimal/place-value entry error", "$502 is roughly ten times the expected order of magnitude."),
      q("Which is more plausible for 2,997·21: 6,293 or 62,937?", "62,937", "3,000·20 is about 60,000."),
      q("Use multiplication to check 7,344 ÷ 24 = 306.", "Correct, because 306·24 = 7,344", "Compute 306(20 + 4) = 6,120 + 1,224."),
      q("A student computes 503 − 278 = 335. Find and repair the error.", "225", "The correct subtraction is 503 − 278 = 225; 225 + 278 = 503."),
      q("Estimate, calculate, and check 249·16.", "Estimate 4,000; exact 3,984", "Use 250·16 − 16 = 4,000 − 16 = 3,984."),
    ],
    takeaway: ["Place value explains every regrouping step.", "Estimate before calculating, then use an inverse operation to check exact work."],
  },
  "A0.3": {
    purpose: "Use prime factorization to answer GCF grouping questions and LCM synchronization questions.",
    prerequisites: [
      "List the multiplication facts that equal 24.",
      "Distinguish an even number from an odd number.",
      "Explain why 1 is a factor of every whole number.",
    ],
    exposition: [
      "A factor divides a whole number with no remainder. A prime number has exactly two positive factors, 1 and itself. Every whole number greater than 1 can be written as a product of primes, and that prime factorization is unique apart from order.",
      "The greatest common factor answers a shared-grouping question: what is the largest factor contained in every number? In prime-exponent form, take only primes shared by all numbers and use the smallest exponent present.",
      "The least common multiple answers a first-alignment question: what is the smallest positive multiple reached by every number? In prime-exponent form, include every needed prime and use the largest exponent present. Context tells you whether to seek a common divisor or a common multiple.",
    ],
    definitions: [
      ["prime factorization", "A whole number written as a product of prime numbers.", "For numbers greater than 1, the prime factors are unique apart from order."],
      ["greatest common factor", "The largest positive whole number dividing every given number.", "Use it for largest equal groups or largest equal-size pieces."],
      ["least common multiple", "The smallest positive whole number that is a multiple of every given number.", "Use it for first repeated alignment or a common denominator."],
    ],
    examples: [
      ex("Find the prime factorization of 360.", ["Divide by 2 repeatedly: 360 = 2·180 = 2²·90 = 2³·45.", "Factor 45 as 3²·5.", "Collect prime powers."], "360 = 2³·3²·5", "Multiplying the prime powers reconstructs 360."),
      ex("Find GCF(84, 126).", ["Write 84 = 2²·3·7.", "Write 126 = 2·3²·7.", "Take shared primes with smaller exponents."], "42", "Both numbers contain 2·3·7 = 42."),
      ex("Two lights flash every 12 seconds and 18 seconds. When do they next flash together?", ["Factor 12 = 2²·3 and 18 = 2·3².", "Take the largest exponent of each prime.", "Compute 2²·3²."], "36 seconds", "The first shared positive multiple is 36."),
    ],
    misconception: ["GCF and LCM are interchangeable because both use factors.", "GCF looks for shared divisors; LCM looks for a shared multiple and is usually at least as large as each input.", "Translate the context into 'largest equal group' or 'first alignment' before calculating."],
    questions: [
      q("List all positive factors of 18.", "1, 2, 3, 6, 9, 18", "Each listed number divides 18 with no remainder."),
      q("Classify 29 as prime or composite.", "Prime", "Its only positive factors are 1 and 29."),
      q("Write 72 as a product of prime powers.", "2³·3²", "72 = 8·9 = 2³·3²."),
      q("Write 150 as a product of prime powers.", "2·3·5²", "150 = 15·10 = 2·3·5²."),
      q("Find GCF(24, 36).", "12", "24 = 2³·3 and 36 = 2²·3²; take 2²·3."),
      q("Find GCF(45, 60, 75).", "15", "The primes shared by all three give 3·5 = 15."),
      q("Find LCM(8, 12).", "24", "8 = 2³ and 12 = 2²·3; take 2³·3."),
      q("Find LCM(15, 18).", "90", "15 = 3·5 and 18 = 2·3²; take 2·3²·5."),
      q("A teacher has 24 red and 36 blue markers. Find the greatest number of identical packs with no markers left.", "12 packs", "The largest number dividing 24 and 36 is GCF = 12."),
      q("Buses arrive every 20 and 30 minutes. If they arrive together now, when is the next shared arrival?", "60 minutes", "LCM(20,30) = 60."),
      q("Is 1 prime? Explain.", "No", "A prime must have exactly two positive factors; 1 has only one."),
      q("A student says GCF(18,24) = 72 because 72 is a common multiple. Repair the answer.", "GCF = 6", "The question asks for a common divisor; 6 is the largest number dividing both."),
      q("Find the missing exponent: 540 = 2²·3³·5^k.", "k = 1", "2²·3³·5 = 4·27·5 = 540."),
      q("Find the smallest number divisible by 6, 8, and 15.", "120", "LCM = 2³·3·5 = 120."),
      q("Tiles measuring 18 cm by 24 cm are cut into the largest possible equal square tiles. Find the side length.", "6 cm", "The side must divide both dimensions; GCF(18,24) = 6."),
      q("Explain why GCF(a,b)·LCM(a,b) = a·b for a = 12 and b = 18.", "6·36 = 12·18 = 216", "GCF is 6 and LCM is 36; both products equal 216."),
    ],
    takeaway: ["Prime factorization is a reusable inventory of multiplicative structure.", "Use GCF for largest shared pieces and LCM for first shared alignment."],
  },
  "A0.4": {
    purpose: "Treat fractions as numbers with magnitude, while connecting quotient, ratio, and operator meanings.",
    prerequisites: [
      "Divide a rectangle into four equal parts and shade one part.",
      "Locate 0, 1, and 2 on a number line.",
      "Explain what 12 ÷ 3 asks.",
    ],
    exposition: [
      "A fraction a/b is a number when b ≠ 0. It marks a points of size 1/b from zero on the number line. Because fractions are numbers, they can be ordered, added, multiplied, and used as coordinates just like whole numbers.",
      "The same notation also records a quotient a ÷ b, a ratio comparing a to b, or an operator taking a/b of a quantity. Context selects the meaning, but the value remains consistent. For example, 3/4 can mean the point 0.75, the quotient 3 ÷ 4, a 3-to-4 comparison, or three-fourths of a set.",
      "Equivalent fractions occupy the same number-line location. Multiplying numerator and denominator by the same nonzero number changes the partition labels but not the value. Comparison is safest with common denominators, common numerators, benchmarks, or cross-products whose signs are understood.",
    ],
    definitions: [
      ["numerator", "The count of selected unit-fraction parts.", "Its meaning depends on the denominator’s unit size."],
      ["denominator", "The number of equal parts in one whole and therefore the size 1/b of each part.", "It cannot be 0."],
      ["equivalent fractions", "Fractions naming the same number.", "Multiplying numerator and denominator by the same nonzero number preserves value."],
    ],
    examples: [
      ex("Locate 7/4 on a number line.", ["Rewrite 7/4 as 4/4 + 3/4.", "Start at 1 and move three fourth-size steps right.", "Mark the point between 1 and 2."], "7/4 = 1¾", "An improper fraction is still one number with a definite location."),
      ex("Compare 5/6 and 7/9.", ["Use common denominator 18.", "Rewrite 5/6 = 15/18 and 7/9 = 14/18.", "Compare numerators because the units are equal."], "5/6 > 7/9", "Common-sized parts make the comparison direct."),
      ex("Find 3/5 of 40.", ["Interpret 3/5 as an operator.", "Divide 40 into 5 equal groups of 8.", "Take 3 groups."], "24", "The operator meaning agrees with multiplication: (3/5)·40 = 24."),
    ],
    misconception: ["A larger denominator makes a larger positive fraction.", "For the same numerator, a larger denominator creates smaller parts.", "Compare fractions using equal wholes and common-sized parts or a benchmark."],
    questions: [
      q("Locate 3/5 between 0 and 1 and write its decimal value.", "0.6", "Three steps of size 1/5 reach 3/5 = 0.6."),
      q("Rewrite 11/4 as a mixed number.", "2¾", "11/4 = 8/4 + 3/4."),
      q("Rewrite 3⅖ as an improper fraction.", "17/5", "Three wholes are 15/5; add 2/5."),
      q("Generate a fraction equivalent to 7/12 with denominator 60.", "35/60", "Multiply numerator and denominator by 5."),
      q("Simplify 42/56.", "3/4", "Divide numerator and denominator by their GCF, 14."),
      q("Compare 4/7 and 5/9.", "4/7 > 5/9", "Cross-products are 36 and 35, so 4/7 is greater."),
      q("Order 2/3, 3/4, and 5/8 from least to greatest.", "5/8 < 2/3 < 3/4", "With denominator 24 they are 15/24, 16/24, and 18/24."),
      q("Which benchmark is closer to 9/10: 0, 1/2, or 1?", "1", "9/10 is only 1/10 below 1."),
      q("Interpret 8/3 as division.", "8 ÷ 3 = 2⅔", "The fraction bar represents division."),
      q("A class has 12 musicians and 18 non-musicians. Write the ratio musicians to all students as a simplified fraction.", "2/5", "There are 30 students; 12/30 simplifies to 2/5."),
      q("Find 7/8 of 32.", "28", "One eighth of 32 is 4; seven eighths is 28."),
      q("Explain why 2/3 = 8/12.", "Both equal the same point; multiply by 4/4", "Multiplying by 4/4 changes the partition, not the value."),
      q("A student says 3/8 > 3/5 because 8 > 5. Repair the comparison.", "3/8 < 3/5", "With equal numerators, fifths are larger pieces than eighths."),
      q("Find a fraction strictly between 1/3 and 1/2.", "For example, 5/12", "1/3 = 4/12 and 1/2 = 6/12, so 5/12 lies between."),
      q("State the restriction on a/b and explain it.", "b ≠ 0", "Division by zero has no real-number value, so a fraction cannot have denominator 0."),
      q("Use number, quotient, ratio, and operator meanings to describe 3/4.", "0.75; 3÷4; 3 to 4; three-fourths of a quantity", "Each interpretation represents the same fractional value in a different context."),
    ],
    takeaway: ["A fraction is a number with one exact location, even when it also represents a quotient, ratio, or operator.", "Equivalent fractions rename the same value using different unit fractions."],
  },
  "A0.5": {
    purpose: "Interpret fraction multiplication as scaling and fraction division as measuring how many groups fit.",
    prerequisites: [
      "Find 1/4 of 20.",
      "Simplify 12/18.",
      "Explain the difference between 12 ÷ 3 and 3 ÷ 12.",
    ],
    exposition: [
      "Multiplying by a fraction scales a quantity. A factor between 0 and 1 shrinks a positive quantity, while a factor greater than 1 enlarges it. The product (a/b)(c/d) = ac/bd follows from taking a/b of the quantity c/d.",
      "Division a ÷ b asks how many groups of size b fit into a. For fractions, (a/b) ÷ (c/d) can be solved by multiplying by d/c because one group of size c/d is counted by scaling with its reciprocal. This requires c/d ≠ 0.",
      "Area models, number-line jumps, and measurement-division diagrams explain the rules and give size checks. Before calculating, predict whether the result should be larger or smaller than the starting quantity.",
    ],
    definitions: [
      ["scaling factor", "A multiplier describing how a quantity changes size.", "For positive quantities, factors below 1 shrink and factors above 1 enlarge."],
      ["reciprocal", "For nonzero a/b, the number b/a whose product with a/b is 1.", "Zero has no reciprocal."],
      ["measurement division", "Division interpreted as the number of groups of a specified size contained in a quantity.", "Dividend and divisor order must be preserved."],
    ],
    examples: [
      ex("Compute 3/4 · 2/5 and interpret the size.", ["Multiply numerators and denominators.", "Simplify 6/20.", "Compare the product with both positive factors."], "3/10", "Taking three-fourths of two-fifths produces a smaller positive amount."),
      ex("Compute 5/6 ÷ 1/4.", ["Ask how many quarter-size groups fit in 5/6.", "Multiply 5/6 by the reciprocal 4.", "Simplify 20/6."], "10/3 = 3⅓", "More than three quarter-units fit into five-sixths."),
      ex("A recipe needs 2/3 cup per batch. How many batches can be made with 3½ cups?", ["Rewrite 3½ as 7/2.", "Compute (7/2) ÷ (2/3).", "Multiply by 3/2 and interpret the quotient."], "21/4 = 5¼ batches", "Five full batches can be made, with enough ingredient for one-quarter of another."),
    ],
    misconception: ["Multiplication always makes numbers larger and division always makes them smaller.", "The effect depends on the multiplier or divisor; dividing by a number below 1 increases the result.", "Predict size from the scale factor before applying the algorithm."],
    questions: [
      q("Compute 2/3 · 5/7.", "10/21", "Multiply numerators and denominators; no common factor remains."),
      q("Compute 4/9 · 3/8 using cancellation.", "1/6", "Cancel 4 with 8 and 3 with 9 before multiplying."),
      q("Find 5/12 of 36.", "15", "36·5/12 = 3·5 = 15."),
      q("Compute 1⅔ · 3/5.", "1", "Convert 1⅔ to 5/3; (5/3)(3/5) = 1."),
      q("Without exact calculation, decide whether 7/8·2/3 is less than or greater than 7/8.", "Less than 7/8", "Multiplication by 2/3 scales a positive number down."),
      q("Compute 3/4 ÷ 2/5.", "15/8 = 1⅞", "Multiply 3/4 by 5/2."),
      q("Compute 5/6 ÷ 10/9.", "3/4", "Multiply 5/6 by 9/10 and simplify."),
      q("Compute 2⅕ ÷ 3/10.", "22/3 = 7⅓", "Convert 2⅕ to 11/5, then multiply by 10/3."),
      q("How many 1/6-mile segments fit in 2½ miles?", "15", "Compute 5/2 ÷ 1/6 = 5/2·6 = 15."),
      q("A 3/4-yard ribbon is split into pieces 1/8 yard long. How many pieces?", "6", "Compute 3/4 ÷ 1/8 = 3/4·8 = 6."),
      q("Find the missing factor: 3/5·x = 9/10.", "x = 3/2", "Divide 9/10 by 3/5: 9/10·5/3 = 3/2."),
      q("Explain why dividing by 2/3 is the same as multiplying by 3/2.", "Because 3/2 is the reciprocal of 2/3", "Multiplying by the reciprocal counts groups of size 2/3."),
      q("A student computes 4/5 ÷ 2/3 as 8/15. Repair the work.", "6/5", "Keep the dividend and multiply by the reciprocal: 4/5·3/2 = 6/5."),
      q("Which is larger: 3/4 ÷ 1/2 or 3/4·1/2?", "3/4 ÷ 1/2 = 3/2", "Division by 1/2 doubles; multiplication by 1/2 halves."),
      q("A map scale is 3/8 inch per mile. How many miles does 2¼ inches represent?", "6 miles", "Compute 9/4 ÷ 3/8 = 9/4·8/3 = 6."),
      q("Evaluate (2/3·9/10) ÷ 3/5 and explain the size.", "1", "The product is 3/5, and (3/5) ÷ (3/5) = 1."),
    ],
    takeaway: ["Multiplication by a fraction is scaling; predict whether the scale enlarges or shrinks.", "Division by a nonzero fraction counts groups and is implemented by multiplying by its reciprocal."],
  },
  "A0.6": {
    purpose: "Combine fractions using common-sized parts and simplify complex fractions without losing grouping.",
    prerequisites: [
      "Find LCM(6, 8).",
      "Generate an equivalent fraction for 2/3 with denominator 12.",
      "Explain why 1/2 + 1/3 cannot be 2/5.",
    ],
    exposition: [
      "Fractions can be added or subtracted only after their parts have the same size. A common denominator names a shared unit fraction; the least common denominator often minimizes later simplification.",
      "The numerator records how many common parts are combined, while the denominator keeps naming the part size. Mixed numbers may be converted to improper fractions or handled by combining whole and fractional parts carefully.",
      "A complex fraction is one fraction whose numerator, denominator, or both contain fractions. Treat the main fraction bar as a grouping symbol. Simplify its numerator and denominator separately, or multiply every term by a common denominator to clear the smaller fractions.",
    ],
    definitions: [
      ["common denominator", "A shared denominator that makes fraction parts the same size.", "Only numerators combine after equivalent forms are established."],
      ["least common denominator", "The least common multiple of the denominators.", "It is efficient but any valid common denominator preserves value."],
      ["complex fraction", "A fraction containing another fraction in its numerator or denominator.", "The main fraction bar groups the entire numerator and denominator."],
    ],
    examples: [
      ex("Compute 5/6 − 1/4.", ["Use LCD 12.", "Rewrite 5/6 = 10/12 and 1/4 = 3/12.", "Subtract the numerators."], "7/12", "Both quantities are expressed in twelfths before subtraction."),
      ex("Compute 2⅓ + 1¾.", ["Convert to 7/3 + 7/4.", "Use denominator 12: 28/12 + 21/12.", "Add and convert back."], "49/12 = 4 1/12", "The result is slightly greater than 4, matching an estimate."),
      ex("Simplify (1/2 + 1/3)/(5/6).", ["Combine the numerator: 1/2 + 1/3 = 5/6.", "Treat the main bar as division.", "Compute (5/6) ÷ (5/6)."], "1", "The grouped numerator equals the denominator."),
    ],
    misconception: ["Add denominators when adding fractions.", "The denominator names the part size; changing it during addition changes the units.", "Rename both fractions with common-sized parts, then combine only the part counts."],
    questions: [
      q("Compute 2/3 + 1/6.", "5/6", "Rewrite 2/3 as 4/6, then add."),
      q("Compute 7/8 − 5/12.", "11/24", "Use denominator 24: 21/24 − 10/24."),
      q("Compute 3/10 + 7/15.", "23/30", "Use denominator 30: 9/30 + 14/30."),
      q("Compute 5/9 − 2/3.", "−1/9", "Rewrite 2/3 as 6/9."),
      q("Compute 1⅝ + 2¾.", "4⅜", "Use eighths: 1⅝ + 2 6/8 = 4 3/8."),
      q("Compute 6⅓ − 2⅚.", "3½", "Use sixths: 6 2/6 − 2 5/6 = 3 3/6."),
      q("Evaluate 1 − 7/12.", "5/12", "Rewrite 1 as 12/12."),
      q("Find x: x + 3/8 = 5/6.", "x = 11/24", "Subtract 3/8 from 5/6 using denominator 24."),
      q("Simplify (1/3)/(5/6).", "2/5", "Compute 1/3 ÷ 5/6 = 1/3·6/5."),
      q("Simplify (3/4 + 1/2)/(5/8).", "2", "The numerator is 5/4; divide by 5/8 to get 2."),
      q("Simplify (2/3)/(1/4 + 1/12).", "2", "The denominator is 1/3; (2/3) ÷ (1/3) = 2."),
      q("Simplify (1/x + 1/y)/(1/(xy)) for nonzero x and y.", "x + y", "The numerator is (x+y)/(xy); dividing by 1/(xy) gives x+y."),
      q("A student says 2/5 + 1/3 = 3/8. Repair the answer.", "11/15", "Use denominator 15: 6/15 + 5/15."),
      q("Explain why 12 is a useful denominator for 1/3 + 1/4.", "12 is LCM(3,4)", "Twelfths are the smallest common-sized parts for thirds and fourths."),
      q("A tank is 5/6 full and 1/4 of its total capacity is drained. What fraction remains?", "7/12", "Compute 5/6 − 1/4 = 10/12 − 3/12."),
      q("Evaluate 1/2 + 3/4 − 5/6 and check with a decimal estimate.", "5/12", "Use denominator 12: 6/12 + 9/12 − 10/12 = 5/12, about 0.417."),
    ],
    takeaway: ["Addition and subtraction require common-sized fractional parts.", "In a complex fraction, the main fraction bar groups the complete numerator and denominator."],
  },
  "A0.7": {
    purpose: "Move accurately among fractions, decimals, and percents and choose the representation that best answers the question.",
    prerequisites: [
      "Read 0.37 using place value.",
      "Simplify 25/100.",
      "Explain what percent means literally.",
    ],
    exposition: [
      "Fractions, decimals, and percents can name the same number. A decimal uses powers of ten, while a percent states how many hundredths. Converting representations should preserve the number-line location.",
      "To convert a fraction to a decimal, divide numerator by denominator. To convert a decimal to a percent, multiply by 100 and attach the percent symbol; reversing that move divides by 100. Terminating decimals arise when a reduced denominator has only factors 2 and 5.",
      "Representation is a strategic choice. Percents communicate relative change, decimals support calculator work and money, and fractions often preserve exact values and multiplicative structure.",
    ],
    definitions: [
      ["percent", "A ratio measured per hundred.", "p% = p/100."],
      ["terminating decimal", "A decimal representation ending after finitely many digits.", "In lowest terms, its denominator has no prime factors other than 2 and 5."],
      ["repeating decimal", "A decimal with a digit block that repeats forever.", "It represents an exact rational number."],
    ],
    examples: [
      ex("Convert 7/20 to a decimal and percent.", ["Make denominator 100 or divide 7 by 20.", "Obtain 0.35.", "Multiply by 100 for percent."], "0.35 = 35%", "All three forms mark the same point."),
      ex("Convert 0.125 to a simplified fraction and percent.", ["Write 125/1000.", "Divide numerator and denominator by 125.", "Multiply the decimal by 100."], "1/8 = 12.5%", "The fraction is exact and the percent is useful for comparison."),
      ex("Order 62%, 5/8, and 0.61.", ["Convert to decimals.", "62% = 0.62 and 5/8 = 0.625.", "Compare thousandths."], "0.61 < 62% < 5/8", "A common representation makes order visible."),
    ],
    misconception: ["To convert a decimal to a percent, just add a percent sign.", "The percent sign means divide by 100, so the numeral must be scaled by 100 first.", "Check that the converted form occupies the same number-line location."],
    questions: [
      q("Convert 3/5 to a decimal and percent.", "0.6 = 60%", "3 ÷ 5 = 0.6; multiply by 100."),
      q("Convert 7/8 to a decimal and percent.", "0.875 = 87.5%", "7 ÷ 8 = 0.875."),
      q("Convert 0.42 to a fraction in lowest terms.", "21/50", "0.42 = 42/100 = 21/50."),
      q("Convert 1.375 to a mixed number.", "1⅜", "1.375 = 1 + 375/1000 = 1 + 3/8."),
      q("Convert 135% to a decimal and fraction.", "1.35 = 27/20", "135/100 simplifies to 27/20."),
      q("Convert 0.006 to a percent.", "0.6%", "Multiply 0.006 by 100."),
      q("Convert 2/9 to a repeating decimal.", "0.222…", "2 ÷ 9 repeats the digit 2."),
      q("Write 0.333… as a fraction.", "1/3", "Let x = 0.333…; 10x − x = 3, so 9x = 3."),
      q("Order 0.48, 49%, and 1/2.", "0.48 < 49% < 1/2", "They are 0.48, 0.49, and 0.50."),
      q("Which is the clearest form for a 15-out-of-20 quiz score when comparing grades?", "75%", "15/20 = 0.75 = 75%; percent supports grade comparison."),
      q("Which is exact: 1/3 or 0.33?", "1/3", "0.33 = 33/100, which is slightly less than 1/3."),
      q("A student writes 0.7 = 0.7%. Repair the statement.", "0.7 = 70%", "Multiply the decimal by 100 before attaching %."),
      q("Explain why 3/40 terminates as a decimal.", "40 = 2³·5", "The reduced denominator has only prime factors 2 and 5."),
      q("Find a fraction equal to 12.5%.", "1/8", "12.5% = 0.125 = 125/1000 = 1/8."),
      q("A price is discounted by 0.2 of its value. State the percent discount.", "20%", "0.2·100 = 20."),
      q("Evaluate 3/4 + 25% and give the result in all three forms.", "1 = 1.0 = 100%", "25% = 1/4, so 3/4 + 1/4 = 1."),
    ],
    takeaway: ["Conversion changes notation, not value.", "Choose fractions for exact structure, decimals for place-value computation, and percents for per-hundred comparison."],
  },
  "A0.8": {
    purpose: "Use ratios and unit rates to build proportional relationships and distinguish percent change from percentage-point change.",
    prerequisites: [
      "Simplify the fraction 18/24.",
      "Find 3/4 of 20.",
      "State the units of 150 miles divided by 3 hours.",
    ],
    exposition: [
      "A ratio compares quantities in a specified order. A rate is a ratio with different units, and a unit rate has denominator 1. Equivalent ratios result from multiplying both quantities by the same nonzero scale factor.",
      "A proportional relationship has a constant unit rate k and can be written y = kx. Ratio tables, double number lines, equations, and graphs all represent the same multiplicative structure. Cross-products are a consequence of equality between two ratios, not a reason to ignore units.",
      "Percent change compares the change with the original amount: (new − original)/original · 100%. A change from 40% to 50% is a 10-percentage-point increase but a 25% relative increase because 10 is one-fourth of the original 40.",
    ],
    definitions: [
      ["unit rate", "A rate expressed per one unit of the denominator quantity.", "Units and order must remain attached."],
      ["proportional relationship", "A relationship y = kx with constant ratio y/x = k.", "Its graph passes through the origin."],
      ["percent change", "Change divided by the original amount, expressed per hundred.", "The original amount is the reference denominator."],
    ],
    examples: [
      ex("A 5-pound bag costs $8.75. Find the unit price.", ["Divide cost by pounds.", "Compute 8.75 ÷ 5.", "Attach dollars per pound."], "$1.75 per pound", "The unit rate supports direct price comparison."),
      ex("Three notebooks cost $7.50. Predict the cost of 8 notebooks.", ["Find $7.50 ÷ 3 = $2.50 per notebook.", "Multiply the unit rate by 8.", "Check that cost/notebook remains constant."], "$20", "The model C = 2.5n is proportional."),
      ex("A price rises from $80 to $92. Find percent change.", ["Compute change 92 − 80 = 12.", "Divide by original price: 12/80.", "Convert to percent."], "15% increase", "The original $80 is the reference amount."),
    ],
    misconception: ["Percent change is change divided by the new amount.", "Relative change measures the change against the original baseline.", "Label original and new values before writing the fraction."],
    questions: [
      q("Simplify the ratio 18:30.", "3:5", "Divide both terms by 6."),
      q("A car travels 156 miles in 3 hours. Find the unit rate.", "52 miles per hour", "156 ÷ 3 = 52."),
      q("A 12-ounce box costs $4.20. Find cents per ounce.", "35 cents per ounce", "$4.20 = 420 cents; 420 ÷ 12 = 35."),
      q("Complete the ratio: 4/7 = x/35.", "x = 20", "The denominator scales by 5, so the numerator does too."),
      q("Do (6,15) and (10,25) represent the same ratio?", "Yes", "15/6 = 25/10 = 2.5."),
      q("If y is proportional to x and y = 18 when x = 6, find k.", "k = 3", "k = y/x = 18/6."),
      q("Using y = 3x, find y when x = 14.", "42", "Substitute x = 14: y = 3·14."),
      q("A map uses 1 inch for 25 miles. How far does 3.6 inches represent?", "90 miles", "3.6·25 = 90."),
      q("A recipe ratio is 2 cups rice to 5 cups water. Find water for 7 cups rice.", "17.5 cups", "The unit rate is 5/2 cups water per cup rice; multiply by 7."),
      q("A $60 item rises to $69. Find percent increase.", "15%", "Change is 9; 9/60 = 0.15."),
      q("A population falls from 500 to 425. Find percent decrease.", "15% decrease", "Decrease is 75; 75/500 = 0.15."),
      q("A rate rises from 40% to 50%. Find percentage-point and relative increases.", "10 points; 25% relative", "The point change is 10; 10/40 = 25%."),
      q("A student solves 3/5 = x/20 as x = 12 but omits units. What must be added if the ratio is cups to servings?", "12 cups, if x is the cup quantity", "The ordered ratio determines the unit attached to x."),
      q("Which relationship is proportional: y = 4x or y = 4x + 2?", "y = 4x", "A proportional relationship has no added constant and passes through the origin."),
      q("A 20% discount is followed by a 20% increase. Does the price return to the original?", "No; it becomes 96% of original", "0.8·1.2 = 0.96."),
      q("Compare $2.70 for 9 ounces with $4.00 for 16 ounces.", "$4.00 for 16 ounces is cheaper", "Unit prices are $0.30/oz and $0.25/oz."),
    ],
    takeaway: ["Equivalent ratios preserve one constant multiplicative relationship.", "Percent change uses the original amount as its reference; percentage points measure a different difference."],
  },
  "A0.9": {
    purpose: "Use units as algebraic factors to guide conversions and reject dimensionally impossible formulas.",
    prerequisites: [
      "State the units of distance divided by time.",
      "Recall that 1 foot = 12 inches.",
      "Multiply 3/4 by 8.",
    ],
    exposition: [
      "A measurement is a number multiplied by a unit. Units behave like algebraic factors: identical units can be added, reciprocal units can cancel in products, and incompatible dimensions cannot be combined by addition.",
      "A conversion factor is a ratio equal to 1, such as 12 in/1 ft. Multiplying by a correctly oriented conversion factor changes the unit label without changing the physical amount. Arrange factors so unwanted units cancel.",
      "Dimensional analysis is also an error check. Distance = rate·time is plausible because (miles/hour)(hours) leaves miles. Distance = rate + time is impossible because miles/hour and hours are unlike dimensions.",
    ],
    definitions: [
      ["dimension", "The physical type of a quantity, such as length, time, mass, or area.", "Quantities added or compared directly must have compatible dimensions."],
      ["conversion factor", "A ratio of equal measurements and therefore a multiplicative value of 1.", "Orient it so the unwanted unit cancels."],
      ["dimensional consistency", "Agreement of units on both sides of a formula or equation.", "Consistency is necessary but does not by itself prove the formula is correct."],
    ],
    examples: [
      ex("Convert 7.5 feet to inches.", ["Use 12 in/1 ft.", "Multiply 7.5 ft·12 in/ft.", "Cancel feet."], "90 inches", "The physical length is unchanged."),
      ex("Convert 60 miles per hour to miles per minute.", ["Use 1 hour/60 minutes.", "Multiply 60 mi/hr·1 hr/60 min.", "Cancel hours."], "1 mile per minute", "The conversion factor changes only the time unit."),
      ex("Check the formula d = vt + 1/2at².", ["vt has units (L/T)T = L.", "at² has units (L/T²)T² = L.", "Both terms and d have length units."], "Dimensionally consistent", "Every added term has the same dimension."),
    ],
    misconception: ["Conversion factors may be placed in either orientation.", "Only one orientation cancels the unwanted unit and leaves the target unit.", "Write units on every factor and cancel them before multiplying numbers."],
    questions: [
      q("Convert 4.25 feet to inches.", "51 inches", "4.25 ft·12 in/ft = 51 in."),
      q("Convert 3.2 kilometers to meters.", "3,200 meters", "3.2 km·1000 m/km = 3200 m."),
      q("Convert 450 seconds to minutes.", "7.5 minutes", "450 s·1 min/60 s = 7.5 min."),
      q("Convert 72 kilometers per hour to kilometers per minute.", "1.2 km/min", "72 km/hr·1 hr/60 min = 1.2 km/min."),
      q("Convert 5 square feet to square inches.", "720 in²", "Use (12 in/1 ft)², so 5·144 = 720."),
      q("A car travels 180 miles in 3 hours. Find its average speed with units.", "60 miles per hour", "180 mi/3 hr = 60 mi/hr."),
      q("At 60 miles per hour for 2.5 hours, find distance.", "150 miles", "60 mi/hr·2.5 hr = 150 mi."),
      q("Which can be added directly: 3 meters + 40 centimeters or 3 meters + 4 seconds?", "The two lengths, after conversion", "Meters and centimeters share the length dimension; seconds do not."),
      q("Evaluate 3 m + 40 cm in meters.", "3.4 m", "40 cm = 0.4 m; add compatible units."),
      q("Check d = v/t dimensionally.", "Inconsistent for distance", "(L/T)/T = L/T², not L."),
      q("Check area = length + width dimensionally.", "Dimensionally inconsistent", "The right side has length units, while area requires length squared."),
      q("A density is 8 g/cm³ and volume is 5 cm³. Find mass.", "40 g", "(8 g/cm³)(5 cm³) = 40 g."),
      q("A student converts 2 hours using 60 hr/1 min. Repair the factor.", "Use 60 min/1 hr; result 120 min", "Hours must cancel and minutes must remain."),
      q("Convert 10 meters per second to meters per minute.", "600 m/min", "10 m/s·60 s/min = 600 m/min."),
      q("Explain why 1 m² is not 100 cm².", "1 m² = 10,000 cm²", "Square the linear conversion: (100 cm)² = 10,000 cm²."),
      q("A formula gives energy in kg·m²/s². Confirm that force times distance has the same units if force is kg·m/s².", "Yes", "(kg·m/s²)(m) = kg·m²/s²."),
    ],
    takeaway: ["Treat each unit as an algebraic factor and cancel deliberately.", "Only quantities with compatible dimensions may be added or equated."],
  },
  "A0.10": {
    purpose: "Interpret powers as repeated multiplication, roots as inverse questions, and scientific notation as controlled place value.",
    prerequisites: [
      "Compute 4·4·4.",
      "Name the side length of a 5-by-5 square.",
      "Identify the place value of the 6 in 60,000.",
    ],
    exposition: [
      "A power aⁿ abbreviates repeated multiplication of the base a. Exponent laws come from counting repeated factors, so they apply only under their stated conditions. For example, aᵐaⁿ = aᵐ⁺ⁿ combines factors with the same base.",
      "A root reverses a power question. √49 asks for the nonnegative number whose square is 49, while solving x² = 49 produces two real solutions, x = ±7. The radical symbol denotes the principal root, not both roots.",
      "Scientific notation writes a nonzero number as a·10ⁿ with 1 ≤ |a| < 10. The exponent records place-value shifts and makes multiplication, division, and order-of-magnitude comparison transparent.",
    ],
    definitions: [
      ["base and exponent", "In aⁿ, the base a is multiplied repeatedly and the exponent n counts factors for positive whole n.", "Parentheses determine whether a negative sign belongs to the base."],
      ["principal square root", "The nonnegative number whose square equals the radicand.", "√x is real only for x ≥ 0 in the real-number system."],
      ["scientific notation", "A number a·10ⁿ with 1 ≤ |a| < 10 and integer n.", "The coefficient must have exactly one nonzero digit before the decimal point."],
    ],
    examples: [
      ex("Simplify 2³·2⁵/2⁴.", ["Add exponents in the numerator.", "Subtract the denominator exponent.", "Evaluate 2⁴."], "16", "The repeated-factor count is 3 + 5 − 4 = 4."),
      ex("Solve x² = 81 and compare with √81.", ["Take square roots of both sides while solving.", "Include both signs for the equation.", "Evaluate the principal radical separately."], "x = ±9; √81 = 9", "An equation’s solution set differs from the radical symbol’s single principal value."),
      ex("Multiply (3.0·10⁵)(4.0·10⁻³).", ["Multiply coefficients to get 12.", "Add exponents to get 10².", "Renormalize 12·10² as 1.2·10³."], "1.2·10³", "Scientific notation keeps the order of magnitude visible."),
    ],
    misconception: ["(−3)² and −3² are the same.", "Exponentiation applies before an ungrouped leading negative; parentheses make −3 the base.", "Identify the complete base before evaluating the power."],
    questions: [
      q("Evaluate 5³.", "125", "5³ = 5·5·5 = 125."),
      q("Evaluate (−2)⁴ and −2⁴.", "16 and −16", "Parentheses make −2 the base in the first expression only."),
      q("Simplify x⁴·x⁷.", "x¹¹", "Add exponents for the same base."),
      q("Simplify y⁹/y³ for y ≠ 0.", "y⁶", "Subtract exponents: 9 − 3 = 6."),
      q("Simplify (a³)⁴.", "a¹²", "A power of a power multiplies exponents."),
      q("Rewrite 3⁻² with a positive exponent.", "1/9", "3⁻² = 1/3²."),
      q("Evaluate √144.", "12", "12² = 144 and the radical means the nonnegative root."),
      q("Solve x² = 36.", "x = ±6", "Both 6 and −6 square to 36."),
      q("Evaluate ∛(−125).", "−5", "(−5)³ = −125."),
      q("Write 6,420,000 in scientific notation.", "6.42·10⁶", "Move the decimal six places left."),
      q("Write 3.08·10⁻⁴ in standard notation.", "0.000308", "Move the decimal four places left."),
      q("Multiply (2·10⁴)(7·10³).", "1.4·10⁸", "2·7 = 14 and 10⁴·10³ = 10⁷; renormalize."),
      q("Divide (8.4·10⁷)/(2.1·10³).", "4·10⁴", "Divide coefficients and subtract exponents."),
      q("Which is larger: 7.2·10⁵ or 6.9·10⁶?", "6.9·10⁶", "The exponent 6 represents an order of magnitude larger than 5."),
      q("A student simplifies 2³ + 2⁴ as 2⁷. Repair the work.", "8 + 16 = 24", "Exponent addition applies to multiplication, not addition."),
      q("Simplify (4·10³)² and state its order of magnitude.", "1.6·10⁷", "Square both factors: 16·10⁶ = 1.6·10⁷."),
    ],
    takeaway: ["Exponent laws are justified by repeated-factor structure and grouping.", "A radical gives a principal root; an equation may require both signs.", "Scientific notation makes place value and order of magnitude explicit."],
  },
};
