const ex = (prompt, steps, answer, interpretation) => ({ prompt, steps, answer, interpretation });
const q = (prompt, answer, solution) => ({ prompt, answer, solution });

export const A1_PROFILES = {
  "A1.1": {
    purpose: "Name each quantity’s role before using symbols so variables, unknowns, parameters, constants, and labels are not confused.",
    prerequisites: ["Identify what changes in a distance-over-time table.", "Distinguish a number from a unit label.", "Describe the horizontal and vertical quantities on a simple graph."],
    exposition: [
      "A variable is a symbol assigned to a quantity, not merely a letter waiting to be solved. Its role comes from context. In h(t), time t varies and altitude h depends on it. A letter can instead represent one unknown value, a fixed parameter controlling a family, or a label with no numerical role.",
      "A constant keeps the same value within the model. A parameter is held fixed during one instance but may change between instances. In C = mt + b, t may vary, C depends on t, and m and b act as parameters selecting one cost plan.",
      "Good algebra begins with a quantity dictionary: symbol, meaning, units, allowed values, and role. This prevents meaningless substitutions and makes graphs, tables, and formulas describe the same relationship.",
    ],
    definitions: [
      ["variable quantity", "A quantity allowed to take more than one value in the situation.", "Its allowable values form its domain."],
      ["unknown", "A fixed but not yet determined value satisfying stated conditions.", "An unknown is not necessarily changing."],
      ["parameter", "A value held fixed in one model but varied to compare a family of models.", "State what the parameter controls."],
    ],
    examples: [
      ex("In h = 1200 − 80t, identify each quantity and role.", ["Read h as altitude in feet and t as elapsed time in seconds.", "t varies and h depends on t.", "1200 and −80 are constants describing initial altitude and rate."], "t: independent variable; h: dependent variable; 1200 and −80: constants", "Symbols gain meaning from the quantity dictionary."),
      ex("In y = mx + b, explain why m is often a parameter.", ["Hold m fixed to draw one line.", "Change m to select a different line.", "Observe that x still varies along each chosen line."], "m controls the line’s slope", "A parameter indexes a family while variables move within one member."),
      ex("A box marked A contains 12 bolts. Is A a variable?", ["Ask whether A is assigned a numerical quantity.", "Here A only names the box.", "The bolt count 12 is the numerical constant."], "No; A is a label", "Not every letter in a mathematical display is a variable."),
    ],
    misconception: ["Every letter is an unknown that must be solved.", "Letters can name changing quantities, parameters, constants, units, objects, or labels.", "Write a symbol-to-quantity dictionary before manipulating a formula."],
    questions: [
      q("In d = 55t, identify the independent and dependent quantities.", "t independent; d dependent", "Elapsed time is chosen and distance changes with it."),
      q("In A = πr², identify the constant and variable quantities.", "π constant; r and A variables", "π is fixed; area depends on radius."),
      q("In C = 12n + 35, interpret 12 and 35 for a service plan.", "12 is cost per unit; 35 is fixed cost", "The coefficient scales usage and the constant is present at zero usage."),
      q("Is x in x + 7 = 19 changing or unknown?", "A fixed unknown", "The equation asks for one value making the statement true."),
      q("In f_a(x) = ax², explain the role of a.", "Parameter controlling the parabola", "For fixed a, x varies; changing a selects a different function."),
      q("A graph labels a point P. Must P be a number?", "No", "P may name a point rather than a numerical quantity."),
      q("Create a quantity dictionary for p = 3s + 2 where s is side length in cm and p is perimeter in cm.", "s: side length (cm), independent; p: perimeter (cm), dependent", "The coefficient and constant define how perimeter depends on side length."),
      q("Which values are reasonable for the number n of students in a room?", "Nonnegative whole numbers", "Counts cannot be negative or fractional."),
      q("Which values are reasonable for elapsed time t in a race model?", "t ≥ 0", "Elapsed time begins at zero."),
      q("In V = lwh, which quantity depends on the other three?", "V", "Volume is determined by length, width, and height."),
      q("A student calls °C a variable in T = 20°C. Repair the claim.", "°C is the unit; T is the quantity symbol", "The unit labels the measurement scale."),
      q("Give one context where k is a constant and one where it is a parameter.", "Examples vary", "A fixed conversion factor is constant; a rate changed across model comparisons is a parameter."),
      q("For y = 2x + b, what stays fixed while viewing one line?", "2 and b", "x varies and y depends on x; coefficients select the line."),
      q("Explain why using m for both mass and meters in one formula is ambiguous.", "The same symbol would have two roles", "Distinct meanings need distinct notation or explicit unit formatting."),
      q("A tank starts with 100 L and drains at r L/min. Name roles in V = 100 − rt.", "V dependent, t independent, r parameter, 100 constant", "The formula’s context assigns each role."),
      q("Write a complete variable declaration for the cost of x adult tickets at $14 each.", "Let x be the nonnegative whole-number count of adult tickets; C = 14x dollars", "The declaration includes meaning, domain, and units."),
    ],
    takeaway: ["A symbol’s role comes from the quantity it represents and the context in which it is used.", "Declare meaning, units, and allowed values before operating on symbols."],
  },
  "A1.2": {
    purpose: "Classify expressions, equations, and inequalities so the goal of the work is clear before any manipulation.",
    prerequisites: ["Evaluate 3·4 + 2.", "State whether 11 = 11 is true.", "Compare 9 and 12 using an order symbol."],
    exposition: [
      "An expression names a value but does not make a claim, so 3x + 2 has no truth value by itself. An equation claims two expressions are equal. An inequality claims one expression is ordered relative to another.",
      "Evaluation finds an expression’s value for supplied inputs. Solving finds all inputs that make an equation or inequality true. Simplifying rewrites an expression without changing its value on its domain. These are different goals and require different conclusions.",
      "The equal sign means 'has the same value as,' not 'the answer comes next.' Reading a chain such as 2(5)+1 = 10+1 = 11 is valid because every expression in the chain has the same value.",
    ],
    definitions: [
      ["expression", "A mathematical object that names a value.", "It has no true-or-false status by itself."],
      ["equation", "A statement that two expressions have equal value.", "Its solution set contains inputs making the statement true."],
      ["inequality", "A statement comparing the order of two expressions.", "Its solution set often contains an interval of values."],
    ],
    examples: [
      ex("Classify 4x − 7, 4x − 7 = 9, and 4x − 7 < 9.", ["Look for a relation symbol.", "No relation symbol means expression.", "= makes an equation; < makes an inequality."], "Expression; equation; inequality", "Classification identifies whether to evaluate, solve, or compare."),
      ex("Evaluate 4x − 7 at x = 3.", ["Substitute 3 for x.", "Preserve multiplication.", "Compute 12 − 7."], "5", "Evaluation returns a value, not a solution set."),
      ex("Determine whether x = 3 solves 4x − 7 = 5.", ["Substitute 3 on the left.", "Compute 5.", "Compare both sides."], "Yes", "The resulting true statement 5 = 5 verifies the solution."),
    ],
    misconception: ["An expression can be solved.", "An expression has no claim to make true; it can be evaluated or simplified.", "Name the object and the requested action before beginning."],
    questions: [
      q("Classify 5a² − 3a + 1.", "Expression", "There is no equality or order relation."),
      q("Classify 2n + 4 = 18.", "Equation", "The equal sign creates a true-or-false statement."),
      q("Classify 7 − 3t ≥ 10.", "Inequality", "The ≥ symbol compares order."),
      q("Evaluate 2x² − 3 at x = −2.", "5", "2(−2)² − 3 = 8 − 3."),
      q("Is 4 a solution of 3x + 1 = 13?", "Yes", "3·4 + 1 = 13."),
      q("Is −1 a solution of 2x − 5 > −6?", "No", "2(−1) − 5 = −7, and −7 > −6 is false."),
      q("What is the goal when simplifying 3(x+2)+x?", "Rewrite as an equivalent expression", "Simplifying preserves value for every allowed x."),
      q("What is the goal when solving 3(x+2)+x = 18?", "Find all x making the equation true", "Solving determines a solution set."),
      q("Repair the chain 3·4 + 2 = 12 = 14.", "3·4 + 2 = 12 + 2 = 14", "Every adjacent expression in an equality chain must have the same value."),
      q("Write an equation representing 'five more than twice x is 19.'", "2x + 5 = 19", "The word 'is' supplies equality."),
      q("Write an inequality representing 'the cost c is at most $40.'", "c ≤ 40", "At most includes 40 and all smaller values."),
      q("Does x + 2 name a proposition?", "No", "It names a value but makes no claim."),
      q("Give the truth value of 3(5) − 2 = 13.", "True", "Both sides equal 13."),
      q("A student writes 2x + 3 = 5x as a simplification step with no original equation. What is wrong?", "It invents an equality that is not true for every x", "Expressions may be rewritten only with equivalent forms."),
      q("Describe the solution-set type likely produced by x < 4.", "An interval of infinitely many numbers", "Every real number below 4 satisfies the inequality."),
      q("Classify and complete the correct action for 6y − 1 when y = 2.", "Expression; evaluate to 11", "Substitution gives 12 − 1 = 11."),
    ],
    takeaway: ["Expressions name values; equations and inequalities make claims.", "Evaluation, simplification, and solving answer different questions."],
  },
  "A1.3": {
    purpose: "Read sums, products, coefficients, and nested grouping from the outside in without flattening structure.",
    prerequisites: ["Identify the addends in 7 + 4.", "Identify the factors in 7·4.", "Explain what parentheses group in 3(2+5)."],
    exposition: [
      "Terms are the addends of a sum, while factors are the multiplicative pieces of a product. In 3x + 5, the terms are 3x and 5; inside the first term, 3 and x are factors. A coefficient is the numerical factor multiplying a variable expression.",
      "Structure is nested. In 2(x + 4) − 3, the outermost operation is subtraction, while multiplication and addition occur inside its parts. Reading the expression tree from the outside inward prevents illegal combinations.",
      "A fraction bar groups the entire numerator and denominator. In (x+1)/(x−2), neither plus nor minus is an outermost operation; the whole numerator is divided by the whole denominator.",
    ],
    definitions: [
      ["term", "An addend in a sum after subtraction is interpreted as adding an opposite.", "Terms are identified at the current grouping level."],
      ["factor", "A multiplicative component of a product.", "Factors can themselves be grouped sums or quotients."],
      ["coefficient", "A numerical factor multiplying a variable or variable expression.", "The implied coefficient of x is 1 and of −x is −1."],
    ],
    examples: [
      ex("Describe the structure of 4x² − 3x + 7.", ["Read subtraction as addition of opposites.", "Identify three terms.", "Identify coefficients 4, −3, and constant 7."], "Terms: 4x², −3x, 7", "Terms are separated only at the outer sum level."),
      ex("Describe 5(x − 2)² without expanding.", ["The outer operation is multiplication by 5.", "The second factor is a square.", "The squared base is the grouped difference x − 2."], "Product of 5 and the square of x−2", "The description preserves nested structure."),
      ex("Find the numerator and denominator of (2x+1)/(3−x).", ["Treat the fraction bar as grouping.", "Everything above is the numerator.", "Everything below is the denominator."], "Numerator 2x+1; denominator 3−x", "The fraction bar has the grouping force of parentheses."),
    ],
    misconception: ["Terms are every piece separated by any operation sign.", "Term boundaries come from addition at the current grouping level; multiplication signs stay inside a term.", "Identify the outermost operation first, then move inward."],
    questions: [
      q("List the terms of 6x² − 4x + 9.", "6x², −4x, 9", "Interpret subtraction as adding −4x."),
      q("List the factors of −3xy.", "−3, x, y", "The term is a product of those factors."),
      q("State the coefficient of x in x − 5.", "1", "x means 1x."),
      q("State the coefficient of x² in −x² + 4.", "−1", "−x² means (−1)x²."),
      q("Name the outermost operation in 2(x+7).", "Multiplication", "The grouped sum is one factor multiplied by 2."),
      q("Name the outermost operation in 2x + 7.", "Addition", "The expression is a sum of 2x and 7."),
      q("Describe the structure of (a+b)/5.", "The sum a+b divided by 5", "The fraction bar groups the numerator."),
      q("Describe the structure of a + b/5.", "a plus the quotient b/5", "Only b is in the numerator of the quotient."),
      q("How many terms does 3(x+2) have before expansion at the outer level?", "One term", "The outermost structure is a product, not a sum."),
      q("How many terms does 3x + 6 have?", "Two", "The outer sum has addends 3x and 6."),
      q("Identify base and exponent in (x−4)³.", "Base x−4; exponent 3", "Parentheses make the whole difference the base."),
      q("A student calls 2 and x terms in 2x+3. Repair the language.", "2 and x are factors of the term 2x", "The terms are 2x and 3."),
      q("Draw or describe an expression tree for 4 − 2(x+1).", "Subtract product 2(x+1) from 4", "The root is subtraction; the right branch is a product containing a sum."),
      q("Identify numerator, denominator, and restriction in (x+5)/(2x).", "Numerator x+5; denominator 2x; x≠0", "The denominator cannot equal zero."),
      q("Rewrite 7 − 3x as an addition expression.", "7 + (−3x)", "Subtraction is addition of an opposite."),
      q("Explain why preserving structure matters when evaluating 2(x+3)².", "The sum must be completed before squaring and multiplying", "Flattening the grouping changes the value."),
    ],
    takeaway: ["Terms belong to sums; factors belong to products; coefficients are numerical factors.", "Read the outermost operation first and preserve every grouping boundary."],
  },
  "A1.4": {
    purpose: "Substitute equal values or expressions while protecting grouping, signs, and units.",
    prerequisites: ["Evaluate 3·5 − 2.", "Compute (−4)².", "Explain why parentheses can preserve a negative input."],
    exposition: [
      "Substitution replaces a symbol or subexpression with an equal-valued quantity. The replacement must occupy the same structural position as the original symbol, so parentheses are essential around negative numbers, fractions, and multi-term expressions.",
      "Evaluation is substitution followed by arithmetic. A clear evaluation line first shows the replacement, then simplifies in justified steps. Units should travel with measured quantities.",
      "Substitution may also replace one expression with an equivalent expression. If y = 2x + 1, then 3y − 4 becomes 3(2x+1) − 4. The parentheses preserve y as one complete object throughout the rewrite.",
    ],
    definitions: [
      ["substitution", "Replacement of a symbol or subexpression by an equal-valued quantity.", "The replacement must retain the original grouping role."],
      ["evaluate", "Find the numerical value of an expression for specified inputs.", "Show the substitution before arithmetic."],
      ["replacement expression", "The complete expression inserted for a symbol.", "Use parentheses when it contains more than one term or a leading sign."],
    ],
    examples: [
      ex("Evaluate 2x² − 3x + 1 at x = −2.", ["Write 2(−2)² − 3(−2) + 1.", "Evaluate the square and products.", "Add 8 + 6 + 1."], "15", "Parentheses ensure the negative input is squared."),
      ex("Evaluate A = 1/2bh for b = 7 cm and h = 4 cm.", ["Substitute values with units.", "Compute 1/2·7·4.", "Combine length units as square centimeters."], "14 cm²", "The result’s units match area."),
      ex("If y = 2x + 1, rewrite 3y − 4 in terms of x.", ["Replace y by the entire expression 2x+1.", "Write 3(2x+1) − 4.", "Distribute and combine constants."], "6x − 1", "The grouped replacement preserves equivalence."),
    ],
    misconception: ["When x = −3, x² becomes −3².", "The replacement for x is the complete number −3 and must be grouped: (−3)².", "Put parentheses around every substituted negative or multi-term expression."],
    questions: [
      q("Evaluate 5x − 7 at x = 4.", "13", "5·4 − 7 = 13."),
      q("Evaluate x² + 2x at x = −3.", "3", "(−3)² + 2(−3) = 9 − 6."),
      q("Evaluate 3a²b for a = −2 and b = 5.", "60", "3(−2)²(5) = 3·4·5."),
      q("Evaluate (m−n)/(m+n) for m=5, n=2.", "3/7", "Substitute into both grouped sums."),
      q("Evaluate C = 2πr for r = 3 cm.", "6π cm", "2π(3 cm) = 6π cm."),
      q("Evaluate d = rt for r = 55 mi/hr and t = 2.5 hr.", "137.5 miles", "Units cancel: (mi/hr)(hr) = mi."),
      q("If p = x−4, rewrite p²+3p in terms of x.", "(x−4)² + 3(x−4)", "Replace every p with the grouped expression x−4."),
      q("Simplify the previous expression.", "x² − 5x + 4", "Expand x²−8x+16 + 3x−12."),
      q("If y = 3x+2 and x=4, find y.", "14", "3·4 + 2 = 14."),
      q("If f(t)=t²−1, find f(1/2).", "−3/4", "(1/2)² − 1 = 1/4 − 1."),
      q("A student evaluates x² at x=−5 as −25. Repair the work.", "25", "Substitute (−5)², which equals 25."),
      q("Why is 4(2x+1) required when y=2x+1 is substituted into 4y?", "y is the entire expression 2x+1", "Parentheses keep both terms multiplied by 4."),
      q("Evaluate P=2l+2w for l=5.2 m, w=3.1 m.", "16.6 m", "2(5.2)+2(3.1)=10.4+6.2."),
      q("For g(x)=|x−3|, find g(−2).", "5", "|−2−3| = |−5| = 5."),
      q("If a=b/c, rewrite 2a+1 using b and c.", "2b/c + 1", "Replace a with b/c."),
      q("Evaluate 2(x+y)−xy for x=−1, y=4.", "10", "2(3) − (−4) = 6+4."),
    ],
    takeaway: ["Substitution replaces one complete mathematical object with an equal one.", "Use parentheses and carry units so the replacement preserves structure."],
  },
  "A1.5": {
    purpose: "Use grouping and precedence to read expressions unambiguously and enter them correctly in calculators.",
    prerequisites: ["Evaluate 6+2·3.", "Explain what (6+2) groups.", "Identify numerator and denominator in 8/2."],
    exposition: [
      "Order of operations is a reading convention for expressions without extra grouping. Grouping symbols override the default order and communicate which expression is one unit. Exponents apply to their complete bases before multiplication and addition.",
      "Multiplication and division share one precedence level and are processed left to right; addition and subtraction do the same. The mnemonic PEMDAS becomes misleading if it suggests multiplication always precedes division.",
      "Calculator syntax must preserve written grouping. A fraction such as (x+1)/(x−2) needs parentheses around both numerator and denominator when typed on one line. Spacing alone does not create a mathematical group.",
    ],
    definitions: [
      ["precedence", "The agreed priority used to parse an expression when grouping is not explicit.", "Operations at the same level are handled left to right."],
      ["grouping symbol", "Notation marking an expression as one unit, including parentheses, brackets, fraction bars, and radical bars.", "The entire grouped expression is evaluated together."],
      ["ambiguous input", "A typed expression that can be read in more than one way.", "Add parentheses rather than relying on visual spacing."],
    ],
    examples: [
      ex("Evaluate 18 ÷ 3·2.", ["Division and multiplication share precedence.", "Work left to right: 18 ÷ 3 = 6.", "Then compute 6·2."], "12", "It is not 18 ÷ 6."),
      ex("Compare 2+3²·4 and (2+3)²·4.", ["Evaluate exponent first in the ungrouped expression.", "Evaluate the grouped sum first in the second.", "Compare 38 and 100."], "38 and 100", "Grouping changes the structure and therefore the value."),
      ex("Type (5+1)/(8−2) unambiguously.", ["Group the numerator.", "Group the denominator.", "Place the division between the two groups."], "(5+1)/(8−2) = 1", "The typed form matches the fraction bar’s grouping."),
    ],
    misconception: ["Multiplication must always be done before division.", "They have equal precedence and are evaluated left to right.", "Mark operation levels or add grouping before computing."],
    questions: [
      q("Evaluate 7 + 3·4.", "19", "Multiply first, then add."),
      q("Evaluate (7+3)·4.", "40", "Grouping makes the sum one factor."),
      q("Evaluate 24÷6·2.", "8", "Work left to right: 24÷6=4, then 4·2."),
      q("Evaluate 24÷(6·2).", "2", "Compute the grouped product 12 first."),
      q("Evaluate 3² + 2³.", "17", "9 + 8 = 17."),
      q("Evaluate −4² and (−4)².", "−16 and 16", "Exponentiation precedes an ungrouped leading negative."),
      q("Evaluate 2[5−(3−7)].", "18", "Inner group 3−7=−4; then 5−(−4)=9."),
      q("Evaluate (18−6)/(2+1).", "4", "Numerator 12 divided by denominator 3."),
      q("Type the fraction x+3 over 2x−1 on one line.", "(x+3)/(2x−1)", "Both numerator and denominator require grouping."),
      q("Insert parentheses so 8−2·3 equals 18.", "(8−2)·3 = 18", "The grouped subtraction is multiplied by 3."),
      q("A student evaluates 20−8÷4 as 3. Repair the work.", "18", "Divide 8÷4=2 before subtracting."),
      q("Evaluate 5 + 12÷3².", "19/3", "Exponent first: 3²=9; then 12/9=4/3; add 5."),
      q("Explain the role of the radical bar in √(9+7).", "It groups 9+7 under the square root", "Compute the radicand 16 before taking the root."),
      q("Evaluate 6/2(1+2) using standard left-to-right convention.", "9", "Group gives 3; then 6÷2·3 = 3·3."),
      q("Rewrite a/b+c to mean a divided by the entire sum b+c.", "a/(b+c)", "Parentheses group the full denominator."),
      q("Evaluate {2+[3(4−1)]}².", "121", "Inner difference 3, product 9, sum 11, then square."),
    ],
    takeaway: ["Grouping determines structure; precedence only resolves ungrouped notation.", "Multiplication/division and addition/subtraction are each handled left to right."],
  },
  "A1.6": {
    purpose: "Use properties of real-number operations to justify efficient, equivalent rewrites.",
    prerequisites: ["Compute 7+0 and 7·1.", "Name the opposite of 5.", "Use an area model to explain 3(4+2)."],
    exposition: [
      "Properties describe transformations that preserve value. Commutative properties change order, associative properties change grouping, identities leave a value unchanged, and inverses combine to an identity.",
      "The distributive property links multiplication with addition: a(b+c)=ab+ac. It works in both directions, enabling expansion and factoring. Distribution applies to every term in the grouped sum.",
      "A written solution should name the property that licenses each non-arithmetic rewrite. This turns symbolic movement into a proof of equivalence rather than a pattern guess that happens to look familiar.",
    ],
    definitions: [
      ["commutative property", "Order may be reversed in addition or multiplication.", "Subtraction and division are not commutative."],
      ["associative property", "Grouping may change in repeated addition or multiplication.", "It does not change the order of terms or factors."],
      ["distributive property", "Multiplication by a sum equals the sum of the products.", "Every term inside the group receives the outside factor."],
    ],
    examples: [
      ex("Compute 25·17·4 efficiently.", ["Use commutativity to place 25 and 4 together.", "Use associativity to group (25·4)·17.", "Compute 100·17."], "1,700", "The properties change order and grouping without changing value."),
      ex("Expand −3(2x−5).", ["Distribute −3 to 2x.", "Distribute −3 to −5.", "Combine the resulting terms."], "−6x + 15", "The sign of the outside factor applies to both products."),
      ex("Factor 12x + 18.", ["Find GCF 6.", "Rewrite each term as a product containing 6.", "Reverse distribution."], "6(2x+3)", "Factoring exposes the common multiplicative structure."),
    ],
    misconception: ["Distribution applies only to the first term in parentheses.", "The grouped expression is a sum, so the outside factor multiplies every addend.", "Draw an area model or write one product for each inside term."],
    questions: [
      q("Name the property: 8+13 = 13+8.", "Commutative property of addition", "The addends change order."),
      q("Name the property: (2·5)·7 = 2·(5·7).", "Associative property of multiplication", "Only grouping changes."),
      q("Name the property: x+0=x.", "Additive identity", "Adding zero leaves a value unchanged."),
      q("Name the property: a·1=a.", "Multiplicative identity", "Multiplying by one leaves a value unchanged."),
      q("Name the property: y+(−y)=0.", "Additive inverse", "Opposites add to the additive identity."),
      q("State the multiplicative inverse of −3/5.", "−5/3", "Their product is 1."),
      q("Use properties to compute 48+37+52 efficiently.", "137", "Group 48+52=100, then add 37."),
      q("Use properties to compute 8·125·6.", "6,000", "Group 8·125=1000, then multiply by 6."),
      q("Expand 5(x+4).", "5x+20", "Distribute 5 to both terms."),
      q("Expand −2(3x−7).", "−6x+14", "Multiply −2 by 3x and by −7."),
      q("Expand 4(2x+3y−1).", "8x+12y−4", "Distribute 4 to all three terms."),
      q("Factor 15x+25.", "5(3x+5)", "Reverse distribution using GCF 5."),
      q("Factor −6x+18.", "−6(x−3)", "Taking out −6 leaves x−3."),
      q("Explain why a−b ≠ b−a in general.", "Subtraction is not commutative", "For example, 5−2=3 but 2−5=−3."),
      q("A student rewrites (a+b)² as a²+b² using distribution. Repair the claim.", "a²+2ab+b²", "(a+b)²=(a+b)(a+b), requiring two distributions."),
      q("Justify 7x+7y = 7(x+y).", "Distributive property in reverse", "Both terms share factor 7."),
    ],
    takeaway: ["Properties are licenses for value-preserving rewrites.", "Name the property, apply it to the complete structure, and check by reversing the rewrite."],
  },
  "A1.7": {
    purpose: "Recognize equivalent expressions and combine only terms with identical variable structure.",
    prerequisites: ["Identify coefficients in 3x and −5x.", "Use distribution on 2(x+4).", "Explain why 3 apples + 2 apples can combine."],
    exposition: [
      "Equivalent expressions have the same value for every allowed input. Numerical testing can disprove equivalence but cannot prove it for all inputs; properties provide a general proof across the full domain.",
      "Like terms have identical variable factors raised to identical powers. Their coefficients count copies of that shared unit, so 3x+5x=8x. Terms x and x² are not alike, just as meters and square meters are not alike.",
      "A reliable simplification sequence distributes first, identifies terms with signs attached, groups like structures, and combines coefficients. The result should be checked at one convenient input to catch arithmetic errors.",
    ],
    definitions: [
      ["equivalent expressions", "Expressions equal for every input in their common domain.", "A proof uses properties or a complete algebraic derivation."],
      ["like terms", "Terms with exactly the same variable part, including exponents.", "Only their numerical coefficients may differ."],
      ["constant term", "A term with no variable factor.", "It is like only other constant terms."],
    ],
    examples: [
      ex("Simplify 4x − 7 + 3x + 2.", ["Group x-terms and constants.", "Combine coefficients 4+3.", "Combine constants −7+2."], "7x−5", "The variable structure x is preserved."),
      ex("Simplify 3(2x−5) − 4(x+1).", ["Distribute to get 6x−15−4x−4.", "Combine x-terms.", "Combine constants."], "2x−19", "Distribution reveals the like terms."),
      ex("Decide whether 2(x+3)+x and 3x+6 are equivalent.", ["Distribute the first expression.", "Combine 2x+x.", "Compare with the second expression."], "Yes", "Both simplify to 3x+6 for every x."),
    ],
    misconception: ["Terms are like whenever they use the same letter.", "Exponents are part of variable structure; x and x² represent different units.", "Match the full variable part before adding coefficients."],
    questions: [
      q("Simplify 6x+2x.", "8x", "Add coefficients of like x terms."),
      q("Simplify 9a−4a+3.", "5a+3", "Combine only the a terms."),
      q("Simplify 5x²+3x−2x²+x.", "3x²+4x", "Combine x² terms separately from x terms."),
      q("Simplify 7−2y+5+y.", "12−y", "Constants combine to 12 and y coefficients to −1."),
      q("Simplify 4(2x+1)+3x.", "11x+4", "Distribute to 8x+4, then combine x terms."),
      q("Simplify −3(x−2)+5x.", "2x+6", "Distribute −3 to get −3x+6."),
      q("Simplify 2(x+4)−(x−1).", "x+9", "Distribute the implied −1 across x−1."),
      q("Are 4(x−2) and 4x−2 equivalent?", "No", "4(x−2)=4x−8."),
      q("Are 3x+3x² and 6x³ equivalent?", "No", "Unlike terms cannot be combined by adding exponents."),
      q("Prove 5(x+2)−2x and 3x+10 are equivalent.", "Both simplify to 3x+10", "Distribute and combine like terms."),
      q("Find k so 4x+kx = 11x.", "k=7", "Coefficients satisfy 4+k=11."),
      q("A student simplifies 2x+3 as 5x. Repair the work.", "It cannot be combined", "2x and 3 are unlike terms."),
      q("Simplify 1/2x + 3/4x.", "5/4x", "Add coefficients 1/2+3/4=5/4."),
      q("Simplify 0.3y−1.2+0.7y+2.", "y+0.8", "Combine y coefficients and constants."),
      q("Check 2x−19 and 3(2x−5)−4(x+1) at x=5.", "Both equal −9", "The check supports the algebraic simplification."),
      q("Explain why testing x=1 alone cannot prove equivalence.", "Different expressions can agree at one input", "Proof must cover every allowed input."),
    ],
    takeaway: ["Equivalent expressions agree for every allowed input.", "Combine coefficients only when the complete variable factors match."],
  },
  "A1.8": {
    purpose: "Read formulas as relationships among measured quantities and write substitutions and transformations so another reader can verify them.",
    prerequisites: ["State units for length and area.", "Substitute r=3 into 2πr.", "Solve a one-step multiplication fact such as 4x=20."],
    exposition: [
      "A formula is a reusable relationship among quantities. Every symbol should be declared with meaning and units. Dimensional consistency constrains sensible substitutions and catches many transcription errors.",
      "Using a formula requires more than inserting numbers: identify the target quantity, select the correct relationship, substitute with grouping and units, compute, and interpret the result. A numerical answer without a unit or context is incomplete when the inputs are measured.",
      "Rearranging a formula isolates a chosen quantity while preserving equality. The same equation may be useful in several solved forms, but restrictions such as nonzero divisors must be recorded.",
    ],
    definitions: [
      ["formula", "An equation expressing a reusable relationship among quantities.", "Every symbol and unit should be declared."],
      ["literal equation", "An equation containing several letters representing quantities.", "It may be rearranged to solve for one chosen quantity."],
      ["dimensional consistency", "Matching dimensions across equal or added quantities.", "It is a necessary check on a measurement formula."],
    ],
    examples: [
      ex("Use A=lw for l=8.5 cm and w=3 cm.", ["Declare l and w as lengths.", "Substitute A=(8.5 cm)(3 cm).", "Multiply values and units."], "25.5 cm²", "Length times length produces area."),
      ex("Use C=5/9(F−32) for F=95°F.", ["Group 95−32.", "Compute 63·5/9.", "Attach Celsius units and interpret."], "35°C", "The grouped subtraction is required by the formula."),
      ex("Solve d=rt for t and state the restriction.", ["Divide both sides by r.", "Write t=d/r.", "Record that r cannot be zero for this division."], "t=d/r, r≠0", "The rearranged form answers a different target question."),
    ],
    misconception: ["A correct number is complete even when units are omitted.", "Units communicate the quantity type and allow dimensional checking.", "Carry units through substitution and interpret the final measurement in words."],
    questions: [
      q("Use P=2l+2w for l=9 m, w=4 m.", "26 m", "2·9+2·4=26."),
      q("Use A=πr² for r=5 cm.", "25π cm²", "Substitute and square the radius including its unit."),
      q("Use I=Prt for P=$800, r=0.04/year, t=3 years.", "$96", "800·0.04·3=96; time units cancel the rate denominator."),
      q("Use v=d/t for d=150 km, t=2.5 h.", "60 km/h", "150÷2.5=60."),
      q("Solve A=bh for h.", "h=A/b, b≠0", "Divide both sides by b."),
      q("Solve P=2l+2w for w.", "w=(P−2l)/2", "Subtract 2l, then divide by 2."),
      q("Solve C=5/9(F−32) for F.", "F=9C/5+32", "Multiply by 9/5, then add 32."),
      q("Check whether area = 2l+2w is dimensionally plausible.", "No", "The right side has length units, not square units."),
      q("Write a quantity dictionary for d=rt.", "d distance, r distance/time, t time", "The unit product rt is distance."),
      q("A student substitutes x=−3 into x² as −3². Repair the written line.", "(−3)²=9", "Parentheses show the complete substituted value."),
      q("Which formula fits constant-speed travel: d=rt or d=r+t?", "d=rt", "Rate times time has distance units."),
      q("Use V=lwh for 2.5 m, 1.2 m, and 0.8 m.", "2.4 m³", "Multiply dimensions and cube the length unit."),
      q("Explain why a formula may have several useful solved forms.", "Different problems target different quantities", "Equivalent rearrangements isolate the needed variable."),
      q("Write the density formula if density is mass per volume.", "ρ=m/V", "The phrase 'per' indicates division."),
      q("Solve ρ=m/V for m.", "m=ρV", "Multiply both sides by V."),
      q("Present a complete solution using A=1/2bh for b=12 ft, h=7 ft.", "A=42 ft²", "A=1/2(12 ft)(7 ft)=42 ft²; the triangle’s area is 42 square feet."),
    ],
    takeaway: ["A formula is a relationship among named quantities, not a slot machine for numbers.", "Declare symbols, preserve grouping, carry units, and state restrictions when rearranging."],
  },
};
