const ex = (prompt, steps, answer, interpretation) => ({ prompt, steps, answer, interpretation });
const q = (prompt, answer, solution) => ({ prompt, answer, solution });

export const A2_PROFILES = {
  "A2.1": {
    purpose: "Interpret a solution as a value that makes an equation true, represent solution sets, and verify candidates by substitution.",
    prerequisites: [
      "Evaluate 3x + 2 when x = 4.",
      "Explain the difference between an expression and an equation.",
      "Decide whether 7 = 7 is true.",
    ],
    exposition: [
      "An equation asserts that two expressions have the same value. A solution is a value in the stated domain that makes that assertion true. Solving is therefore not a ritual for moving symbols; it is the process of finding every value that survives substitution into the original equation.",
      "A solution set records all solutions. It may contain one value, several values, every value in a domain, or no values at all. The braces in {5} describe a set containing 5; they are not grouping symbols in a calculation. An empty solution set is written ∅.",
      "Checking closes the reasoning loop. Substitute a candidate into the original equation, simplify each side independently, and compare the results. A check can reject an arithmetic error and can also reveal a domain problem, such as a value that makes a denominator zero.",
    ],
    definitions: [
      ["solution", "A value that makes an equation true when substituted for its variable.", "It must belong to the stated domain."],
      ["solution set", "The set containing every solution of an equation.", "It may be empty, finite, or all values in a domain."],
      ["identity", "An equation true for every value in its domain.", "Its solution set is the entire stated domain."],
    ],
    examples: [
      ex("Is x = 4 a solution of 3x − 5 = 7?", ["Substitute 4 for x in the original equation.", "Compute 3(4) − 5 = 12 − 5.", "Compare 7 with the right side, 7."], "Yes; 7 = 7", "A true substituted statement confirms the candidate."),
      ex("Test x = −2 in x² + x = 2.", ["Use parentheses: (−2)² + (−2).", "Simplify to 4 − 2.", "Compare the result with 2."], "Yes; 2 = 2", "Parentheses preserve the sign of a substituted value."),
      ex("Describe the solution set of x + 0 = x over the real numbers.", ["Recognize that adding zero leaves every real number unchanged.", "Substitute several values as a check.", "State the complete set, not one example."], "All real numbers", "The equation is an identity over the real numbers."),
    ],
    misconception: ["A value reached at the end of algebra must be a solution.", "An arithmetic slip or an invalid operation can produce a candidate that fails the original equation.", "Substitute every candidate into the original equation and compare both sides."],
    questions: [
      q("Is x = 5 a solution of 2x + 1 = 11?", "Yes", "Substitution gives 2(5)+1=11, the same as the right side."),
      q("Is x = −3 a solution of 4 − x = 1?", "No", "Substitution gives 4−(−3)=7, not 1."),
      q("Test x = 0 in 7x = 0.", "Yes", "7(0)=0, so the equation is true."),
      q("Test x = 1/2 in 6x − 1 = 2.", "Yes", "6(1/2)−1=3−1=2."),
      q("Which of {−2, 0, 2} solve x² = 4?", "−2 and 2", "Both (−2)² and 2² equal 4; 0² does not."),
      q("Write the solution set if the only solution is x = −7.", "{−7}", "A one-element solution set is written with braces."),
      q("Write the solution set of x + 3 = x + 4.", "∅", "Subtracting x would require 3=4, which is false."),
      q("Describe the solution set of 5(x + 1) = 5x + 5.", "All real numbers", "Distributing makes both sides 5x+5 for every real x."),
      q("A candidate produces 9 = 9 after substitution. What does that establish?", "The candidate is a solution", "Equal simplified sides make the original equation true for that value."),
      q("A candidate produces −2 = 6. What does that establish?", "The candidate is not a solution", "The substituted equation is false."),
      q("Check x = −4 in 2(x − 1) = −10.", "Yes", "2(−4−1)=2(−5)=−10."),
      q("Check x = 3 in (x + 1)/2 = 2.", "Yes", "(3+1)/2=4/2=2."),
      q("Why should a negative substituted value be parenthesized?", "To keep its sign attached to the value", "Parentheses prevent expressions such as x² from becoming the different expression −3²."),
      q("Can an equation have more than one solution?", "Yes", "For example, x²=1 has solutions −1 and 1."),
      q("Can a linear equation have every real number as a solution?", "Yes", "An identity such as 2(x+1)=2x+2 is true for every real x."),
      q("Explain a complete check for x = 6 in 3x − 8 = 10.", "3(6)−8=18−8=10, so x=6 is a solution", "Substitute into the original equation, simplify, and explicitly compare with the right side."),
    ],
    takeaway: ["A solution makes the original equation true.", "Record the complete solution set and verify candidates by substituting into the original equation."],
  },
  "A2.2": {
    purpose: "Solve addition and subtraction equations by preserving equality with inverse operations.",
    prerequisites: [
      "Name the additive inverse of −8.",
      "Evaluate −5 + 12.",
      "Explain why adding the same amount to equal quantities preserves equality.",
    ],
    exposition: [
      "An equation behaves like a balanced scale: changing only one side destroys the equality, while performing the same valid operation on both sides preserves it. For x + 7 = 19, subtracting 7 from both sides isolates x without changing the solution set.",
      "Subtraction equations deserve careful reading. In x − 5 = 9, add 5 to both sides. In 5 − x = 9, the variable is being subtracted, so adding x first or reasoning from the missing subtrahend avoids a sign trap. Written equality steps should show the same operation on both sides.",
      "The final value is a candidate until it is checked. Substitute into the original equation, not merely the last transformed line. A one-step equation may be quick, but the habits of balance, explanation, and verification scale to every later equation.",
    ],
    definitions: [
      ["inverse operations", "Operations that undo one another, such as addition and subtraction.", "Apply the inverse to both sides of an equation."],
      ["equivalent equations", "Equations with the same solution set.", "Adding or subtracting the same quantity on both sides produces an equivalent equation."],
      ["isolate", "Rewrite an equation so the target variable stands alone.", "Isolation must be achieved through equality-preserving operations."],
    ],
    examples: [
      ex("Solve x + 14 = 31.", ["Subtract 14 from both sides.", "Simplify x = 17.", "Check 17 + 14 = 31."], "x = 17", "The inverse of adding 14 is subtracting 14."),
      ex("Solve x − 8 = −3.", ["Add 8 to both sides.", "Simplify x = 5.", "Check 5 − 8 = −3."], "x = 5", "The solution may have a different sign than either visible constant."),
      ex("Solve 6 − x = 10.", ["Subtract 6 from both sides to get −x = 4.", "Multiply both sides by −1.", "Check 6 − (−4) = 10."], "x = −4", "A variable after a minus sign has coefficient −1."),
    ],
    misconception: ["Moving a term across the equals sign automatically changes its sign.", "Terms do not move; an unrecorded sign change hides the operation and invites errors.", "Write the same addition or subtraction on both sides, then simplify."],
    questions: [
      q("Solve x + 9 = 22.", "x = 13", "Subtract 9 from both sides: x=22−9=13."),
      q("Solve x − 11 = 4.", "x = 15", "Add 11 to both sides: x=4+11=15."),
      q("Solve x + 6 = −2.", "x = −8", "Subtract 6 from both sides."),
      q("Solve x − 7 = −12.", "x = −5", "Add 7 to both sides."),
      q("Solve x + (−5) = 3.", "x = 8", "Add 5 to both sides."),
      q("Solve x − (−4) = 10.", "x = 6", "Rewrite as x+4=10, then subtract 4."),
      q("Solve y + 2.7 = 8.1.", "y = 5.4", "Subtract 2.7 from both sides."),
      q("Solve t − 3/4 = 5/4.", "t = 2", "Add 3/4: t=8/4=2."),
      q("Solve 12 − x = 5.", "x = 7", "Subtract 12 to get −x=−7, then multiply by −1."),
      q("Solve −3 − x = 8.", "x = −11", "Add 3 to get −x=11, then multiply by −1."),
      q("Write an equation for 'a number increased by 6 is 20' and solve.", "x + 6 = 20; x = 14", "Translate increased by as addition, then subtract 6."),
      q("Write an equation for '9 less than a number is −1' and solve.", "x − 9 = −1; x = 8", "The number comes first in x−9; add 9."),
      q("A student changes x+4=10 to x=10+4. Identify and repair the error.", "x = 10 − 4 = 6", "Undo +4 by subtracting 4 from both sides."),
      q("Solve x + a = b for x.", "x = b − a", "Subtract a from both sides."),
      q("Check x = −6 in x − 2 = −8.", "Yes", "−6−2=−8."),
      q("Solve and verify 4 − x = −9.", "x = 13", "Subtract 4: −x=−13, so x=13; 4−13=−9."),
    ],
    takeaway: ["Preserve equality by applying the same inverse operation to both sides.", "Treat subtraction of the variable as a coefficient of −1 and always check the original equation."],
  },
  "A2.3": {
    purpose: "Solve multiplication and division equations using reciprocal operations, with attention to zero restrictions.",
    prerequisites: [
      "Find the reciprocal of 3/5.",
      "Evaluate −4 · 6.",
      "Explain why division by zero is not defined.",
    ],
    exposition: [
      "In a multiplication equation such as 7x = 42, the coefficient 7 tells how x is scaled. Dividing both sides by the nonzero coefficient reverses that scaling and preserves equality. Writing x = 42/7 makes the inverse operation visible.",
      "A division equation such as x/5 = 8 can be read as one fifth of x equals 8. Multiplying both sides by 5 clears the division. Fractions are handled the same way: multiplying by the reciprocal of a nonzero coefficient isolates the variable.",
      "Zero is a structural boundary. Dividing by a coefficient is valid only when that coefficient is not zero. The equation 0x = 5 has no solution, while 0x = 0 is true for every x; neither can be handled by dividing by zero.",
    ],
    definitions: [
      ["coefficient", "The numerical factor multiplying a variable.", "A nonzero coefficient can be undone by division."],
      ["reciprocal", "A number that multiplies with a nonzero number to produce 1.", "Zero has no reciprocal."],
      ["zero-product boundary", "The special behavior created when a variable's coefficient is zero.", "Check the resulting statement instead of dividing by zero."],
    ],
    examples: [
      ex("Solve −6x = 27.", ["Divide both sides by −6.", "Simplify x = 27/(−6) = −9/2.", "Check −6(−9/2) = 27."], "x = −9/2", "A negative coefficient reverses the sign of the quotient."),
      ex("Solve x/−4 = 7.", ["Multiply both sides by −4.", "Simplify x = −28.", "Check (−28)/(−4) = 7."], "x = −28", "Multiplication by the denominator clears division."),
      ex("Solve (3/5)x = 12.", ["Multiply both sides by the reciprocal 5/3.", "Cancel (5/3)(3/5) to 1.", "Simplify 12·5/3."], "x = 20", "A reciprocal undoes a nonzero fractional coefficient."),
    ],
    misconception: ["Dividing both sides by the visible coefficient always works.", "A coefficient may be zero, and division by zero is not defined.", "Confirm the divisor is nonzero; if it is zero, analyze the resulting constant statement."],
    questions: [
      q("Solve 8x = 56.", "x = 7", "Divide both sides by 8."),
      q("Solve −5x = 35.", "x = −7", "Divide by −5."),
      q("Solve 12x = −9.", "x = −3/4", "Divide by 12 and simplify −9/12."),
      q("Solve 0.4x = 3.2.", "x = 8", "Divide 3.2 by 0.4."),
      q("Solve x/6 = 9.", "x = 54", "Multiply both sides by 6."),
      q("Solve x/−7 = −3.", "x = 21", "Multiply both sides by −7."),
      q("Solve x/2.5 = 4.", "x = 10", "Multiply by 2.5."),
      q("Solve x/(3/4) = 8.", "x = 6", "Multiply by 3/4: x=8·3/4."),
      q("Solve (2/3)x = 14.", "x = 21", "Multiply by 3/2."),
      q("Solve (−5/8)x = 15.", "x = −24", "Multiply by −8/5."),
      q("Solve ax = b for x when a ≠ 0.", "x = b/a", "Divide both sides by the nonzero coefficient a."),
      q("Analyze 0x = 6.", "No solution", "The left side is always 0, so the equation would require 0=6."),
      q("Analyze 0x = 0.", "All real numbers", "Every real x makes 0x=0 true."),
      q("A student solves −4x=20 as x=5. Repair the sign.", "x = −5", "20÷(−4)=−5."),
      q("Check x = 18 in x/3 = 6.", "Yes", "18/3=6."),
      q("Solve and verify (7/4)x = −21.", "x = −12", "Multiply by 4/7: x=−12; then (7/4)(−12)=−21."),
    ],
    takeaway: ["Undo a nonzero coefficient by division or multiplication by its reciprocal.", "Never divide by zero; analyze zero-coefficient equations as true or false statements."],
  },
  "A2.4": {
    purpose: "Simplify each side of an equation correctly before choosing operations that isolate the variable.",
    prerequisites: [
      "Combine 3x + 5x.",
      "Distribute 4(x − 2).",
      "Evaluate 12 − 7.",
    ],
    exposition: [
      "Equations often contain removable clutter: like terms, numerical arithmetic, or distributive products on the same side. Simplifying each side first exposes the equation's structure and reduces the number of balance operations required.",
      "Only like terms combine. A term containing x cannot combine with a constant, and x cannot combine with x². Distribution must reach every term inside the grouping symbol, including negative signs. These expression rules happen within a side; equality operations happen to both sides.",
      "After simplifying, solve the resulting equation and check against the original unsimplified form. That final check is especially valuable because it tests both the simplification and the solving steps.",
    ],
    definitions: [
      ["like terms", "Terms with identical variable parts and exponents.", "Only their coefficients are combined."],
      ["distribution", "Multiplying a factor by every term in a grouped sum or difference.", "The sign and factor apply to each term."],
      ["simplify", "Rewrite an expression in an equivalent, more useful form.", "Simplifying one side does not require the same rewrite on the other side."],
    ],
    examples: [
      ex("Solve 4x + 3x − 5 = 30.", ["Combine 4x+3x to get 7x.", "Add 5 to both sides.", "Divide by 7 and check."], "x = 5", "Combining like terms reveals a two-step equation."),
      ex("Solve 3(x + 4) = 27.", ["Distribute to get 3x+12=27, or divide by 3 first.", "Isolate x.", "Check 3(5+4)=27."], "x = 5", "More than one efficient first step can preserve equivalence."),
      ex("Solve 2(x − 3) + 4 = 12.", ["Distribute: 2x−6+4=12.", "Combine constants: 2x−2=12.", "Add 2 and divide by 2."], "x = 7", "Simplification separates expression work from balance work."),
    ],
    misconception: ["Whatever is done within one side must also be done to the other side.", "Replacing an expression with an equivalent expression does not change that side's value.", "Distinguish simplifying a side from applying an operation to both sides."],
    questions: [
      q("Solve 2x + 5x = 28.", "x = 4", "Combine to 7x=28, then divide by 7."),
      q("Solve 9x − 4x + 6 = 31.", "x = 5", "Combine to 5x+6=31, subtract 6, and divide by 5."),
      q("Solve 4(x + 2) = 32.", "x = 6", "Divide by 4 or distribute; x+2=8."),
      q("Solve −3(x − 5) = 6.", "x = 3", "Divide by −3: x−5=−2, then add 5."),
      q("Solve 5(x + 1) − 2 = 18.", "x = 3", "Distribute and combine: 5x+3=18."),
      q("Solve 2(x − 4) + 3x = 17.", "x = 5", "Simplify to 5x−8=17."),
      q("Solve 7 + 3(x − 1) = 19.", "x = 5", "Simplify to 3x+4=19."),
      q("Solve 4x + 2 − x + 7 = 24.", "x = 5", "Combine to 3x+9=24."),
      q("Solve 6(2x − 1) − 12x = −6.", "All real numbers", "Distribution gives 12x−6−12x=−6, or −6=−6."),
      q("Solve 2(x + 3) + 2x = 18.", "x = 3", "Simplify to 4x+6=18."),
      q("A student rewrites −2(x−4) as −2x−8. Repair it.", "−2x + 8", "The factor −2 multiplies both x and −4."),
      q("Which terms combine in 3x + 2 + 5x² − x?", "3x and −x", "They have the same variable part x; 5x² and 2 are different term types."),
      q("Simplify, then solve: 8 − 2x + 5 = 21.", "x = −4", "Combine constants: 13−2x=21; subtract 13 and divide by −2."),
      q("Solve 3(2x + 1) + 4 = 25.", "x = 3", "Simplify to 6x+7=25."),
      q("Why check in the original equation after simplifying?", "It tests both simplification and solving", "A check only in the simplified line may miss an earlier distribution error."),
      q("Solve and verify 2(3x − 5) + 4x = 40.", "x = 5", "Simplify to 10x−10=40, so x=5; substitution gives 40."),
    ],
    takeaway: ["Simplify within each side before applying balance operations.", "Combine only like terms, distribute to every term, and verify in the original equation."],
  },
  "A2.5": {
    purpose: "Solve multistep linear equations with a clear sequence of simplification, balance operations, and verification.",
    prerequisites: [
      "Solve 4x = 20.",
      "Solve x + 7 = 12.",
      "Distribute 3(x − 2).",
    ],
    exposition: [
      "A multistep equation is a sequence of reversible decisions. First simplify each side, then move variable terms and constants using equality-preserving operations, and finally undo the remaining coefficient. The most useful next step is the one that makes the structure simpler.",
      "There is no law requiring constants to move before variable terms. Good strategy minimizes fractions, negative coefficients, and unnecessary lines. Each written line should be an equation equivalent to the line above, with the operation visible enough to audit.",
      "A solution statement is not complete without verification. Substitute the value into the original equation, simplify both sides independently, and state that they match. If they do not, trace the first line where equivalence was lost.",
    ],
    definitions: [
      ["balance operation", "An operation performed on both sides to preserve equality.", "Its inverse must be valid in the chosen number system."],
      ["equivalent step", "A transformation that preserves exactly the same solution set.", "Each solving line should be justified by simplification or a balance operation."],
      ["verification", "Substitution of a candidate into the original equation.", "Both sides must simplify to the same value."],
    ],
    examples: [
      ex("Solve 5x − 7 = 28.", ["Add 7 to both sides.", "Divide 35 by 5.", "Check 5(7)−7=28."], "x = 7", "Undo addition before undoing multiplication."),
      ex("Solve 4 − 3x = 19.", ["Subtract 4 from both sides.", "Divide −3x=15 by −3.", "Check 4−3(−5)=19."], "x = −5", "The negative coefficient must be preserved."),
      ex("Solve 2(3x − 1) + 5 = 27.", ["Distribute and combine to get 6x+3=27.", "Subtract 3.", "Divide by 6 and check."], "x = 4", "Simplification turns a nested equation into a familiar form."),
    ],
    misconception: ["Every multistep equation must be solved with the same fixed order.", "Different valid first moves may be more efficient depending on the structure.", "Choose reversible steps that simplify the equation, and justify each line."],
    questions: [
      q("Solve 3x + 8 = 26.", "x = 6", "Subtract 8, then divide 18 by 3."),
      q("Solve 7x − 9 = 40.", "x = 7", "Add 9, then divide by 7."),
      q("Solve 12 − 2x = 24.", "x = −6", "Subtract 12, then divide 12 by −2."),
      q("Solve −4x + 5 = 29.", "x = −6", "Subtract 5, then divide 24 by −4."),
      q("Solve 5(x − 2) = 35.", "x = 9", "Divide by 5, then add 2."),
      q("Solve 3(x + 4) − 2 = 25.", "x = 5", "Simplify to 3x+10=25."),
      q("Solve 2(4x − 3) + 1 = 35.", "x = 5", "Simplify to 8x−5=35."),
      q("Solve 18 = 6 − 3(x + 2).", "x = −6", "Simplify right side to −3x; then 18=−3x."),
      q("Solve 4x/3 + 2 = 10.", "x = 6", "Subtract 2, then multiply 8 by 3/4."),
      q("Solve 0.5x − 1.2 = 3.8.", "x = 10", "Add 1.2, then divide 5 by 0.5."),
      q("A student divides 2x+6=18 by 2 and writes x+6=9. Repair the line.", "x + 3 = 9", "Every term on the left must be divided by 2."),
      q("Which first step is efficient for 9(x−4)=45?", "Divide both sides by 9", "This immediately gives x−4=5 without distribution."),
      q("Solve 6 − (x + 2) = 11.", "x = −7", "Simplify to 4−x=11, then −x=7."),
      q("Solve 3 − 2(5 − x) = 9.", "x = 8", "Simplify to 2x−7=9."),
      q("Check x = 4 in 2(3x−1)+5=27.", "Yes", "2(12−1)+5=22+5=27."),
      q("Solve and verify 7 − 3(2x + 1) = −20.", "x = 4", "Simplify to 4−6x=−20, so x=4; substitution returns −20."),
    ],
    takeaway: ["Simplify, choose efficient balance operations, and undo the remaining coefficient.", "Every line should preserve the solution set, and the final value must pass the original equation."],
  },
  "A2.6": {
    purpose: "Solve linear equations with fractions and decimals by choosing exact, efficient ways to clear denominators or decimal places.",
    prerequisites: [
      "Find the least common multiple of 4 and 6.",
      "Multiply 0.35 by 100.",
      "Add 2/3 and 1/6.",
    ],
    exposition: [
      "Fractions and decimals do not change the logic of solving; they change which first step is efficient. Multiplying every term on both sides by the least common denominator clears fractions while preserving equality. The multiplier must reach every term, not only the terms with denominators.",
      "Terminating decimals can be cleared by multiplying both sides by a suitable power of ten. This is an equality operation, not a decimal-point shortcut. Exact fraction arithmetic is often preferable to early rounding because rounding can change a solution.",
      "After clearing the notation, solve the resulting integer-coefficient equation and check in the original form. When measurements are approximate, distinguish an exact algebraic result from a deliberately rounded reported value.",
    ],
    definitions: [
      ["least common denominator", "The least positive number divisible by every denominator in an equation.", "Multiplying every term by it clears all listed fractions."],
      ["clearing decimals", "Multiplying both sides by a power of ten to obtain integer coefficients.", "Every term on both sides must receive the same factor."],
      ["exact value", "A value represented without approximation, often as a fraction.", "Round only when the context requests an approximation."],
    ],
    examples: [
      ex("Solve x/3 + 1/4 = 5/6.", ["Use LCD 12 and multiply every term by 12.", "Obtain 4x+3=10.", "Solve 4x=7 and check."], "x = 7/4", "Clearing denominators produces an equivalent integer equation."),
      ex("Solve 0.3x − 1.2 = 2.4.", ["Multiply every term by 10.", "Solve 3x−12=24.", "Check 0.3(12)−1.2=2.4."], "x = 12", "A power of ten can remove terminating decimals cleanly."),
      ex("Solve (2x−1)/5 = (x+4)/3.", ["Multiply both sides by 15.", "Obtain 3(2x−1)=5(x+4).", "Expand, solve, and verify."], "x = 23", "The LCD clears both compound numerators without cross-multiplication ambiguity."),
    ],
    misconception: ["Multiplying by the LCD only affects fraction terms.", "An equality operation must apply to every term on both sides.", "Use grouping or annotate the multiplier across the full equation before simplifying."],
    questions: [
      q("Solve x/4 = 7.", "x = 28", "Multiply both sides by 4."),
      q("Solve x/5 + 2 = 8.", "x = 30", "Subtract 2, then multiply by 5."),
      q("Solve x/3 − 1/2 = 5/6.", "x = 4", "Multiply every term by 6: 2x−3=5."),
      q("Solve x/4 + x/6 = 5.", "x = 12", "Multiply by 12: 3x+2x=60."),
      q("Solve (x−2)/3 = 5.", "x = 17", "Multiply by 3, then add 2."),
      q("Solve (2x+1)/4 = 3/2.", "x = 5/2", "Multiply by 4: 2x+1=6."),
      q("Solve 0.6x = 4.2.", "x = 7", "Multiply by 10 to get 6x=42."),
      q("Solve 0.25x + 1.5 = 3.", "x = 6", "Multiply by 100 or subtract 1.5 and divide by 0.25."),
      q("Solve 1.2x − 0.4 = 2.0.", "x = 2", "Multiply by 10: 12x−4=20."),
      q("Solve 0.03x + 0.12 = 0.30.", "x = 6", "Multiply by 100: 3x+12=30."),
      q("What multiplier clears denominators in x/6 + 1/8 = 1/3?", "24", "The least common multiple of 6, 8, and 3 is 24."),
      q("After multiplying x/3 + 2 = 5/6 by 6, write the correct equation.", "2x + 12 = 5", "The factor 6 multiplies every term."),
      q("A student rounds 2/3 to 0.67 before solving. Why is that risky?", "It changes the equation slightly", "Use the exact fraction until a context calls for a rounded report."),
      q("Solve (x+1)/2 − (x−1)/3 = 4.", "x = 19", "Multiply by 6: 3(x+1)−2(x−1)=24, so x+5=24."),
      q("Check x = 12 in 0.3x−1.2=2.4.", "Yes", "3.6−1.2=2.4."),
      q("Solve and verify (3x−2)/4 = (x+6)/2.", "x = 14", "Multiply by 4: 3x−2=2x+12, so x=14; both original sides equal 10."),
    ],
    takeaway: ["Clear fractions or decimals by multiplying every term on both sides by one useful factor.", "Keep exact values through the algebra and verify in the original equation."],
  },
  "A2.7": {
    purpose: "Solve linear equations with variables on both sides by collecting variable terms strategically and preserving signs.",
    prerequisites: [
      "Combine 7x − 3x.",
      "Solve 4x = 20.",
      "Subtract 2x from both sides of a simple equation.",
    ],
    exposition: [
      "When x appears on both sides, use the addition or subtraction property of equality to collect variable terms on one side. Subtracting the smaller variable term often keeps the remaining coefficient positive, but either direction is valid when signs are handled correctly.",
      "After collecting variable terms, collect constants on the other side and divide by the remaining coefficient. The equals sign should stay aligned conceptually: each new line describes the same solution set, not a collection of terms drifting across a boundary.",
      "Some equations collapse after collection. A true constant statement signals infinitely many solutions; a false constant statement signals no solution. Do not force a numerical value when the variable disappears.",
    ],
    definitions: [
      ["collect variable terms", "Use balance operations to place variable terms on one side.", "Subtract or add the same variable expression on both sides."],
      ["constant statement", "An equation containing no variables after simplification.", "Its truth determines whether the solution set is all values or empty."],
      ["strategic side", "The side chosen to hold the remaining variable term.", "Choosing it can reduce negative coefficients but does not change the solution."],
    ],
    examples: [
      ex("Solve 7x + 2 = 4x + 20.", ["Subtract 4x from both sides.", "Solve 3x+2=20.", "Check x=6 in both original sides."], "x = 6", "Collecting the smaller variable term keeps a positive coefficient."),
      ex("Solve 5 − 2x = 3x − 15.", ["Add 2x to both sides.", "Add 15 to both sides.", "Solve 20=5x and check."], "x = 4", "Variable terms and constants are collected with separate balance operations."),
      ex("Solve 3(x + 2) = 2x + 11.", ["Distribute to get 3x+6=2x+11.", "Subtract 2x.", "Subtract 6 and check."], "x = 5", "Simplify before collecting variable terms."),
    ],
    misconception: ["A variable term can cross the equals sign by changing sign without explanation.", "This hides the equality operation and makes sign errors hard to detect.", "Write the same addition or subtraction of the variable term on both sides."],
    questions: [
      q("Solve 5x + 3 = 2x + 18.", "x = 5", "Subtract 2x, subtract 3, then divide by 3."),
      q("Solve 9x − 4 = 7x + 10.", "x = 7", "Subtract 7x and add 4."),
      q("Solve 4x + 12 = 6x − 2.", "x = 7", "Subtract 4x, then add 2: 14=2x."),
      q("Solve 8 − 3x = x − 12.", "x = 5", "Add 3x and add 12: 20=4x."),
      q("Solve 2x − 9 = 5 − 5x.", "x = 2", "Add 5x and add 9: 7x=14."),
      q("Solve −4x + 7 = −x − 8.", "x = 5", "Add 4x and add 8: 15=3x."),
      q("Solve 3(x + 1) = 2x + 9.", "x = 6", "Distribute, then subtract 2x and 3."),
      q("Solve 4(2x − 1) = 5x + 17.", "x = 7", "Simplify to 8x−4=5x+17."),
      q("Solve 2(x − 5) + x = 5x − 18.", "x = 4", "Simplify to 3x−10=5x−18; collect terms."),
      q("Solve 0.5x + 4 = 0.2x + 10.", "x = 20", "Subtract 0.2x and 4: 0.3x=6."),
      q("Which subtraction keeps a positive coefficient in 7x+1=3x+9?", "Subtract 3x from both sides", "This leaves 4x on the left."),
      q("A student changes 4x+2=7x−10 to 4x−7x=−10−2. Is the line equivalent?", "Yes", "It represents subtracting 7x and 2 from both sides, though showing the operations is clearer."),
      q("Solve ax + b = cx + d when a ≠ c.", "x = (d−b)/(a−c)", "Subtract cx and b, then divide by a−c."),
      q("Check x = 7 in 4x+12=6x−2.", "Yes", "Both sides equal 40."),
      q("Solve 6x + 2 = 6x + 2.", "All real numbers", "Subtracting 6x gives the true statement 2=2."),
      q("Solve and verify 5(x−1)+2x = 3(x+7)−2.", "x = 6", "Simplify to 7x−5=3x+19, so 4x=24; both original sides equal 37."),
    ],
    takeaway: ["Collect variable terms with explicit balance operations, then collect constants.", "If the variable disappears, classify the resulting constant statement instead of inventing a value."],
  },
  "A2.8": {
    purpose: "Classify linear equations as having one solution, no solution, or infinitely many solutions by interpreting the simplified statement.",
    prerequisites: [
      "Distribute 2(x + 3).",
      "Combine like terms on each side of an equation.",
      "Decide whether 5 = 5 and 5 = 8 are true.",
    ],
    exposition: [
      "A linear equation in one variable can finish in three fundamentally different ways. If it simplifies to x = a, it has one solution. If the variable cancels and leaves a false statement such as 4 = 9, it has no solution. If it leaves a true statement such as 4 = 4, every value in the domain is a solution.",
      "These outcomes reflect relationships between two linear expressions. Different slopes meet once; equal slopes with different intercepts never meet; identical expressions agree everywhere. The symbolic result and the graph tell the same story.",
      "The correct response is a solution-set classification, not a forced number. Show enough simplification to reveal the constant statement, state whether it is true or false, and then name the corresponding solution set.",
    ],
    definitions: [
      ["one solution", "Exactly one value makes the equation true.", "The equation reduces to x=a with a nonzero coefficient before division."],
      ["no solution", "No value in the domain makes the equation true.", "The equation reduces to a false constant statement."],
      ["infinitely many solutions", "Every value in the stated domain makes the equation true.", "The equation reduces to a true constant statement."],
    ],
    examples: [
      ex("Classify 3x + 4 = x + 12.", ["Subtract x and 4.", "Obtain 2x=8, then x=4.", "State the solution set {4}."], "One solution: x = 4", "Different variable coefficients lead to one intersection."),
      ex("Classify 2(x + 3) = 2x + 9.", ["Distribute to get 2x+6=2x+9.", "Subtract 2x to get 6=9.", "Recognize the false statement."], "No solution", "Parallel linear expressions never have equal outputs."),
      ex("Classify 5(x − 2) + 3 = 5x − 7.", ["Distribute and combine the left side to 5x−7.", "Subtract 5x to obtain −7=−7.", "Recognize the true statement."], "Infinitely many solutions", "Both sides are the same expression."),
    ],
    misconception: ["If the variable cancels, the answer is always no solution.", "Cancellation can leave either a true or a false statement.", "Evaluate the remaining statement: true means all values; false means none."],
    questions: [
      q("Classify 4x + 1 = 13.", "One solution", "It reduces to x=3."),
      q("Classify 2x + 5 = 2x + 8.", "No solution", "Subtracting 2x leaves the false statement 5=8."),
      q("Classify 7x − 4 = 7x − 4.", "Infinitely many solutions", "Subtracting 7x leaves the true statement −4=−4."),
      q("Classify 3(x+2)=3x+6.", "Infinitely many solutions", "Distribution makes both sides identical."),
      q("Classify 5(x−1)=5x+2.", "No solution", "Distribution gives 5x−5=5x+2, so −5=2."),
      q("Classify 4(x+1)=2x+10.", "One solution", "It simplifies to 4x+4=2x+10, then x=3."),
      q("Solve or classify 6x+9=3(2x+3).", "Infinitely many solutions", "The right side distributes to 6x+9."),
      q("Solve or classify 2(3x−4)=6x−7.", "No solution", "Simplification leaves −8=−7."),
      q("Solve or classify 8−2x=4x−10.", "One solution: x=3", "Collecting terms gives 18=6x."),
      q("What does the final line 0x=0 mean?", "All real numbers", "Every real value satisfies the statement."),
      q("What does the final line 0x=5 mean?", "No solution", "No value can make zero equal 5."),
      q("Two graphs have the same slope but different y-intercepts. Classify their equality equation.", "No solution", "Distinct parallel lines never intersect."),
      q("Two equations simplify to the same line. Classify their equality equation.", "Infinitely many solutions", "Every point on the common line satisfies both."),
      q("A student reaches 4=4 and reports x=4. Repair the conclusion.", "Infinitely many solutions", "The variable canceled and the remaining statement is true for every x."),
      q("Classify ax+b=ax+d when b≠d.", "No solution", "Subtracting ax leaves b=d, false under the given condition."),
      q("Classify and justify 3(2x+5)−x=5x+15.", "Infinitely many solutions", "The left simplifies to 6x+15−x=5x+15, identical to the right."),
    ],
    takeaway: ["One solution leaves a variable value; no solution leaves a false statement; infinitely many leaves a true statement.", "Variable cancellation is a signal to inspect the remaining statement, not a conclusion by itself."],
  },
  "A2.9": {
    purpose: "Translate one-variable situations into linear equations, solve them, and interpret the answer with units and constraints.",
    prerequisites: [
      "Translate 'five more than x' into an expression.",
      "Identify a fixed amount and a per-unit amount in a short scenario.",
      "Solve 4x + 3 = 19.",
    ],
    exposition: [
      "A mathematical model begins with a quantity dictionary: define the variable, attach units, and identify what each number represents. Translation should preserve relationships, not merely turn keywords into operations. The phrase '5 less than a number' is x−5, while '5 less than twice a number' is 2x−5.",
      "Many one-variable models have the form total = fixed amount + rate·quantity. Others compare two totals or express a part-whole relationship. Write the equation before calculating so that another reader can audit how the context became mathematics.",
      "After solving, return to the situation. State the answer in a sentence with units, check that it satisfies the equation, and reject values that violate a contextual constraint such as a negative count or a fractional number of whole tickets.",
    ],
    definitions: [
      ["quantity dictionary", "A declaration of each variable and its meaning and units.", "It anchors symbols to the context."],
      ["fixed amount", "A quantity that does not change with the variable.", "It appears as a constant term."],
      ["rate", "An amount per unit of another quantity.", "Multiplying rate by quantity gives the variable part of a total."],
    ],
    examples: [
      ex("A taxi charges $4 plus $2.50 per mile. The fare is $19. How many miles?", ["Let m be the trip distance in miles.", "Write 4+2.50m=19.", "Subtract 4, divide by 2.50, and interpret."], "6 miles", "The fixed fee and mileage charge combine to the total fare."),
      ex("The length of a rectangle is 3 cm more than its width. Its perimeter is 30 cm. Find both dimensions.", ["Let w be width; then length is w+3.", "Write 2w+2(w+3)=30.", "Solve w=6 and compute length 9."], "Width 6 cm; length 9 cm", "Both dimensions satisfy the perimeter and comparison."),
      ex("After a 20% discount, a jacket costs $64. Find the original price.", ["Let p be the original price in dollars.", "The sale price is 80% of p, so 0.80p=64.", "Divide and check 20% off $80 is $64."], "$80", "A percent decrease multiplies the original by the remaining percent."),
    ],
    misconception: ["Translation is done by matching isolated keywords to operations.", "Word order and the relationship among quantities matter more than a single word.", "Define quantities, state the relationship in words, then write the equation."],
    questions: [
      q("A streaming plan costs $8 plus $3 per movie. The bill is $26. How many movies?", "6 movies", "Let m be movies: 8+3m=26, so m=6."),
      q("A gym charges $25 to join and $15 per month. You paid $100. How many months?", "5 months", "25+15m=100, so 15m=75."),
      q("Three consecutive integers sum to 72. Find them.", "23, 24, 25", "Let n be first: n+(n+1)+(n+2)=72, so n=23."),
      q("A number decreased by 9 is 17. Find the number.", "26", "x−9=17, so x=26."),
      q("Five less than twice a number is 21. Find the number.", "13", "2x−5=21, so 2x=26."),
      q("A rectangle's length is 4 m more than its width and its perimeter is 40 m. Find both dimensions.", "Width 8 m; length 12 m", "2w+2(w+4)=40 gives 4w=32."),
      q("A phone battery at 92% drops 8 percentage points per hour. When will it reach 44%?", "6 hours", "92−8h=44, so h=6."),
      q("A tank has 18 L and fills at 6 L/min until it has 72 L. How long?", "9 minutes", "18+6t=72, so 6t=54."),
      q("A $90 item is discounted 30%. Find the sale price.", "$63", "The remaining 70% is 0.70·90=63."),
      q("After a 25% increase, a value is 100. Find the original value.", "80", "1.25x=100, so x=80."),
      q("One angle is 12° larger than another; together they are 90°. Find both.", "39° and 51°", "Let x be smaller: x+(x+12)=90."),
      q("Tickets cost $7 each plus a one-time $3 fee. Can a total of $40 represent a whole number of tickets?", "No", "3+7t=40 gives t=37/7, not a whole ticket count."),
      q("A student writes 5−2x for '5 less than twice x.' Repair it.", "2x − 5", "The quantity being reduced is twice x."),
      q("Define a variable and equation: 180 km traveled at 60 km/h.", "Let t be hours; 60t=180", "Rate times time equals distance."),
      q("Why can x=−3 be algebraically correct but contextually invalid for a ticket count?", "Counts cannot be negative", "A model's domain can exclude a solution of the bare equation."),
      q("A rental costs $12 plus $4 per hour and totals $36. Solve, check, and interpret.", "6 hours", "12+4h=36 gives h=6; 12+4(6)=36."),
    ],
    takeaway: ["Define the variable and units before translating the relationship.", "Solve the equation, then check and interpret the value against the context and its domain."],
  },
  "A2.10": {
    purpose: "Select, explain, and verify an efficient strategy across the major forms of one-variable linear equations.",
    prerequisites: [
      "Solve a one-step equation.",
      "Distribute a factor across parentheses.",
      "Classify a true or false constant statement.",
    ],
    exposition: [
      "Equation solving is strategic rather than mechanical. Start by scanning the structure: simplify each side, clear awkward fractions or decimals when useful, collect variable terms, collect constants, and undo the final coefficient. Skip any step the equation does not need.",
      "Efficiency never replaces justification. A strong solution records transformations that preserve equality, explains a non-obvious choice, and avoids moves that create unnecessary complexity. Different valid paths should reach the same solution set.",
      "The final audit has three parts: classify the solution set, substitute numerical candidates into the original equation when appropriate, and interpret any contextual restrictions. This audit separates a plausible line of algebra from a reliable solution.",
    ],
    definitions: [
      ["structure scan", "A quick identification of grouping, like terms, denominators, decimals, and variable placement.", "It determines an efficient first move."],
      ["solution strategy", "A sequence of valid transformations chosen for a particular equation.", "More than one strategy may be correct."],
      ["final audit", "Classification, verification, and interpretation of the result.", "It uses the original equation and any stated domain."],
    ],
    examples: [
      ex("Solve 4(x − 3) + 2 = 2x + 10.", ["Distribute and combine to get 4x−10=2x+10.", "Subtract 2x and add 10.", "Solve x=10 and check both sides equal 30."], "x = 10", "A structure scan reveals distribution and variables on both sides."),
      ex("Solve x/4 + (x−2)/6 = 3.", ["Use LCD 12 to clear fractions.", "Obtain 3x+2(x−2)=36.", "Simplify, solve x=8, and check."], "x = 8", "Clearing denominators first avoids repeated fraction arithmetic."),
      ex("Classify 3(2x+1)−x = 5x+4.", ["Simplify the left side to 5x+3.", "Subtract 5x from both sides.", "Interpret the false statement 3=4."], "No solution", "The final form, not the presence of x at the start, determines the classification."),
    ],
    misconception: ["A memorized sequence should be applied even when it makes the equation harder.", "Forcing every possible step can introduce fractions, extra signs, and more chances for error.", "Scan the structure and choose the simplest valid next transformation."],
    questions: [
      q("Solve 6x − 5 = 31.", "x = 6", "Add 5 and divide by 6."),
      q("Solve 4(x + 3) = 28.", "x = 4", "Divide by 4 first, then subtract 3."),
      q("Solve 3x + 8 = x + 18.", "x = 5", "Collect x terms and constants to get 2x=10."),
      q("Solve 2(5x−1)+3=31.", "x = 3", "Simplify to 10x+1=31."),
      q("Solve x/3 + 1/2 = 5/2.", "x = 6", "Multiply by 6: 2x+3=15."),
      q("Solve 0.4x + 1.6 = 4.8.", "x = 8", "Multiply by 10 or subtract 1.6 and divide by 0.4."),
      q("Classify 5(x−2)=5x−10.", "Infinitely many solutions", "Both sides are identical after distribution."),
      q("Classify 2(x+4)=2x+9.", "No solution", "Simplification leaves 8=9."),
      q("Solve 7−2(x+1)=3x.", "x = 1", "Simplify to 5−2x=3x, then 5=5x."),
      q("Solve 3(x−4)+2x=2(x+1)+1.", "x = 5", "Simplify to 5x−12=2x+3, then 3x=15."),
      q("Choose an efficient first step for 12(x−5)=36 and explain.", "Divide both sides by 12", "It immediately reduces the equation to x−5=3."),
      q("Choose an efficient first step for x/8+x/12=5.", "Multiply every term by 24", "The LCD clears both denominators."),
      q("Find and repair the error: from 3(x−2)=15, a student writes 3x−2=15.", "3x − 6 = 15", "Distribution multiplies every term inside the parentheses."),
      q("Compare solving 2x+7=19 by subtracting 7 first versus dividing by 2 first.", "Subtracting 7 first is cleaner", "Dividing first creates 7/2; both can be valid if every term is divided."),
      q("Solve ax+b=c for x and state the needed restriction.", "x=(c−b)/a, a≠0", "Subtract b and divide by nonzero a."),
      q("Complete a final audit for 4(x−3)+2=2x+10.", "x=10; both sides equal 30", "The equation has one solution, and substitution into the original gives 30=30."),
    ],
    takeaway: ["Scan the equation before choosing a first move; use only the steps its structure needs.", "A reliable solution states the solution set and verifies it against the original equation and domain."],
  },
};
