export const FOUNDATION_EXTENSIONS = {
  "A0.1": [
    "Signed numbers are especially useful when a quantity changes repeatedly. Instead of restarting a story after every event, keep one running total: initial value + first change + second change + ⋯. A bank balance of $12 followed by a $20 purchase, a $5 refund, and a $3 fee is 12 + (−20) + 5 + (−3) = −6. Grouping the positive and negative changes gives (12 + 5) + [(−20) + (−3)] = 17 − 23 = −6. The regrouping is legal because addition is associative and commutative; it is not legal to rearrange an unrevised chain of subtractions as though every symbol were addition.",
    "Pay special attention to words that reverse the viewpoint. “How much greater is a than b?” asks for a − b, while “the change from a to b” asks for b − a. Those expressions have opposite signs unless the values are equal. Write a short arrow from the initial value to the final value before choosing an expression. The arrow identifies direction, and its length identifies absolute change. This habit separates three answers that students often blur together: final position, signed change, and distance traveled. They may have the same magnitude in a one-step problem, but they do not represent the same quantity.",
  ],
  "A0.2": [
    "Standard algorithms can be explained one place at a time. In 5,002 − 786, the zero tens and zero hundreds do not mean there is nothing available; one thousand can be exchanged for ten hundreds, one of those hundreds for ten tens, and one ten for ten ones. Each exchange preserves value. Recording the regrouped places carefully turns “borrowing across zeros” into a sequence of equal representations rather than a mysterious exception. The same principle explains carrying in multiplication: ten ones are renamed as one ten, ten tens as one hundred, and so on.",
    "An estimate can be a range rather than one rounded value. Because 398 lies between 390 and 400, the product 398·27 lies between 390·27 and 400·27. This bounds the answer between 10,530 and 10,800 before exact multiplication begins. Bounds are particularly helpful when every rounding choice would push in the same direction. They also reveal calculator-key errors more sharply than a single approximate target. When reporting a real measurement or cost, distinguish an exact count from an approximation by using words such as “exactly,” “about,” or an appropriate rounding symbol.",
  ],
  "A0.3": [
    "Lists of factors and multiples can solve small cases, but prime powers explain why the method works and scale to larger numbers. For two positive integers a and b, the product GCF(a,b)·LCM(a,b) equals a·b. This identity provides a useful check: after finding the GCF, divide a·b by it to recover the LCM. It also shows why the shared prime powers cannot be counted twice in the LCM. The GCF holds one copy of the overlap; the LCM holds enough factors to satisfy both complete inventories.",
    "Grouping problems may have more than two constraints. If 72 red cards, 108 blue cards, and 180 green cards must be divided into the greatest possible number of identical packets, the number of packets is GCF(72,108,180). Each packet then receives the original count divided by that GCF. Timing problems work dually: for three repeating cycles, take the maximum exponent of every prime appearing anywhere. Always answer the second contextual question too—what goes in each group, or what clock time corresponds to the elapsed LCM—rather than stopping at an unlabeled integer.",
  ],
  "A0.4": [
    "Negative signs in fractions can be placed in the numerator, denominator, or in front of the fraction: (−a)/b = a/(−b) = −(a/b) when b ≠ 0. Two negative signs cancel because (−a)/(−b) = a/b. A standard form keeps a positive denominator so comparisons and later algebra are easier to read. Zero in the numerator is allowed when the denominator is nonzero, and it represents the number zero. Zero in the denominator is never repaired by calling the fraction “infinity”; the expression has no value in ordinary real-number arithmetic.",
    "Density is an important feature of fractions: between any two distinct rational numbers lies another rational number. One easy construction is their average. Between 2/5 and 3/5, for example, lies [(2/5) + (3/5)]/2 = 1/2. This means fractions are not isolated tick marks that appear only when a denominator is announced. The number line contains infinitely many rational points in every interval. That perspective matters later when inequalities describe entire intervals and when a graph’s scale displays only a few labels even though every point between them still represents a number.",
  ],
  "A0.5": [
    "Multiplication by a fraction can be read in either order because multiplication is commutative, but the two readings emphasize different ideas. Three-fourths of 20 is (3/4)·20, while 20 groups of three-fourths is 20·(3/4); both equal 15. In a context, choose the reading that matches the units. “Three-fourths of 20 meters” produces meters, whereas “20 pieces, each three-fourths of a meter” also produces meters by multiplying pieces by meters per piece. Writing units beside factors makes the common structure visible.",
    "Division situations split into measurement and sharing interpretations. The expression 6 ÷ 3/4 can ask how many three-fourth-size groups fit into 6; the answer is 8 groups. The expression 3/4 ÷ 6 can ask how much each of 6 equal shares receives; the answer is 1/8. Both use reciprocal multiplication, but their stories and units differ. Before computing, say which quantity is the total and which is the group size or number of groups. This prevents reversing the dividend and divisor merely because the smaller number “looks as if it should go first.”",
  ],
  "A0.6": [
    "Subtraction deserves its own estimate because the exact result may be small even when both fractions are large. For 11/12 − 5/6, both values are near 1, so their difference should be near 0; rewriting 5/6 as 10/12 reveals the exact difference 1/12. If an algorithm instead produces 16/18, the benchmark prediction immediately exposes the error. When subtracting mixed numbers, also decide whether the answer should cross a whole-number boundary. That prediction guides regrouping and makes a misplaced whole part easier to see.",
    "Two methods for complex fractions should agree. For (1/3 + 1/6)/(3/4), simplifying the numerator first gives (1/2)/(3/4) = 2/3. Clearing small denominators multiplies every term above and below the main bar by 12: the numerator becomes 4 + 2, the denominator becomes 9, and 6/9 = 2/3. The second method is efficient only when distribution reaches every term. Writing large parentheses around the full numerator and denominator before multiplying is a simple visual safeguard against clearing some fractions but not others.",
  ],
  "A0.7": [
    "Repeating decimals can be converted back to fractions with place-value subtraction. If x = 0.272727…, then 100x = 27.272727…. Subtracting the first equation from the second gives 99x = 27, so x = 27/99 = 3/11. The subtraction removes the infinite repeating tails because they align exactly. This method shows that a repeating decimal is not an approximation; it is another exact notation for a rational number. A rounded decimal such as 0.27, by contrast, equals exactly 27/100 and is only near 3/11.",
    "Percent language can hide a multiplicative factor. Increasing by 12% means multiplying by 1 + 0.12 = 1.12, while decreasing by 12% means multiplying by 1 − 0.12 = 0.88. These operations are not inverses: a 12% increase followed by a 12% decrease multiplies by 1.12·0.88 = 0.9856, leaving 98.56% of the start. Whenever several percent changes occur, use a separate multiplier for each stage and keep the changing reference amount visible. Adding the percent labels usually gives the wrong model.",
    "When data are rounded, a percent calculated from them is also approximate. Report enough digits to support the decision but not more precision than the inputs justify. In money contexts, keep full calculator precision during the computation and round the final currency amount to cents; in survey contexts, name the sample or reference population. A percent is never self-explanatory: 40% of 50 and 40% of 500 have the same rate but very different parts.",
  ],
  "A0.8": [
    "Proportions compare corresponding quantities, so the order inside every ratio must remain consistent. If 4 notebooks cost $10, the ratios 4 notebooks/$10 and n notebooks/$35 may be equated; so may $10/4 notebooks and $35/n notebooks. Mixing one orientation with the other creates an equation about unlike rates. Label numerator and denominator units before solving. When the units match across the equality, cross-products inherit compatible compound units and the numerical equation represents the intended comparison.",
    "Not every rate problem is proportional. A taxi fare with a $4 starting fee plus $2 per mile does not have a constant fare-to-mile ratio, because the fixed fee is present even at zero miles. A quantity y is proportional to x only when y = kx for one constant k and the relationship passes through (0,0). Look for fixed starting amounts, minimum charges, or one-time fees before setting up a proportion. If such a quantity exists, the model is usually additive-plus-multiplicative and belongs to the later study of linear equations rather than a single ratio equality.",
    "Scale drawings require the same unit on both sides of a scale ratio. A map scale of 1 cm to 8 km may be used directly only if map lengths are in centimeters and actual lengths are in kilometers; converting first avoids mixing centimeters with meters or miles. After solving, ask whether enlargement or reduction makes sense. A small map distance should correspond to a larger real distance, whereas a scale model may be smaller or larger depending on the stated factor.",
  ],
  "A0.9": [
    "Conversion factors are equal quantities written as a ratio equal to 1. Because 1 foot = 12 inches, either 12 in/1 ft or 1 ft/12 in may be used; choose the orientation that cancels the starting unit. Converting 7.5 feet to inches gives 7.5 ft·(12 in/1 ft) = 90 in. The numerical value changes because the unit size changes, but the physical length does not. Keeping units attached through every multiplication makes dimensional analysis a chain of justified substitutions rather than a memorized direction for moving decimals.",
    "Area and volume conversions require powers of the linear conversion. Since 1 m = 100 cm, a square meter is (100 cm)² = 10,000 cm², not 100 cm². A cubic meter is (100 cm)³ = 1,000,000 cm³. Draw or imagine the grid: 100 small lengths fit along each dimension, so a square contains 100·100 small squares. This is why a conversion factor must be squared for area and cubed for volume. A dimensional check catches the common mistake of applying a one-dimensional factor to a two- or three-dimensional measurement.",
    "Derived units can be converted as complete ratios. To convert 60 miles per hour to miles per minute, multiply by 1 hour/60 minutes so hours cancel and obtain 1 mile per minute. To convert both the distance and time units, use one factor for each. Never cancel labels that occur in the same numerator or the same denominator; cancellation represents division by a common unit factor. The surviving compound unit predicts the kind of quantity the numerical answer can describe.",
  ],
  "A0.10": [
    "Exponent laws describe repeated multiplication of the same base. In x³x⁵, the factors combine into eight copies of x, so exponents add. In (x³)⁵, five groups of three copies create fifteen copies, so exponents multiply. These explanations require attention to the base: x³y⁵ cannot be combined into one power because the bases differ. Addition behaves differently as well; x³ + x⁵ is a sum of unlike terms, not x⁸. State the operation before selecting an exponent law.",
    "Scientific notation separates size from precision. In 6.20 × 10⁴, the coefficient 6.20 records three significant digits while the power of ten records scale. For multiplication, multiply coefficients and add exponents, then renormalize so the coefficient is at least 1 and less than 10. For addition, first rewrite the numbers with the same power of ten because the coefficients then count equal place-value units. Estimating the power of ten before calculation guards against errors caused by shifting a decimal in the wrong direction.",
    "Zero and negative exponents complete the exponent pattern. Since x³/x³ = 1 for x ≠ 0 and the quotient law gives x^(3−3) = x⁰, it follows that x⁰ = 1 for nonzero x. Continuing the pattern gives x⁻² = 1/x². A negative exponent does not make the value negative; it indicates a reciprocal. Radical notation provides another inverse relationship: the principal square root √a is the nonnegative number whose square is a, so √(x²) = |x| for real x.",
  ],
  "A1.1": [
    "A variable’s meaning includes its units, allowed values, and role. In A = s², s might be a side length measured in centimeters, so s ≥ 0 and A is measured in square centimeters. In a purely algebraic identity, s may instead range over all real numbers. Writing a variable key beside a model prevents the same letter from quietly changing meaning. It also reveals when two quantities should not share a symbol even if their current numerical values happen to match.",
    "Variables can serve as unknowns, changing quantities, generalized numbers, or parameters. In x + 7 = 12, x is an unknown to determine. In y = 3x + 2, x and y vary together. In a(b + c) = ab + ac, the letters stand for arbitrary numbers for which the operations are defined. In y = mx + b, m and b are parameters that select one line from a family. Identifying the role clarifies whether the task is to solve, evaluate, describe a relationship, or justify a statement for every permitted value.",
  ],
  "A1.2": [
    "An expression is evaluated; an equation or inequality is solved or tested. This grammatical distinction helps organize work. The expression 4x − 9 has no truth value by itself, although it has a value once x is chosen. The equation 4x − 9 = 11 can be true or false depending on x, and its solution set contains the values that make it true. The inequality 4x − 9 < 11 usually has many solutions. Naming the object correctly determines what a complete answer must contain.",
    "Equivalent equations have the same solution set, and equivalent inequalities have the same solution set. Simplifying one side of an equation can reveal structure, but changing only part of a side can change the statement. For example, 2(x + 3) = 10 is equivalent to 2x + 6 = 10, while 2x + 3 = 10 is not. Use an equals sign only between expressions known to have the same value. If a line merely announces the next action, write a short note instead of linking unequal expressions with a misleading chain of equals signs.",
  ],
  "A1.3": [
    "Structure can be read from the outermost operation inward. In 5(x − 2)² + 7, the final operation is adding 7; before that, a squared quantity is multiplied by 5. The grouped expression x − 2 is a factor inside the power, not a term of the full expression. This operation-tree view is more reliable than labeling every visible symbol from left to right. It also tells you which inverse operation would be undone first when solving an equation built from the expression.",
    "Like terms share an identical variable part, including exponents. The terms 3x² and −8x² are like terms because both multiply x²; 3x² and 3x are not. Coefficients may be combined because the distributive property gives 3x² − 8x² = (3 − 8)x². Constants are like terms with variable part 1. Naming coefficient, factor, term, base, exponent, and constant precisely makes later explanations shorter and prevents illegal combinations that merely look visually similar.",
    "A negative sign in front of grouping can be understood as a coefficient of −1. The expression −(x − 4) has two terms inside one grouped factor and rewrites as −x + 4 by distribution. In −x², the exponent applies to x before the outside negative is applied; in (−x)², the entire negative quantity is squared. Reading base and exponent precisely prevents these expressions from being treated as identical. Structure, not visual proximity, decides what each symbol controls.",
  ],
  "A1.4": [
    "Substitution is replacement with grouping. If x = −3 in 2x², the expression becomes 2(−3)², not 2·−3². Parentheses preserve the fact that the entire signed number replaces x. The same rule applies to fractions and expressions: if a = p + q, then a² becomes (p + q)². After substitution, the remaining work is numerical or symbolic evaluation under the ordinary order of operations.",
    "A table of values is repeated substitution organized to show a relationship. For y = x² − 2x, each row should use one x-value consistently through both occurrences before y is recorded. Checking symmetry, sign, or size across rows can expose an isolated arithmetic error. When a formula has several variables, hold the others fixed unless the problem changes them. State units in the final column so the table records quantities rather than disconnected numbers.",
    "Restrictions are checked before substitution, not after a calculator reports an error. In 5/(x − 2), the input x = 2 is excluded because it creates division by zero. In √x over the real numbers, negative inputs are excluded. Record these constraints with the expression so a table does not disguise an excluded output as zero or a blank. An excluded input is not a computational failure; it is information about the expression’s domain. When several substitutions are requested, evaluate one complete input at a time and keep its arithmetic on a separate line. This prevents values assigned to different variables or rows from being mixed.",
  ],
  "A1.5": [
    "Order of operations is determined by structure, not by a slogan that forces multiplication before division or addition before subtraction. Multiplication and division share one level and are performed from left to right unless grouping changes the order; addition and subtraction behave the same way. Thus 24 ÷ 6·2 = 4·2 = 8, not 24 ÷ 12. Rewriting subtraction as addition of an opposite and division as multiplication by a reciprocal can make the left-to-right structure explicit.",
    "A fraction bar, radical bar, absolute-value bars, and function notation all create grouping even when parentheses are absent. In (3 + 5)/(2²), the complete numerator and denominator must be evaluated before division. In √(9 + 16), the radical covers the entire sum. When copying an expression into a calculator, add parentheses that reproduce every visual grouping symbol. A correct keystroke sequence is a translation of the written structure, not a replacement for reading it.",
    "Nested grouping is evaluated from the innermost structure outward. Brackets and braces do not have separate arithmetic powers; they help the eye track levels of grouping. For 3[2 − (5 − 7)]², evaluate 5 − 7, then the bracketed difference, then the exponent, then multiplication. Write intermediate lines that preserve all unevaluated structure. Dropping a bracket too early can change which terms an exponent or coefficient controls. A rough magnitude estimate before the final arithmetic provides an independent check on the resulting sign and size.",
  ],
  "A1.6": [
    "Properties are permissions for rewriting, and each has a specific scope. Commutativity changes order in addition or multiplication; associativity changes grouping without changing order; distributivity connects multiplication with a sum or difference. Subtraction and division are not commutative or associative in general. Testing a proposed property with small values such as 8, 4, and 2 can quickly disprove an illegal rewrite, though a successful example alone cannot prove a rule for every number.",
    "Identity and inverse properties explain why equation-solving moves preserve values. Adding 0 or multiplying by 1 leaves a number unchanged. Adding −a to a produces 0, and multiplying nonzero a by 1/a produces 1. These are not isolated vocabulary items: they describe the cancellation created when the same operation is applied to both sides of an equation. Naming the property behind a line of work turns a sequence of symbols into an argument another person can audit.",
    "The zero-product and zero-multiplication ideas should not be confused. Every real number multiplied by zero equals zero, so 0·a = 0. If a product ab equals zero, then at least one factor must equal zero; this conclusion depends on the real-number system having no nonzero zero divisors. These statements later support factoring equations. For now, use them to check that distributing a zero coefficient or combining inverse terms does not leave stray variable pieces. A property name should explain the exact rewrite on the page rather than decorate a line after the fact. Match the name to the changed structure.",
  ],
  "A1.7": [
    "Equivalent expressions agree for every value in their common domain, not merely for one convenient test value. Numerical substitution is useful for finding a counterexample: if two expressions give different values once, they are not equivalent. But matching at one or even several inputs does not establish an identity. A valid property-based transformation, such as distribution or combining like terms, supplies the general justification.",
    "Simplest form depends on purpose. Expanded form can reveal like terms and support addition; factored form can expose zeros, common factors, or repeated structure. For 6x + 12, the form 6(x + 2) highlights a common factor, while 6x + 12 may be easier to combine with another polynomial. The goal is not always the shortest string. Choose a form that makes the next mathematical question easier, and preserve domain restrictions when a rewrite involves division.",
    "A transformation can be checked locally. After distributing, multiply the coefficient by every term and compare signs. After combining like terms, substitute a simple value such as 0, 1, or −1 into the expression before and after the step. This does not prove an unsupported transformation, but it catches many arithmetic slips immediately. The strongest written justification still names the property that guarantees equivalence for all allowed inputs. Preserve the original expression until the check is finished so both forms remain available for comparison. If a restriction exists, choose a permitted test value carefully.",
  ],
  "A1.8": [
    "A formula is a compact model whose symbols must be connected to measured or defined quantities. Before substituting, write a variable key and convert all data to compatible units. In d = rt, a rate in kilometers per hour and a time in minutes cannot be multiplied directly without converting one unit. The unit product should simplify to the requested output. If it does not, the formula, conversion, or substitution order needs repair.",
    "Communication includes precision. An exact value such as 10/3 should remain exact unless the context requests a decimal; a measurement-based result should be rounded to a sensible place and labeled with units. A complete formula solution shows the original formula, the substitution with parentheses, the calculation, and a sentence interpreting the result. This small amount of structure lets a reader distinguish a conceptual modeling decision from an arithmetic step and makes an error easier to locate.",
    "Rearranging a formula creates a reusable form for a different unknown. From d = rt, dividing by nonzero t gives r = d/t; dividing by nonzero r gives t = d/r. State the nonzero condition that permits division. Checking dimensions verifies the rearrangement: distance divided by time has rate units, while distance divided by rate has time units. A formula that is symbolically neat but dimensionally inconsistent cannot model the stated quantities. Keep symbols through the rearrangement and substitute numbers only after the desired variable stands alone.",
  ],
  "A2.1": [
    "A solution is a value that makes the original equation true. Solving produces a candidate; substitution decides whether the candidate belongs to the solution set. This distinction matters when later operations can introduce extraneous values or lose restrictions, but it is already useful for linear equations because it catches sign and distribution errors. Substitute into the untouched original equation, simplify the left and right sides independently, and compare them without assuming they must match.",
    "Solution sets can contain one number, no numbers, many numbers, or—in later work—structured collections. For a one-variable linear equation, write a singleton solution as x = 4 or {4}; do not report the check line 9 = 9 as though 9 were the solution. If a context restricts possible values, intersect the algebraic solution with that domain. A negative length or a fractional number of indivisible objects may solve the symbolic equation but fail the model.",
    "An equation may also be viewed as an intersection question: for which inputs do the left-hand expression and right-hand expression have the same output? A table can test selected candidates, and a graph can display intersections, but algebra gives an exact solution when the expressions are manageable. Whichever representation is used, the definition is unchanged. A candidate belongs only when both sides evaluate to exactly the same value within the stated number system.",
  ],
  "A2.2": [
    "Addition and subtraction equations are solved by isolating the variable term with an inverse operation. In x − 7 = 15, adding 7 to both sides creates x + 0 = 22. The balance is preserved because equal quantities remain equal after the same number is added. Writing the operation on both sides is more informative than moving a term across the equals sign and changing its sign, a shortcut that can hide why the new equation is equivalent.",
    "The variable need not appear on the left. For 18 = y + 5, subtract 5 from both sides to obtain 13 = y, which may be reordered as y = 13 because equality is symmetric. Signed constants require extra care: x + (−8) = 3 is undone by adding 8, while x − (−8) = 3 is first read as x + 8 = 3. A number-line interpretation can check whether the isolated value completes the stated change.",
    "A one-step equation can model a change from an unknown start or toward an unknown finish. If a temperature rose 11 degrees to reach −2°, then x + 11 = −2 and the starting temperature was −13°. The negative answer is reasonable because the rise crossed toward zero but ended below it. Attach the result to the story and reverse the change: −13 + 11 = −2. This interpretation is a stronger check than arithmetic alone.",
  ],
  "A2.3": [
    "Multiplication and division equations are undone with reciprocal operations. If 7x = 35, divide both sides by the nonzero coefficient 7. If x/5 = 9, multiply both sides by 5. The coefficient includes its sign, so −4x = 20 requires division by −4 and gives x = −5. Separating the sign from the magnitude during a prediction can prevent an answer with the wrong direction.",
    "Fractional coefficients are often cleared by multiplying by their reciprocal. In (3/5)x = 12, multiplying both sides by 5/3 creates x = 20. The reciprocal exists because 3/5 is nonzero. Alternatively, multiply by 5 and then divide by 3; both paths preserve equality and should agree. Choose the form with fewer opportunities for arithmetic error, then verify by reconstructing the original product or quotient.",
    "A zero coefficient creates a special case rather than an ordinary division step. In 0x = 0, every real x works; in 0x = 7, no real x works. Dividing by zero is not permitted, so the instruction “divide by the coefficient” always carries a nonzero condition. Recognizing this boundary prepares the later classification of equations and prevents a forbidden operation from being hidden in an otherwise familiar procedure. A final check should therefore inspect both the candidate value and whether every operation used to obtain it was allowed.",
  ],
  "A2.4": [
    "Simplifying before solving means replacing each side with an equivalent expression, not performing an operation that changes only one side. Distribute through grouping, combine like terms, and reduce numerical fractions while keeping the equality visible. In 3(x + 4) − 2x = 19, the left side becomes 3x + 12 − 2x = x + 12, after which one inverse step isolates x. The simplification reveals that an apparently multistep equation has a simple underlying structure.",
    "Do not combine across the equals sign. The equation 4x + 3 = 2x + 11 has like terms on different sides, but they belong to different expressions. Subtracting 2x from both sides is an equality-preserving operation; simply calling 4x and 2x “like terms” and replacing them with 2x without showing the balance loses the argument. Keep a vertical equals-sign spine so every line clearly states an equation equivalent to the one above it.",
    "Fractions and negative coefficients can be simplified before isolation too. In −(x − 6) + 2x = 13, distributing −1 gives −x + 6 + 2x = 13, then combining like terms gives x + 6 = 13. A common error is to change only the first sign inside the parentheses. Writing the hidden coefficient −1 and multiplying it by every term makes the structure explicit and produces an equation that is easier to solve. Circle or underline the terms that are truly like before combining them; coefficients may change, but the shared variable part must remain intact. Constants combine only with other constants on the same side of the equation.",
  ],
  "A2.5": [
    "A useful solving strategy works from the outside inward: simplify each side, collect variable terms, collect constants, and scale the remaining coefficient to 1. This is the reverse of evaluating an expression, where the innermost grouping is handled first. For 4(2x − 3) + 5 = 25, distribution and combination give 8x − 7 = 25, then addition isolates 8x, and division isolates x. Writing one justified transformation per line lowers cognitive load.",
    "Efficiency should not erase reasoning. Some equations permit a helpful first move, such as dividing every term by a common factor or clearing several fractions with one least common denominator. A move is good when it applies to both complete sides and reduces complexity. Before choosing it, scan for distribution, like terms, fraction denominators, and variable terms on both sides. After solving, estimate whether the sign and size of the answer fit the original equation before doing the exact substitution check.",
    "Keep arithmetic exact while solving. Replacing 1/3 with 0.33 can turn an exact equation into an approximation and make a correct check appear slightly unequal. If decimals are already part of measured data, retain enough precision and use an approximation symbol in the conclusion. Exact symbolic work and approximate numerical modeling are both legitimate, but the notation should tell the reader which claim is being made. In either case, carry extra precision through intermediate steps and round only the interpreted final quantity.",
  ],
  "A2.6": [
    "Equations with decimal coefficients may be solved in decimal form or converted to whole-number coefficients by multiplying every term on both sides by a power of ten. For 0.3x + 1.2 = 2.7, multiplying the entire equation by 10 gives 3x + 12 = 27. The multiplication must reach every term; multiplying only the decimal terms changes the equation. The whole-number version often reduces calculator dependence and makes exact checking easier.",
    "For fractional coefficients, multiply every term by the least common denominator of all numerical denominators. In x/3 − 1/4 = 5/6, the LCD is 12, so 12(x/3) − 12(1/4) = 12(5/6), giving 4x − 3 = 10. Clearing denominators does not mean canceling terms across addition; it is distribution of one nonzero multiplier across both complete sides. Preserve any original denominator restrictions when variables later appear in denominators.",
    "After clearing decimals or fractions, the new equation should be equivalent to the original, so either may be used for solving but the original should be used for the final check. Track multiplication with parentheses: 12(x/3 − 1/4) = 12(5/6) makes distribution visible. If every coefficient shares a common integer factor after clearing, divide the entire equation by that factor to reduce the numbers before isolating x. Write the chosen LCD or power of ten explicitly so every transformed coefficient can be audited. Confirm carefully that no term on either side was skipped during complete distribution.",
  ],
  "A2.7": [
    "When variables appear on both sides, collect them on the side that makes the arithmetic convenient. In 7x − 4 = 3x + 20, subtracting 3x produces a positive 4x; subtracting 7x would also be valid but creates −4x. Both paths must lead to the same solution if the balance is maintained. There is no rule that variables must move left—only a preference for clear, efficient work.",
    "After variable terms are collected, the equation may become an ordinary one- or two-step equation, or the variable may disappear. Track the coefficient carefully: subtracting 3x from 7x leaves 4x, while subtracting 7x from 3x leaves −4x. A quick check substitutes the candidate into both original expressions rather than into a simplified line, because the original is the claim the solution must satisfy.",
    "Grouping can conceal variable terms on both sides. In 2(x + 5) = 3(x − 1), distribute before collecting: 2x + 10 = 3x − 3. Subtracting 2x gives 10 = x − 3, then adding 3 gives x = 13. Substitution confirms both original sides equal 36. The check is particularly valuable because a single missed distribution sign would create a plausible-looking but incorrect candidate. When fractions are present too, clear denominators only after recording restrictions and distributing the common multiplier across every term. The goal is a simpler equivalent equation, not merely fewer visible fraction bars. Keep variable terms on one side and constants on the other only after both sides have been simplified. This order prevents terms hidden inside grouping from being collected prematurely.",
  ],
  "A2.8": [
    "If the variable disappears and the remaining statement is true, every value in the stated domain solves the equation. For 2(x + 3) = 2x + 6, distribution produces 2x + 6 = 2x + 6 and subtraction leaves 6 = 6. The equation is an identity. If the remaining statement is false, as in 2(x + 3) = 2x + 9 leading to 6 = 9, no value can make the original sides equal.",
    "Do not divide by a variable expression in an attempt to avoid these cases. Dividing both sides by x can silently discard x = 0, and dividing by an expression that may equal zero is not an equivalent operation over the full domain. Collect terms using addition or subtraction first. Report the conclusion as a solution set—one value, no solution, or all real numbers in the domain—and explain how the final true or false statement supports it.",
    "Context can narrow an all-values conclusion. An identity derived from a formula may hold for every value in its algebraic domain but still describe only nonnegative times or positive lengths in the model. Likewise, “no solution” means no allowed value satisfies all stated conditions, not that the algebraic procedure failed. State the relevant domain in the conclusion so the solution set answers the actual problem rather than a broader symbolic version. Testing one input can illustrate an identity, but the simplified true statement explains why all allowed inputs work.",
  ],
  "A2.9": [
    "Translation begins with quantities and relationships, not keywords. Define the unknown with units, then describe how each given quantity is built from it. “Five more than twice a number” is 2x + 5 because the number is doubled before 5 is added; “twice the sum of a number and 5” is 2(x + 5). Reading the finished expression back in words is an effective structure check.",
    "A good model distinguishes a starting amount, repeated rate, and final amount. A phone plan with a $25 base fee and $8 per gigabyte is C = 25 + 8g. If the bill is $73, the equation 25 + 8g = 73 asks which usage produces that total. Units verify the terms: dollars + (dollars/gigabyte)(gigabytes) = dollars. After solving, interpret g in the context and check constraints such as nonnegativity or whole-number counts.",
    "Diagrams and tables can expose relationships before symbols are chosen. For consecutive integers, define the first as n and the next as n + 1 rather than assigning unrelated variables. For a perimeter, label each equal side with the same expression and add every side once. The equation should preserve the structure shown in the representation. If the solved value is substituted back into the diagram or table, every given total and relationship should be recovered.",
  ],
  "A2.10": [
    "Strategy choice should respond to structure. Clear grouping and combine like terms before trying to isolate a variable; clear fractions when denominators obscure that structure; collect variable terms before deciding whether the equation has one, no, or infinitely many solutions. Annotate the purpose of each move in a margin—“distribute,” “collect x-terms,” “undo +7”—so a long solution remains readable and an error can be traced to its first cause.",
    "A complete solution has four parts: a defined variable, a sequence of equivalent equations, a verification in the original equation, and an interpreted conclusion. For a contextual problem, the conclusion also checks units and feasibility. For a symbolic problem, the conclusion states the solution set and any restrictions. Comparing two valid solution paths is worthwhile: if both preserve equality, they should converge on the same result, and the shorter or clearer path can inform future strategy without turning into an unexplained shortcut.",
    "When reviewing work, locate the first line that is not equivalent to the one before it. A wrong final answer is a symptom; the instructional value lies in identifying whether the first failure came from translation, distribution, combining terms, an inverse operation, or arithmetic. Repair that one step and continue from the corrected equation. This error-analysis habit turns a completed solution into feedback and is more effective than erasing the entire attempt and copying a model answer. Record the repaired principle in words so it can guide the next problem, not just the current correction.",
  ],
};
