import { algebraArticle } from "./shared";

export const equationsArticles = [
  algebraArticle({
    slug: "order-of-operations-with-variables", topicSlug: "expressions-equations", archetype: "concept",
    title: "Order of operations with variables: what actually comes first?", shortTitle: "Order of operations",
    deck: "Parentheses and exponents set the structure; multiplication, division, addition, and subtraction then move left to right within their own level.",
    course: "Algebra I", difficulty: "Foundational", minutes: 7,
    formula: String.raw`3+2(x-4)^2`,
    immediate: { label: "Core rule", tex: String.raw`\text{grouping}\to\text{powers}\to\text{products}\to\text{sums}`, text: "Multiplication does not always beat division, and addition does not always beat subtraction. Equal-priority operations are read from left to right." },
    sections: [
      ["Read the structure before calculating", "An expression is a set of nested instructions. Grouping symbols tell you which part acts as one unit, while an exponent belongs only to its base unless parentheses enlarge that base.", "A quick pause to mark the groups prevents the most common error: applying an operation to more of the expression than the notation allows.", String.raw`-3^2=-(3^2)=-9\qquad(-3)^2=9`],
      ["Multiplication and division share a level", "The familiar acronym can make it sound as if multiplication must happen before division. They have equal priority, so evaluate whichever appears first when reading left to right.", "Addition and subtraction work the same way. A subtraction can be rewritten as addition of a negative, which makes the left-to-right rule easier to see.", String.raw`24\div6\cdot2=4\cdot2=8`],
      ["Variables do not change the rule", "A variable is simply a number whose value is not yet fixed. Substitute with parentheses, then use the same structure you would use for a numerical expression.", "Keeping substituted negatives in parentheses is especially important because the exponent and the negative sign may not belong to the same base.", String.raw`x=-2:\quad 5-x^2=5-(-2)^2=1`],
    ],
    example: { heading: "Evaluate with care", prompt: "Evaluate 3 + 2(x − 4)² when x = 1.", steps: [[String.raw`3+2(1-4)^2`, "Substitute 1 for x and keep the grouped difference."], [String.raw`3+2(-3)^2`, "Evaluate inside the parentheses."], [String.raw`3+2(9)=21`, "Square, multiply, then add."]], result: String.raw`\boxed{21}` },
    mistakes: ["Treating the acronym as a strict left-to-right list.", "Letting an exponent apply beyond its actual base.", "Substituting a negative value without parentheses."],
    takeaways: ["Grouping defines the expression's shape.", "Equal-priority operations move left to right.", "Substitute first, then simplify."],
    related: ["combining-like-terms", "exponent-rules", "function-notation"],
  }),
  algebraArticle({
    slug: "combining-like-terms", topicSlug: "expressions-equations", archetype: "method",
    title: "Combining like terms without combining things that only look alike", shortTitle: "Combining like terms",
    deck: "Terms combine only when their variable parts match exactly. The coefficients change; the variable structure does not.",
    course: "Algebra I", difficulty: "Foundational", minutes: 7,
    formula: String.raw`4x^2-3x+7+5x^2+2x-1`,
    immediate: { label: "Pattern", tex: String.raw`ax^n+bx^n=(a+b)x^n`, text: "Same variables, same exponents: combine the coefficients. Different variable parts stay separate." },
    sections: [
      ["A term has two jobs", "The coefficient tells how many copies there are; the variable part tells what kind of object is being counted. Like terms have identical variable parts, including every exponent.", "That is why 3x and 5x combine, but 3x and 5x² do not. They name different algebraic quantities.", String.raw`3x+5x=8x\qquad3x+5x^2\text{ cannot combine}`],
      ["Signs travel with their terms", "A minus sign immediately before a term belongs to that term. When you rearrange an expression, move the sign with the coefficient.", "Rewriting subtraction as addition of a negative makes this explicit and reduces dropped-sign errors.", String.raw`6x-4+2x=6x+(-4)+2x`],
      ["Distribute before you collect", "Parentheses may hide terms that are not ready to combine. Use the distributive property first, then group matching variable parts.", "A negative multiplier must reach every term inside the parentheses, not just the first one.", String.raw`2(3x-4)-(x+5)=6x-8-x-5`],
    ],
    example: { heading: "Collect by variable part", prompt: "Simplify 4x² − 3x + 7 + 5x² + 2x − 1.", steps: [[String.raw`(4x^2+5x^2)+(-3x+2x)+(7-1)`, "Group terms with identical variable parts."], [String.raw`9x^2-x+6`, "Add the coefficients within each group."]], result: String.raw`\boxed{9x^2-x+6}` },
    mistakes: ["Adding exponents when adding terms.", "Combining x with x².", "Leaving a minus sign behind when rearranging."],
    takeaways: ["Variable parts must match exactly.", "Only coefficients combine.", "Distribute before collecting terms."],
    related: ["order-of-operations-with-variables", "distributive-property", "multiply-polynomials"],
  }),
  algebraArticle({
    slug: "distributive-property", topicSlug: "expressions-equations", archetype: "concept",
    title: "The distributive property: why the outside factor reaches every term", shortTitle: "Distributive property",
    deck: "Distribution is multiplication across a sum. It expands an expression without changing its value—and it works in reverse when factoring.",
    course: "Algebra I", difficulty: "Foundational", minutes: 8,
    formula: String.raw`a(b+c)=ab+ac`,
    immediate: { label: "Identity", tex: String.raw`a(b+c)=ab+ac`, text: "The grouped sum is one quantity. Multiplying that quantity by a means multiplying each part of the sum by a." },
    sections: [
      ["Why distribution is legal", "Imagine b + c as a length split into two pieces. A rectangle of height a has total area a(b + c), which is also the sum of the two smaller areas ab and ac.", "The same equality holds for negative numbers, variables, and expressions. Distribution is structural, not a visual trick.", String.raw`-3(2x-5)=-6x+15`],
      ["The negative sign is a factor", "A minus sign before parentheses can be read as multiplication by negative one. Every term inside must change sign.", "This is the source of many equation errors: the first term changes, but the later terms are accidentally left alone.", String.raw`-(x-4+2y)=-x+4-2y`],
      ["Factoring runs the movie backward", "If two terms share a factor, pull it outside and leave behind what remains after division. Expanding can verify the result immediately.", "The greatest common factor produces the most useful factored form because nothing common remains inside.", String.raw`12x^2-18x=6x(2x-3)`],
    ],
    example: { heading: "Distribute and simplify", prompt: "Simplify 3(2x − 5) − 2(x + 4).", steps: [[String.raw`6x-15-2x-8`, "Distribute both factors, including the negative two."], [String.raw`(6x-2x)+(-15-8)`, "Collect like terms."], [String.raw`4x-23`, "Combine coefficients and constants."]], result: String.raw`\boxed{4x-23}` },
    mistakes: ["Multiplying only the first term in parentheses.", "Forgetting that a leading minus means −1.", "Changing signs without multiplying magnitudes."],
    takeaways: ["Every term receives the outside factor.", "A minus sign can be treated as −1.", "Factoring is reverse distribution."],
    related: ["combining-like-terms", "greatest-common-factor", "solving-linear-equations"],
  }),
  algebraArticle({
    slug: "solving-linear-equations", topicSlug: "expressions-equations", archetype: "method",
    title: "Solving linear equations: keep the balance, not a bag of tricks", shortTitle: "Solve linear equations",
    deck: "An equation stays true when the same legal operation is applied to both sides. Simplify, isolate, and check.",
    course: "Algebra I", difficulty: "Foundational", minutes: 9,
    formula: String.raw`3(x-2)+5=2x+9`,
    immediate: { label: "Goal", tex: String.raw`ax+b=c\quad\Longrightarrow\quad x=\frac{c-b}{a}`, text: "The compact formula is useful, but the reliable habit is balance: perform the same reversible move on both sides." },
    sections: [
      ["Start by reducing clutter", "Distribute and combine like terms on each side before moving terms across the equals sign. This exposes the equation's real structure.", "Fractions can often be cleared by multiplying every term on both sides by a common denominator. Skipping a term breaks the balance.", String.raw`\frac{x}{3}+\frac12=2\quad\Longrightarrow\quad2x+3=12`],
      ["Isolate in a sensible order", "Move variable terms to one side and constants to the other. Then undo multiplication or division around the variable.", "There is rarely one mandatory sequence. Prefer moves that keep coefficients small and reduce the chance of sign errors.", String.raw`5x-7=2x+8\quad\Longrightarrow\quad3x=15`],
      ["The check is part of the solution", "Substitute the proposed value into the original equation, not a later simplified line. Both sides should produce the same number.", "A check catches arithmetic slips and also reveals equations with no solution or infinitely many solutions when the variable disappears.", String.raw`x=5:\quad5(5)-7=2(5)+8=18`],
    ],
    example: { heading: "Balance both sides", prompt: "Solve 3(x − 2) + 5 = 2x + 9.", steps: [[String.raw`3x-6+5=2x+9`, "Distribute the three."], [String.raw`3x-1=2x+9`, "Combine constants on the left."], [String.raw`x-1=9`, "Subtract 2x from both sides."], [String.raw`x=10`, "Add one to both sides."]], result: String.raw`\boxed{x=10}` },
    mistakes: ["Moving a term by changing its sign without naming the operation.", "Applying a denominator-clearing multiplier to only some terms.", "Checking in a simplified line that already contains the same error."],
    takeaways: ["Simplify each side first.", "Use the same operation on both sides.", "Check in the original equation."],
    related: ["variables-on-both-sides", "distributive-property", "no-one-infinite-solutions"],
  }),
  algebraArticle({
    slug: "variables-on-both-sides", topicSlug: "expressions-equations", archetype: "decision",
    title: "Variables on both sides: which side should you move them to?", shortTitle: "Variables on both sides",
    deck: "Either side can work. Choose the direction that keeps the variable coefficient positive and the arithmetic easy to audit.",
    course: "Algebra I", difficulty: "Foundational", minutes: 8,
    formula: String.raw`7-2x=4x+19`,
    immediate: { label: "Decision", text: "Move the smaller variable term toward the larger one when that avoids a negative leading coefficient. Correct algebra matters more than a rigid rule." },
    sections: [
      ["Both directions preserve equality", "Subtracting the same variable term from both sides is legal no matter which term you choose. The two routes produce equivalent equations.", "A good choice reduces mental load. Positive coefficients and fewer fractions make later arithmetic easier to check.", String.raw`5x+2=2x+14\quad\Longrightarrow\quad3x+2=14`],
      ["Simplify before deciding", "Distribution and like-term collection may change which side is cleaner. Do that work first instead of moving half-simplified pieces back and forth.", "Writing one operation per line keeps the equality visible and makes a sign mistake easy to locate.", String.raw`2(3x-1)=4x+10\quad\Longrightarrow\quad6x-2=4x+10`],
      ["Watch what happens when x disappears", "If the variable terms cancel and a true statement remains, every permitted value solves the equation. If a false statement remains, no value can solve it.", "Those outcomes are not mistakes. They describe equations whose two sides are identical expressions or permanently separated expressions.", String.raw`3(x+2)=3x+6\quad\Longrightarrow\quad6=6`],
    ],
    example: { heading: "Choose the cleaner direction", prompt: "Solve 7 − 2x = 4x + 19.", steps: [[String.raw`7=6x+19`, "Add 2x to both sides so the variable coefficient stays positive."], [String.raw`-12=6x`, "Subtract 19 from both sides."], [String.raw`x=-2`, "Divide both sides by six."], [String.raw`7-2(-2)=4(-2)+19=11`, "Check both sides in the original equation."]], result: String.raw`\boxed{x=-2}` },
    mistakes: ["Changing a sign without applying an operation to both sides.", "Moving terms before distributing.", "Treating a vanished variable as automatic proof of no solution."],
    takeaways: ["Either direction can be valid.", "Choose the route with cleaner arithmetic.", "A cancelled variable can signal special solution sets."],
    related: ["solving-linear-equations", "no-one-infinite-solutions", "distributive-property"],
  }),
];
