import { algebraArticle } from "./shared";

export const algebraExpansionArticles = [
  algebraArticle({
    slug: "evaluating-expressions-by-substitution", topicSlug: "expressions-equations", archetype: "method",
    title: "Evaluating algebraic expressions by substitution", shortTitle: "Evaluate by substitution",
    deck: "Replace every occurrence of the variable, preserve the expression's grouping, and simplify only after the substitution is complete.",
    course: "Algebra I", difficulty: "Foundational", minutes: 7,
    formula: String.raw`2a^2-3b\quad\text{when }a=-2,\ b=5`,
    searchTerms: ["plug in values", "substitute variables", "evaluate an expression"],
    immediate: { label: "Safe habit", tex: String.raw`x=-3:\quad x^2\longrightarrow(-3)^2`, text: "Put substituted negative numbers and multi-term expressions in parentheses. The parentheses preserve the original job of the variable." },
    sections: [
      ["Substitution is replacement, not multiplication", "A variable holds a place in an expression. Evaluating means replacing that place with a supplied value everywhere it appears.", "Write the replacement first and postpone arithmetic. That short line exposes missing replacements before they become calculation errors.", String.raw`3x-y\quad\xrightarrow{x=4,\ y=-2}\quad3(4)-(-2)`],
      ["Parentheses preserve the variable's role", "If a negative value replaces a powered variable, the entire value becomes the base. Without parentheses, the exponent may attach to the number but not its sign.", "The same rule applies when an expression replaces a variable. Group the whole replacement so multiplication, powers, and subtraction still act on the intended object.", String.raw`x^2\big|_{x=-3}=(-3)^2=9\ne-3^2`],
      ["Finish with ordinary order of operations", "Once every variable has been replaced, the problem is numerical. Evaluate grouping and powers before products and sums.", "Keep exact fractions until the final line when possible. Early decimal rounding can hide a correct structure behind an inaccurate approximation.", String.raw`\frac{x+1}{2}\bigg|_{x=5}=\frac{6}{2}=3`],
    ],
    example: { heading: "Two-variable substitution", prompt: "Evaluate 2a² − 3b when a = −2 and b = 5.", steps: [[String.raw`2(-2)^2-3(5)`, "Replace both variables and group the negative input."], [String.raw`2(4)-15`, "Evaluate the exponent before multiplication."], [String.raw`8-15=-7`, "Complete the subtraction."]], result: String.raw`\boxed{-7}` },
    mistakes: ["Replacing only the first occurrence of a variable.", "Substituting a negative value without parentheses.", "Starting arithmetic before all replacements are visible."],
    takeaways: ["Replace every occurrence.", "Parentheses protect the input.", "Simplify after substitution."],
    related: ["order-of-operations-with-variables", "function-notation", "combining-like-terms"],
  }),
  algebraArticle({
    slug: "graphing-linear-equations-from-standard-form", topicSlug: "linear-relationships", archetype: "method",
    title: "Graphing a linear equation from standard form", shortTitle: "Graph from standard form",
    deck: "Use intercepts when they are clean, or solve for y when slope and vertical change are more informative.",
    course: "Algebra I", difficulty: "Foundational", minutes: 8,
    formula: String.raw`Ax+By=C`,
    searchTerms: ["graph standard form", "x intercept y intercept", "linear graph"],
    immediate: { label: "Two routes", tex: String.raw`Ax+By=C\quad\Rightarrow\quad\text{intercepts or }y=mx+b`, text: "Both routes produce the same line. Choose the representation that makes two reliable points easiest to obtain." },
    sections: [
      ["Intercepts come from setting one coordinate to zero", "At the x-intercept, y is zero. At the y-intercept, x is zero. Substituting those values often creates two points with almost no algebra.", "This route is especially efficient when both intercepts are integers. It is less useful when one coefficient is zero or the intercepts are awkward fractions.", String.raw`2x+3y=12:\quad(6,0),\ (0,4)`],
      ["Slope-intercept form reveals direction", "Solving for y turns standard form into y = mx + b, where m controls the step pattern and b gives a starting point.", "Use legal equation moves on every term. Dividing by B means dividing the x-term, the constant, and their signs by B.", String.raw`Ax+By=C\quad\Rightarrow\quad y=-\frac ABx+\frac CB`],
      ["A graph needs a check, not just two dots", "Substitute a plotted point into the original equation. A point that misses the equation exposes an arithmetic or plotting error immediately.", "Vertical lines have the form x = constant and cannot be written as y = mx + b. Horizontal lines have slope zero and the form y = constant.", String.raw`x=3\text{ is vertical}\qquad y=-2\text{ is horizontal}`],
    ],
    example: { heading: "Use clean intercepts", prompt: "Graph 2x + 3y = 12.", steps: [[String.raw`y=0:\quad2x=12\Rightarrow x=6`, "The x-intercept is (6, 0)."], [String.raw`x=0:\quad3y=12\Rightarrow y=4`, "The y-intercept is (0, 4)."], [String.raw`\text{Draw the line through }(6,0)\text{ and }(0,4)`, "Two distinct points determine the line."]], result: String.raw`y=-\frac23x+4` },
    mistakes: ["Setting x and y to zero at the same time.", "Dividing only part of the equation when solving for y.", "Trying to assign a finite slope to a vertical line."],
    takeaways: ["Intercepts are coordinate-zero points.", "Standard and slope-intercept forms describe the same line.", "Check a plotted point in the original equation."],
    related: ["slope-as-rate-of-change", "equation-from-two-points", "point-slope-vs-slope-intercept"],
  }),
  algebraArticle({
    slug: "graphing-linear-inequalities", topicSlug: "systems-inequalities", archetype: "method",
    title: "Graphing linear inequalities in two variables", shortTitle: "Graph linear inequalities",
    deck: "Draw the boundary, decide whether it belongs to the solution, then test a point to choose the correct half-plane.",
    course: "Algebra I", difficulty: "Intermediate", minutes: 9,
    formula: String.raw`y>-2x+3`,
    searchTerms: ["shade linear inequality", "dashed boundary", "solid boundary", "half plane"],
    immediate: { label: "Three decisions", tex: String.raw`\text{boundary}\to\text{solid or dashed}\to\text{shaded side}`, text: "An inequality describes a region, not one line. The boundary separates points that work from points that do not." },
    sections: [
      ["The related equation creates the boundary", "Replace the inequality sign with an equals sign and graph that line first. Every point on the line makes the two sides equal.", "Use a solid boundary for ≤ or ≥ because equality is allowed. Use a dashed boundary for < or > because boundary points are excluded.", String.raw`y\ge2x-1\Rightarrow y=2x-1\text{ is solid}`],
      ["A test point chooses the side", "Select a point not on the boundary—often (0, 0)—and substitute it into the original inequality. If the statement is true, shade the side containing that point.", "If the boundary passes through the origin, choose another simple point. The test must distinguish one side from the other.", String.raw`(0,0):\quad0>-2(0)+3\text{ is false}`],
      ["Reversing the inequality matters when solving for y", "Multiplying or dividing both sides by a negative reverses the order relation. Missing that reversal shades exactly the wrong region.", "You can avoid solving for y by graphing the boundary in standard form and testing a point directly, but the solid-or-dashed decision still comes from the original symbol.", String.raw`-2y<4x-6\Rightarrow y>-2x+3`],
    ],
    example: { heading: "Boundary and test point", prompt: "Graph y > −2x + 3.", steps: [[String.raw`y=-2x+3`, "Draw the related boundary as a dashed line because equality is excluded."], [String.raw`(0,0):\quad0>3\text{ is false}`, "The origin is not in the solution."], [String.raw`\text{Shade the side opposite }(0,0)`, "That half-plane contains all points that satisfy the inequality."]], result: String.raw`\boxed{y>-2x+3}` },
    mistakes: ["Using a solid line for a strict inequality.", "Testing a point that lies on the boundary.", "Forgetting to reverse the inequality after division by a negative."],
    takeaways: ["Graph the related equation first.", "Boundary style records equality.", "One valid test point identifies the region."],
    related: ["compound-inequalities", "choosing-system-method", "no-one-infinite-solutions"],
  }),
  algebraArticle({
    slug: "completing-the-square", topicSlug: "polynomials-factoring", archetype: "method",
    title: "Completing the square without guessing", shortTitle: "Complete the square",
    deck: "Add the exact term that turns a quadratic expression into a perfect-square trinomial, while preserving the equation's value.",
    course: "Algebra II", difficulty: "Intermediate", minutes: 10,
    formula: String.raw`x^2+bx+\left(\frac b2\right)^2=\left(x+\frac b2\right)^2`,
    searchTerms: ["complete square", "vertex form", "derive quadratic formula"],
    immediate: { label: "The missing term", tex: String.raw`x^2+bx\quad\Rightarrow\quad\left(\frac b2\right)^2`, text: "Half the linear coefficient, then square it. If you are solving an equation, add that value to both sides." },
    sections: [
      ["The middle term determines the square", "Expanding (x + p)² gives x² + 2px + p². Matching 2p with b forces p = b/2, so the constant must be (b/2)².", "This is a structural identity, not a factoring guess. It works for every quadratic after the leading coefficient has been normalized to one.", String.raw`(x+p)^2=x^2+2px+p^2`],
      ["Equations must stay balanced", "Adding the completing term changes an expression. In an equation, add the same amount to both sides so the solution set remains unchanged.", "If the coefficient of x² is not one, divide the equation by that coefficient or factor it from the quadratic terms before using the half-and-square step.", String.raw`x^2+6x=7\Rightarrow x^2+6x+9=16`],
      ["Completed square form exposes useful features", "The form (x − h)² = k makes square-root solving immediate and reveals the vertex of a parabola. It also explains the structure behind the quadratic formula.", "After taking square roots, include both signs. Squaring hides whether the original quantity was positive or negative.", String.raw`(x-h)^2=k\Rightarrow x=h\pm\sqrt{k}`],
    ],
    example: { heading: "Solve by completing the square", prompt: "Solve x² + 6x − 7 = 0.", steps: [[String.raw`x^2+6x=7`, "Move the constant before completing the square."], [String.raw`x^2+6x+9=16`, "Add (6/2)² = 9 to both sides."], [String.raw`(x+3)^2=16`, "Factor the perfect-square trinomial."], [String.raw`x+3=\pm4`, "Take both square roots."]], result: String.raw`\boxed{x=1\text{ or }x=-7}` },
    mistakes: ["Using b² instead of (b/2)².", "Adding the completing term to only one side.", "Keeping only the positive square root."],
    takeaways: ["Half the linear coefficient and square it.", "Normalize the leading coefficient first.", "Square-root solving needs ±."],
    related: ["factoring-trinomials", "special-factor-patterns", "multiply-polynomials"],
  }),
  algebraArticle({
    slug: "simplifying-complex-rational-expressions", topicSlug: "rational-expressions", archetype: "method",
    title: "Simplifying complex rational expressions", shortTitle: "Complex rational expressions",
    deck: "Treat the stacked fraction as division, state every original restriction, and clear the small denominators with one common multiplier.",
    course: "Algebra II", difficulty: "Advanced", minutes: 11,
    formula: String.raw`\frac{\frac1x+\frac1y}{\frac1x-\frac1y}`,
    searchTerms: ["fraction over fraction", "complex fraction", "clear nested denominators"],
    immediate: { label: "Reliable move", tex: String.raw`\text{multiply numerator and denominator by the LCD}`, text: "Use the least common denominator of every small fraction. Because the same nonzero quantity multiplies the top and bottom, the overall value is preserved." },
    sections: [
      ["Restrictions come from the original denominators", "Before simplifying, list every value that makes any original denominator zero. A factor that later disappears still records an excluded input.", "For a complex fraction, inspect denominators inside both the numerator and denominator, then also require the entire large denominator to be nonzero.", String.raw`x\ne0,\quad y\ne0,\quad \frac1x-\frac1y\ne0`],
      ["Clear all small denominators at once", "Find the LCD of the nested fractions and multiply the entire numerator and entire denominator by it. Parentheses help show that every term receives the multiplier.", "This method is usually cleaner than combining the top and bottom separately, although both legal approaches must agree.", String.raw`\frac{xy\left(\frac1x+\frac1y\right)}{xy\left(\frac1x-\frac1y\right)}`],
      ["Factor only after the fraction is flat", "Once the small denominators are gone, simplify the resulting ordinary rational expression by factoring and canceling common factors—not terms across addition.", "Carry the original restrictions beside the final result. The simplified formula and its domain together describe the original expression.", String.raw`\frac{x+y}{y-x},\quad x\ne0,\ y\ne0,\ x\ne y`],
    ],
    example: { heading: "Clear a two-level fraction", prompt: "Simplify (1/x + 1/y)/(1/x − 1/y).", steps: [[String.raw`x\ne0,\ y\ne0,\ x\ne y`, "Record restrictions before changing the form."], [String.raw`\frac{xy(1/x+1/y)}{xy(1/x-1/y)}`, "Multiply the top and bottom by the LCD xy."], [String.raw`\frac{y+x}{y-x}`, "Cancel within each product and combine."]], result: String.raw`\boxed{\frac{x+y}{y-x}}` },
    mistakes: ["Ignoring the large denominator's zero condition.", "Multiplying only the first term by the LCD.", "Canceling x terms across x + y."],
    takeaways: ["Record every original restriction.", "Clear nested denominators with one LCD.", "A final formula needs its domain."],
    related: ["rational-domain-restrictions", "simplifying-rational-expressions", "add-subtract-rational-expressions"],
  }),
  algebraArticle({
    slug: "exponential-growth-and-decay", topicSlug: "radicals-exponents-functions", archetype: "concept",
    title: "Exponential growth and decay: reading the model", shortTitle: "Exponential growth and decay",
    deck: "Separate the starting amount from the repeated growth factor, then connect each parameter to a real change per time interval.",
    course: "Algebra II", difficulty: "Intermediate", minutes: 9,
    formula: String.raw`A(t)=A_0b^t`,
    searchTerms: ["exponential model", "growth factor", "decay factor", "percent growth"],
    immediate: { label: "Parameter meaning", tex: String.raw`A_0=\text{initial value},\qquad b=1+r`, text: "Growth uses b > 1. Decay uses 0 < b < 1. The exponent counts how many equal time intervals have passed." },
    sections: [
      ["The initial value is the output at time zero", "Substituting t = 0 makes b⁰ = 1, so A(0) = A₀. That makes the coefficient the starting amount, not the amount added each interval.", "Units matter: if t counts years, the factor describes one year. A monthly factor needs t measured in months or an adjusted exponent.", String.raw`A(0)=A_0b^0=A_0`],
      ["Percent change becomes a multiplier", "A growth rate r means the new amount is 100% + r of the old amount, so b = 1 + r. A decay rate r leaves 100% − r, so b = 1 − r.", "Convert percentages to decimals before building the factor. A 6% increase uses 1.06, while a 6% decrease uses 0.94.", String.raw`\text{growth: }b=1+r\qquad\text{decay: }b=1-r`],
      ["Exponential change is multiplicative", "Equal time steps multiply by the same factor; they do not add the same amount. That is why the absolute change grows during growth and shrinks during decay.", "A model is only as useful as its domain and assumptions. Real populations, prices, and substances rarely follow one unchanged factor forever.", String.raw`\frac{A(t+1)}{A(t)}=b`],
    ],
    example: { heading: "Build and evaluate a model", prompt: "A $500 account grows 4% per year. Find its value after 3 years.", steps: [[String.raw`A(t)=500(1.04)^t`, "Use the starting value and annual growth factor."], [String.raw`A(3)=500(1.04)^3`, "Three years means three repeated multiplications."], [String.raw`A(3)=562.432`, "Evaluate, then round money to cents."]], result: String.raw`\boxed{\$562.43}` },
    mistakes: ["Using 0.04 as the growth factor.", "Treating exponential change as equal additive increases.", "Mixing the time unit and the factor's interval."],
    takeaways: ["A₀ is the value at time zero.", "Percent change becomes 1 ± r.", "Equal intervals share a multiplier."],
    related: ["rational-exponents", "function-notation", "direct-inverse-variation"],
  }),
];
