const c = (prompt, steps, answer, interpretation) => ({ prompt, steps, answer, interpretation });

export const LESSON_CASES = Object.freeze({
  "A3.1": c(
    "Determine whether x = 4 and x = 7 belong to the truth set of 3x + 2 < 20.",
    ["Substitute each candidate into the left side.", "For x = 4, compare 14 with 20; for x = 7, compare 23 with 20.", "Record every candidate that makes the original inequality true."],
    "x = 4 belongs to the truth set; x = 7 does not.",
    "A truth set contains values that make the complete inequality true, not values that merely look close to its boundary.",
  ),
  "A3.2": c(
    "Solve 5 − 3x ≤ 17 and write the solution in interval notation.",
    ["Subtract 5 from both sides to obtain −3x ≤ 12.", "Divide by −3 and reverse the order symbol.", "Check the boundary and one value on each side in the original inequality."],
    "x ≥ −4, or [−4, ∞).",
    "The endpoint is included because equality is allowed, and negative division reverses the direction of the truth set.",
  ),
  "A3.3": c(
    "Start with 2 < 5. Multiply both sides by −3 and explain the resulting comparison.",
    ["Scale both numbers by −3 to obtain −6 and −15.", "Locate the products on a number line or compare their signed values.", "Write the order relation that remains true."],
    "−6 > −15.",
    "Negative scaling reflects both values across zero, exchanging left and right and therefore reversing order.",
  ),
  "A3.4": c(
    "Translate −2 < x ≤ 5 into interval notation and describe its number-line graph.",
    ["Use a parenthesis at −2 because −2 is excluded.", "Use a bracket at 5 because 5 is included.", "Shade every value between the two endpoints."],
    "(−2, 5], with an open endpoint at −2 and a closed endpoint at 5.",
    "The inequality, interval, and number-line description encode the same set and endpoint decisions.",
  ),
  "A3.5": c(
    "Solve −1 ≤ 2x + 3 < 9 as one compound inequality.",
    ["Subtract 3 from all three parts to obtain −4 ≤ 2x < 6.", "Divide all three parts by 2.", "Translate the result into interval notation and test both endpoints."],
    "−2 ≤ x < 3, or [−2, 3).",
    "An and-compound inequality describes the intersection of two conditions, so the solution is one bounded interval.",
  ),
  "A3.6": c(
    "Solve |x − 4| = 7 by interpreting absolute value as distance.",
    ["Read the equation as a point x being 7 units from the center 4.", "Move 7 units right and 7 units left from 4.", "Substitute both points into the original distance equation."],
    "x = 11 or x = −3.",
    "A positive distance from a center produces two symmetric points.",
  ),
  "A3.7": c(
    "Solve |2x − 1| < 5 and express the result as an interval.",
    ["Rewrite the distance condition as −5 < 2x − 1 < 5.", "Add 1 throughout and then divide throughout by 2.", "Test an interior value and both boundary values in the original condition."],
    "−2 < x < 3, or (−2, 3).",
    "A strict less-than absolute-value inequality describes inputs whose expression lies inside an open distance band.",
  ),
  "A3.8": c(
    "Solve A = (1/2)h(b₁ + b₂) for h and state the required condition.",
    ["Multiply both sides by 2 to obtain 2A = h(b₁ + b₂).", "Divide by b₁ + b₂.", "State when that division is permitted and check the units."],
    "h = 2A/(b₁ + b₂), provided b₁ + b₂ ≠ 0.",
    "Rearranging a formula preserves the relationship while making the requested quantity and its restrictions explicit.",
  ),

  "A4.1": c(
    "A paint mixture uses 3 parts blue for every 5 parts white. Find an equivalent ratio with 20 parts white.",
    ["Preserve the order blue:white as 3:5.", "Multiply both entries by the scale factor 4.", "Check that the new ratio reduces to the original ratio."],
    "12 parts blue to 20 parts white.",
    "Equivalent ratios multiply both quantities by the same nonzero scale factor.",
  ),
  "A4.2": c(
    "A 12-ounce package costs $4.50. Find the price per ounce and compare it with a 20-ounce package costing $7.20.",
    ["Divide each price by its ounce count.", "Compute 4.50/12 and 7.20/20 with dollars in the numerator.", "Compare the two unit prices."],
    "$0.375 per ounce versus $0.36 per ounce; the 20-ounce package is cheaper per ounce.",
    "A consistent unit rate makes differently sized packages directly comparable.",
  ),
  "A4.3": c(
    "The table contains (x, y) = (2, 7), (5, 17.5), and (8, 28). Determine whether y is proportional to x.",
    ["Compute y/x for every nonzero input.", "Compare the three ratios.", "Write y = kx using the common constant and identify the graph feature that must follow."],
    "Yes; k = 3.5, so y = 3.5x and the graph passes through the origin.",
    "A proportional relationship has one constant output-to-input ratio and zero output at zero input.",
  ),
  "A4.4": c(
    "A $80 item is discounted by 15% and then taxed by 8%. Find the final price.",
    ["Use 0.85 as the remaining-price multiplier after the discount.", "Use 1.08 as the tax multiplier.", "Multiply 80·0.85·1.08 and round the currency only at the end."],
    "$73.44.",
    "Successive percent changes multiply; subtracting and adding the percentages directly would ignore the changed base.",
  ),
  "A4.5": c(
    "Decide whether the point (3, 11) lies on y = 4x − 1.",
    ["Substitute the x-coordinate 3 into the equation.", "Compute the resulting output 4(3) − 1.", "Compare that output with the point’s y-coordinate."],
    "Yes, because 11 = 4(3) − 1.",
    "A graphed point represents an ordered pair that satisfies the equation exactly.",
  ),
  "A4.6": c(
    "Find and interpret both intercepts of 3x + 2y = 12.",
    ["Set y = 0 to find the horizontal intercept.", "Set x = 0 to find the vertical intercept.", "Substitute both ordered pairs into the original equation."],
    "x-intercept (4, 0) and y-intercept (0, 6).",
    "Each intercept records the value of one quantity when the other quantity is zero.",
  ),
  "A4.7": c(
    "A table contains (time, distance) values (1, 5), (3, 13), and (6, 25). Find and interpret the slope.",
    ["Compute the change in distance from 5 to 13 and divide by the time change from 1 to 3.", "Repeat with the second pair of intervals.", "Attach distance-per-time units to the common rate."],
    "Slope 4 distance units per time unit.",
    "Equal output change per unit input change confirms a constant linear rate.",
  ),
  "A4.8": c(
    "Find the slope through (−2, 5) and (4, −7).",
    ["Use the same point order in numerator and denominator.", "Compute (−7 − 5)/(4 − (−2)).", "Simplify the signed ratio and verify its direction against the points."],
    "m = −12/6 = −2.",
    "The negative slope agrees with the output decreasing as the input increases.",
  ),
  "A4.9": c(
    "Write the equation of the line with slope −3 through (2, 5) in point-slope and slope-intercept form.",
    ["Insert the known point and slope into y − y₁ = m(x − x₁).", "Distribute and isolate y.", "Substitute the known point into the final equation."],
    "y − 5 = −3(x − 2), so y = −3x + 11.",
    "Point-slope form preserves the given data, while slope-intercept form exposes the vertical intercept.",
  ),
  "A4.10": c(
    "Find the line perpendicular to y = (2/3)x − 4 that passes through (6, 1).",
    ["Use the negative reciprocal slope −3/2.", "Write point-slope form through (6, 1).", "Simplify and verify that the slope product is −1."],
    "y − 1 = −(3/2)(x − 6), or y = −(3/2)x + 10.",
    "Perpendicular nonvertical lines have negative-reciprocal slopes.",
  ),
  "A4.11": c(
    "A model predicts y = 2.5x + 8. At x = 10 the observed value is 31. Find and interpret the residual.",
    ["Compute the predicted value at x = 10.", "Use residual = observed − predicted.", "Interpret the sign and consider whether one residual alone establishes a pattern."],
    "Predicted 33; residual 31 − 33 = −2.",
    "The model overpredicts this observation by 2 units; a residual plot is needed to judge systematic model error.",
  ),

  "A5.1": c(
    "Determine whether (4, 3) solves x + y = 7 and 2x − y = 5.",
    ["Substitute x = 4 and y = 3 into the first equation.", "Substitute the same pair into the second equation.", "Accept the pair only if both statements are true."],
    "Yes; 4 + 3 = 7 and 2(4) − 3 = 5.",
    "A system solution must satisfy every condition simultaneously.",
  ),
  "A5.2": c(
    "Use the graphs y = 2x + 1 and y = −x + 7 to identify their intersection, then verify algebraically.",
    ["Set the two output expressions equal because an intersection has the same y-value.", "Solve 2x + 1 = −x + 7 and then compute y.", "Substitute the pair into both original equations."],
    "(2, 5).",
    "The intersection is the ordered pair satisfying both line equations.",
  ),
  "A5.3": c(
    "Solve y = 3x − 4 and 2x + y = 11 by substitution.",
    ["Replace y in the second equation with the equal expression 3x − 4.", "Solve the resulting one-variable equation.", "Use the first equation to find y and check both originals."],
    "(3, 5).",
    "Substitution preserves the system because an expression is replaced by an equal expression.",
  ),
  "A5.4": c(
    "Solve 2x + 3y = 13 and 4x − 3y = 5 by elimination.",
    ["Add the equations so the opposite y-terms cancel.", "Solve 6x = 18.", "Substitute x = 3 into either original equation and verify the pair."],
    "(3, 7/3).",
    "Adding equations preserves every common solution while eliminating one variable.",
  ),
  "A5.5": c(
    "Classify the system 2x − y = 4 and 4x − 2y = 9.",
    ["Double the first equation to compare coefficients.", "Observe that the left sides match but the constants do not.", "Connect the contradiction to the geometry of the lines."],
    "No solution; the equations reduce to the contradiction 8 = 9.",
    "Equal left-side structure with different constants represents parallel distinct lines.",
  ),
  "A5.6": c(
    "Adult tickets cost $12 and student tickets cost $8. A total of 150 tickets earns $1,560. Find each ticket count.",
    ["Define a as adult tickets and s as student tickets.", "Write a + s = 150 and 12a + 8s = 1560.", "Solve the system and verify both the count and revenue equations."],
    "90 adult tickets and 60 student tickets.",
    "Two independent totals require two unknowns and two simultaneous conditions.",
  ),
  "A5.7": c(
    "Describe the feasible region for y ≥ x − 1 and y < −2x + 5.",
    ["Graph y = x − 1 with a solid boundary because equality is included.", "Graph y = −2x + 5 with a dashed boundary because equality is excluded.", "Identify the overlap above the first line and below the second."],
    "The intersection is the region above or on y = x − 1 and strictly below y = −2x + 5.",
    "A system of inequalities is solved by points satisfying every shaded condition.",
  ),
  "A5.8": c(
    "Choose an efficient method for y = 4x − 9 and 3x + 2y = 5, then solve.",
    ["Choose substitution because y is already isolated.", "Replace y in the second equation and solve for x.", "Recover y and check the ordered pair in both equations."],
    "(23/11, −7/11).",
    "Method selection uses visible structure; an isolated variable makes substitution direct.",
  ),

  "A6.1": c(
    "Write 5⁴ as repeated multiplication, identify the base and exponent, and evaluate.",
    ["Use four factors of the base 5.", "Write 5·5·5·5.", "Multiply the factors without treating 4 as a factor."],
    "Base 5, exponent 4, and value 625.",
    "The exponent counts repeated factors of the base.",
  ),
  "A6.2": c(
    "Compare −4² and (−4)².",
    ["For −4², apply the exponent to 4 before the leading negation.", "For (−4)², use −4 as the grouped base.", "Evaluate and explain the different signs."],
    "−4² = −16, while (−4)² = 16.",
    "Parentheses determine whether the negative sign belongs to the base.",
  ),
  "A6.3": c(
    "Simplify a⁷·a³/a⁴ for a ≠ 0.",
    ["Add exponents across the product in the numerator.", "Subtract the denominator exponent for the quotient.", "Retain the nonzero restriction inherited from the denominator."],
    "a⁶, with a ≠ 0.",
    "Product and quotient laws count repeated factors of the same nonzero base.",
  ),
  "A6.4": c(
    "Simplify [(2x³y)²]/(4xy²).",
    ["Apply the outer exponent to the coefficient and every factor in the numerator.", "Obtain 4x⁶y² before dividing.", "Divide coefficients and subtract exponents of like bases."],
    "x⁵, with x ≠ 0 and y ≠ 0 in the original expression.",
    "An outer power acts on the complete grouped product, not only the first factor.",
  ),
  "A6.5": c(
    "Simplify (3x⁻²y⁰)/(6x) using positive exponents.",
    ["Use y⁰ = 1 and the coefficient ratio 3/6 = 1/2.", "Combine x⁻²/x as x⁻³.", "Rewrite the negative exponent as a reciprocal and state restrictions."],
    "1/(2x³), with x ≠ 0 and y ≠ 0 in the original expression.",
    "Zero and negative exponents preserve exponent laws while introducing reciprocal structure and nonzero bases.",
  ),
  "A6.6": c(
    "Write 0.0000725 in scientific notation and multiply it by 3.0×10⁶.",
    ["Move the decimal five places right to obtain a normalized coefficient.", "Write 7.25×10⁻⁵.", "Multiply coefficients and add powers of ten, then normalize."],
    "0.0000725 = 7.25×10⁻⁵, and the product is 2.175×10² = 217.5.",
    "Scientific notation separates significant digits from scale.",
  ),
  "A6.7": c(
    "Evaluate √144 and solve x² = 144 over the real numbers.",
    ["Use the principal-root convention for √144.", "For the equation, identify every real number whose square is 144.", "Check both candidates by squaring."],
    "√144 = 12; x = −12 or x = 12.",
    "The radical symbol names one principal value, while a power equation may have two real solutions.",
  ),
  "A6.8": c(
    "Solve x⁴ = 81 over the real numbers.",
    ["Take the fourth-root question and note that the exponent is even.", "Recognize 81 = 3⁴.", "Check both real candidates in the original equation."],
    "x = −3 or x = 3.",
    "An even power equation with a positive target has symmetric real solutions.",
  ),
  "A6.9": c(
    "Compare f(x) = x² and g(x) = x³ at x = −2, 0, and 2, then describe their symmetry.",
    ["Evaluate both functions at the three inputs.", "Compare outputs for opposite inputs.", "Use the pattern to name even or odd symmetry."],
    "f outputs 4, 0, 4 and is even; g outputs −8, 0, 8 and is odd.",
    "Even powers erase the sign of opposite inputs, while odd powers preserve opposite output signs.",
  ),

  "A7.1": c(
    "Write 4 − 3x³ + 2x − 7x⁵ in standard form and identify its degree and leading coefficient.",
    ["Order terms by descending exponent.", "Locate the highest nonzero power.", "Read the coefficient attached to that leading term."],
    "−7x⁵ − 3x³ + 2x + 4; degree 5; leading coefficient −7.",
    "Standard form makes a polynomial’s leading behavior and missing powers visible.",
  ),
  "A7.2": c(
    "Simplify (3x³ − 2x + 5) − (x³ + 4x² − 7x − 1).",
    ["Distribute the subtraction sign to every term in the second polynomial.", "Align like powers, including missing powers.", "Combine coefficients only within matching powers."],
    "2x³ − 4x² + 5x + 6.",
    "Polynomial subtraction changes every sign in the subtracted expression before like terms combine.",
  ),
  "A7.3": c(
    "Multiply (−3x⁴y²)(5x³y⁵).",
    ["Multiply the numerical coefficients.", "Add exponents of the common base x.", "Add exponents of the common base y."],
    "−15x⁷y⁷.",
    "Monomial multiplication combines coefficients and counts repeated factors of each common base.",
  ),
  "A7.4": c(
    "Expand −2x³(4x² − 3x + 5).",
    ["Multiply −2x³ by each of the three terms.", "Multiply coefficients and add exponents for each product.", "Check that all original terms received the factor."],
    "−8x⁵ + 6x⁴ − 10x³.",
    "Distribution creates one product term for every term in the grouped polynomial.",
  ),
  "A7.5": c(
    "Expand (2x − 3)(x² + 4x − 5).",
    ["Multiply 2x by every term in the second factor.", "Multiply −3 by every term in the second factor.", "Combine the resulting like powers and write standard form."],
    "2x³ + 5x² − 22x + 15.",
    "General distribution accounts for every pair of terms across the two factors.",
  ),
  "A7.6": c(
    "Expand (3x − 5)² and (3x − 5)(3x + 5), then compare the patterns.",
    ["Use a² − 2ab + b² for the square.", "Use a² − b² for the conjugate product.", "Verify both by ordinary distribution."],
    "(3x − 5)² = 9x² − 30x + 25; (3x − 5)(3x + 5) = 9x² − 25.",
    "The middle terms combine in a square and cancel in a conjugate product.",
  ),
  "A7.7": c(
    "Divide (12x⁵ − 18x³ + 6x²) by 6x².",
    ["Divide every term by the monomial.", "Divide coefficients and subtract exponents.", "State the original divisor restriction and multiply back."],
    "2x³ − 3x + 1, with x ≠ 0.",
    "Division by a monomial distributes across every term and retains the divisor’s domain restriction.",
  ),
  "A7.8": c(
    "Divide 2x³ + 3x² − 11x − 6 by x + 3.",
    ["Divide the leading terms to obtain 2x², multiply back, and subtract.", "Repeat to obtain −3x, then −2.", "Confirm that the final remainder is zero and multiply divisor by quotient."],
    "2x² − 3x − 2, remainder 0.",
    "Polynomial long division repeatedly removes the leading term and is checked by divisor times quotient plus remainder.",
  ),
  "A7.9": c(
    "A student claims (x + 4)² = x² + 16. Diagnose and repair the identity.",
    ["Expand the product (x + 4)(x + 4).", "List all four pairwise products.", "Combine like terms and compare with the claim."],
    "(x + 4)² = x² + 8x + 16.",
    "Squaring a binomial includes two equal cross-products; an exponent does not distribute across addition.",
  ),

  "A8.1": c(
    "Factor 18x⁴y − 24x³y² completely using the greatest common factor.",
    ["Find the greatest common numerical factor 6.", "Take the minimum shared powers x³ and y.", "Factor out 6x³y and expand to verify."],
    "6x³y(3x − 4y).",
    "The GCF contains every factor shared by all terms at its minimum exponent.",
  ),
  "A8.2": c(
    "Factor 6x³ + 9x² + 4x + 6 by grouping.",
    ["Group the first two and last two terms.", "Factor 3x² from the first group and 2 from the second.", "Extract the repeated binomial factor."],
    "(3x² + 2)(2x + 3).",
    "Strategic grouping creates a common binomial factor and reverses distribution twice.",
  ),
  "A8.3": c(
    "Factor x² − 7x + 12.",
    ["List integer factor pairs of 12.", "Choose the pair whose sum is −7.", "Write the binomial product and expand to verify."],
    "(x − 3)(x − 4).",
    "For x² + bx + c, the factor constants multiply to c and add to b.",
  ),
  "A8.4": c(
    "Factor 6x² + 11x + 3 using the ac method.",
    ["Compute ac = 18 and find factors 9 and 2 whose sum is 11.", "Rewrite 11x as 9x + 2x.", "Group and extract the common binomial."],
    "(3x + 1)(2x + 3).",
    "Splitting the middle term creates two groups with a shared binomial factor.",
  ),
  "A8.5": c(
    "Factor 25x² − 40x + 16 and 49y² − 81.",
    ["Recognize square endpoints and test the middle term of the trinomial.", "Reverse the perfect-square pattern.", "Reverse the difference-of-squares pattern for the binomial."],
    "(5x − 4)² and (7y − 9)(7y + 9).",
    "Special patterns save work only when every coefficient and sign satisfies the exact pattern.",
  ),
  "A8.6": c(
    "Factor 2x³ − 18x completely over the integers.",
    ["Extract the GCF 2x.", "Recognize the remaining difference of squares x² − 9.", "Factor completely and verify by expansion."],
    "2x(x − 3)(x + 3).",
    "A general strategy checks GCF before patterns and continues until every factor is irreducible in the stated coefficient system.",
  ),
  "A8.7": c(
    "Solve (2x − 5)(x + 4) = 0 and explain why the method applies.",
    ["Use the zero-product property because the complete product equals zero.", "Set each factor equal to zero.", "Solve both linear equations and check the product."],
    "x = 5/2 or x = −4.",
    "A zero product forces at least one factor to be zero.",
  ),
  "A8.8": c(
    "Solve 2x² − 7x + 3 = 0 by factoring.",
    ["Factor the quadratic as (2x − 1)(x − 3).", "Apply the zero-product property.", "Solve each factor equation and check both roots."],
    "x = 1/2 or x = 3.",
    "Factoring exposes the linear conditions that make the quadratic product zero.",
  ),
  "A8.9": c(
    "Solve 3(x − 2)² = 48 using the square-root method.",
    ["Divide by 3 to isolate the square.", "Take both square roots of 16.", "Solve the two resulting linear equations and check."],
    "x = −2 or x = 6.",
    "Solving an isolated even power requires both positive and negative roots.",
  ),
  "A8.10": c(
    "Complete the square for x² + 6x using an area interpretation.",
    ["View x² and 6x as one square plus two rectangles of width 3.", "Add the missing 3-by-3 corner.", "Write the completed square identity."],
    "x² + 6x + 9 = (x + 3)².",
    "Half the linear coefficient gives the side length of the missing corner.",
  ),
  "A8.11": c(
    "Solve x² + 8x − 5 = 0 by completing the square.",
    ["Move the constant to obtain x² + 8x = 5.", "Add 16 to both sides and factor the perfect square.", "Take both roots and isolate x."],
    "x = −4 ± √21.",
    "Adding the same missing-corner value to both sides preserves equality and creates an invertible square form.",
  ),
  "A8.12": c(
    "Use the quadratic formula to solve 2x² + 3x − 4 = 0 and interpret the discriminant.",
    ["Identify a = 2, b = 3, and c = −4.", "Compute b² − 4ac = 41.", "Substitute into the formula and keep the exact radical form."],
    "x = (−3 ± √41)/4; the positive discriminant gives two distinct real roots.",
    "The quadratic formula gives exact roots, while the discriminant predicts their real-number behavior.",
  ),

  "A9.1": c(
    "Rewrite f(x) = x² − 6x + 5 in factored and vertex form, then name the feature exposed by each form.",
    ["Factor the trinomial using numbers that multiply to 5 and add to −6.", "Complete the square by adding and subtracting 9.", "Read zeros from factored form and the vertex from vertex form."],
    "f(x) = (x − 1)(x − 5) = (x − 3)² − 4; zeros 1 and 5; vertex (3, −4).",
    "Equivalent forms preserve the same function while making different structural features easy to read.",
  ),
  "A9.2": c(
    "Sketch y = −2(x − 1)² + 8 from its structural features.",
    ["Read the vertex (1, 8) and axis x = 1.", "Use a = −2 to determine downward opening and vertical scale.", "Find the intercepts and plot symmetric points."],
    "Vertex (1, 8), axis x = 1, x-intercepts (−1, 0) and (3, 0), and y-intercept (0, 6).",
    "A structural sketch uses vertex, opening, scale, symmetry, and intercepts before filling in additional points.",
  ),
  "A9.3": c(
    "For f(x) = (x + 2)(x − 5), find the zeros, horizontal intercepts, and sign on each interval.",
    ["Set each factor equal to zero.", "Use the zeros −2 and 5 to divide the number line.", "Test one input in each interval to determine the product sign."],
    "Zeros −2 and 5; intercepts (−2, 0) and (5, 0); positive on (−∞, −2)∪(5, ∞) and negative on (−2, 5).",
    "Factored form links roots, intercepts, and sign changes through the signs of the factors.",
  ),
  "A9.4": c(
    "Describe the transformations from y = x² to y = 3(x + 2)² − 5.",
    ["Read x + 2 as a horizontal shift left 2.", "Read the factor 3 as a vertical stretch.", "Read −5 as a vertical shift and identify the vertex and opening."],
    "Shift left 2, stretch vertically by 3, and shift down 5; vertex (−2, −5), opening upward.",
    "Vertex form records transformations relative to the parent parabola without requiring expansion.",
  ),
  "A9.5": c(
    "Choose a useful form for f(x) = 2x² − 12x + 10 when the goal is to find the minimum value.",
    ["Recognize that vertex form directly exposes an extremum.", "Factor out 2 from the quadratic and linear terms, then complete the square.", "Read the vertex and verify by expansion."],
    "f(x) = 2(x − 3)² − 8, so the minimum value is −8 at x = 3.",
    "Changing form is strategic: vertex form answers an extremum question directly.",
  ),
  "A9.6": c(
    "A projectile’s height is h(t) = −16t² + 64t + 5. Find and interpret its maximum height.",
    ["Use t = −b/(2a) to find the vertex time.", "Evaluate h at that time.", "Restrict the interpretation to the physically meaningful time interval."],
    "The maximum occurs at t = 2 seconds and is h(2) = 69 feet.",
    "The vertex represents the maximum only within the model’s contextual domain and carries both time and height units.",
  ),
  "A9.7": c(
    "Solve x² − 5x + 6 ≤ 0.",
    ["Factor as (x − 2)(x − 3).", "Use 2 and 3 as critical values and test the three intervals.", "Include both zeros because equality is allowed."],
    "2 ≤ x ≤ 3, or [2, 3].",
    "An upward-opening quadratic is at or below the axis between its real zeros.",
  ),
  "A9.8": c(
    "Two models fit a dataset: linear residuals show a U-shaped pattern, while quadratic residuals are small and randomly scattered. Choose the stronger model and state a limitation.",
    ["Interpret the systematic linear residual pattern as missed curvature.", "Interpret random quadratic residual scatter as better structural fit.", "Limit conclusions to the observed range and avoid causal claims."],
    "The quadratic model is stronger within the observed input range, but fit alone does not prove causation or justify distant extrapolation.",
    "Residual structure matters more than a graph merely appearing close to the data points.",
  ),

  "A10.1": c(
    "State the domain restrictions of (x + 4)/[(x − 2)(x + 5)].",
    ["Set every original denominator factor unequal to zero.", "Solve x − 2 ≠ 0 and x + 5 ≠ 0.", "State the excluded inputs as part of the expression."],
    "x ≠ 2 and x ≠ −5.",
    "Rational-expression restrictions come from the original denominator before any simplification occurs.",
  ),
  "A10.2": c(
    "Simplify (x² − 9)/(x² − x − 6) and preserve all original restrictions.",
    ["Factor the numerator as (x − 3)(x + 3).", "Factor the denominator as (x − 3)(x + 2).", "State restrictions, cancel the common nonzero factor, and retain the canceled restriction."],
    "(x + 3)/(x + 2), with x ≠ 3 and x ≠ −2.",
    "A canceled factor creates an equivalent simpler rule only on the original domain.",
  ),
  "A10.3": c(
    "Multiply [3x/(x² − 4)]·[(x + 2)/(6x²)] and simplify.",
    ["Factor x² − 4 as (x − 2)(x + 2) and state restrictions.", "Cancel common factors across the complete product.", "Multiply the remaining factors."],
    "1/[2x(x − 2)], with x ≠ −2, 0, 2.",
    "Factoring before multiplication reveals valid cross-cancellation while preserving all original restrictions.",
  ),
  "A10.4": c(
    "Simplify [(x² − 9)/(x + 1)] ÷ [(x − 3)/(2x)].",
    ["State restrictions from both denominators and require the divisor itself to be nonzero.", "Multiply by the reciprocal of the divisor.", "Factor, cancel common nonzero factors, and multiply."],
    "2x(x + 3)/(x + 1), with x ≠ −1, 0, 3.",
    "Division adds restrictions because the divisor must be defined and nonzero before its reciprocal is used.",
  ),
  "A10.5": c(
    "Find the least common denominator of 6x²(x − 1) and 9x(x − 1)³.",
    ["Factor the numerical coefficients and use their least common multiple.", "Take the greatest required power of x.", "Take the greatest required power of x − 1."],
    "18x²(x − 1)³.",
    "An LCD contains each irreducible denominator factor at the greatest power appearing in any denominator.",
  ),
  "A10.6": c(
    "Simplify 2/(x − 1) − 3/(x + 2).",
    ["Use (x − 1)(x + 2) as the common denominator and state restrictions.", "Rewrite both numerators using the missing factor.", "Combine numerators and simplify without cancelling terms."],
    "(7 − x)/[(x − 1)(x + 2)], with x ≠ 1, −2.",
    "Rational addition and subtraction require equal denominator units before numerators can combine.",
  ),
  "A10.7": c(
    "Simplify [1/x + 1/y]/[1/x − 1/y].",
    ["State x ≠ 0, y ≠ 0, and require the complex-expression denominator to be nonzero.", "Multiply numerator and denominator by the common LCD xy.", "Simplify the resulting ordinary rational expression."],
    "(x + y)/(y − x), with x ≠ 0, y ≠ 0, and x ≠ y.",
    "Multiplying the numerator and denominator by the same nonzero LCD clears the internal fractions without changing value.",
  ),
  "A10.8": c(
    "Solve 2/(x − 1) + 1/(x + 1) = 1.",
    ["State x ≠ 1 and x ≠ −1.", "Multiply every term by (x − 1)(x + 1) and simplify the resulting quadratic.", "Solve the candidates and test each in the original equation."],
    "x = (3 ± √17)/2; both candidates satisfy the original restrictions.",
    "Denominator clearing produces candidates, so the original equation remains the final authority.",
  ),
  "A10.9": c(
    "The time t to complete a fixed job varies inversely with the number n of workers. If 6 workers take 10 hours, find the time for 15 workers.",
    ["Write t = k/n.", "Use 10 = k/6 to find k = 60 worker-hours.", "Evaluate t = 60/15 and interpret the units."],
    "4 hours.",
    "Inverse variation keeps the product nt constant while one quantity rises and the other falls.",
  ),
  "A10.10": c(
    "Analyze the critical values and graph features of f(x) = (x² − 4)/(x² − x − 2).",
    ["Factor numerator and denominator.", "Identify the canceled factor and uncanceled denominator factor.", "State the hole, vertical asymptote, remaining zero, and domain restrictions."],
    "f(x) = (x + 2)/(x + 1), with a hole at (1, 3/2), vertical asymptote x = −1, zero x = −2, and restrictions x ≠ 1, −1.",
    "Canceled denominator factors create holes; uncanceled denominator factors create vertical asymptotes.",
  ),

  "A11.1": c(
    "Evaluate ∛(−125) and compare √36 with the solutions of x² = 36.",
    ["Use the odd-root definition for the negative radicand.", "Use the principal-root convention for √36.", "Solve the even power equation separately and check all values."],
    "∛(−125) = −5; √36 = 6; x² = 36 has x = −6 or x = 6.",
    "Odd roots accept negative radicands, while principal even roots differ from the full solution set of an even-power equation.",
  ),
  "A11.2": c(
    "Simplify √432 exactly.",
    ["Factor 432 as 144·3.", "Use √144 = 12.", "Leave the non-square factor inside the radical."],
    "12√3.",
    "Extracting perfect-square factors produces a simpler exact radical without decimal approximation.",
  ),
  "A11.3": c(
    "Simplify √18·√8 and √75/√3.",
    ["Confirm the real radicands and combine each product or quotient under one root.", "Simplify √144 and √25.", "Check the exact values against separately simplified factors."],
    "√18·√8 = 12 and √75/√3 = 5.",
    "Root product and quotient properties preserve exact value under their valid real-domain conditions.",
  ),
  "A11.4": c(
    "Simplify 3√12 − 2√27 + √48.",
    ["Extract perfect-square factors from every radical.", "Rewrite all terms using √3.", "Combine the coefficients of the like radical terms."],
    "6√3 − 6√3 + 4√3 = 4√3.",
    "Radical terms combine only after simplification reveals an identical radical part.",
  ),
  "A11.5": c(
    "Rationalize 5/(2√3).",
    ["Multiply numerator and denominator by √3.", "Use √3·√3 = 3.", "Simplify the rational denominator."],
    "5√3/6.",
    "Multiplication by √3/√3 changes the form without changing the value.",
  ),
  "A11.6": c(
    "Rationalize 4/(3 − √5).",
    ["Multiply numerator and denominator by the conjugate 3 + √5.", "Use (3 − √5)(3 + √5) = 9 − 5.", "Simplify the resulting denominator and numerator."],
    "3 + √5.",
    "The conjugate product removes the radical through a difference of squares.",
  ),
  "A11.7": c(
    "Rewrite 16^(3/4) in radical form and evaluate.",
    ["Interpret the denominator 4 as a fourth root.", "Interpret the numerator 3 as a power.", "Use the principal fourth root of 16 and cube it."],
    "16^(3/4) = (⁴√16)³ = 2³ = 8.",
    "A rational exponent combines a root and a power in a compact exact notation.",
  ),
  "A11.8": c(
    "Solve √(x + 5) = x − 1.",
    ["Require x − 1 ≥ 0 and isolate the radical.", "Square both sides to obtain x + 5 = (x − 1)².", "Solve the quadratic candidates and check each in the original radical equation."],
    "x = 4.",
    "Squaring creates candidates; only x = 4 satisfies the original equation and sign condition.",
  ),
  "A11.9": c(
    "Explain why x = −1 is extraneous after solving √(x + 5) = x − 1.",
    ["Substitute x = −1 into the original equation.", "Compare the nonnegative left side with the negative right side.", "Identify squaring as the one-way step that lost sign information."],
    "x = −1 fails because 2 ≠ −2; squaring made both sides equal to 4 and created the candidate.",
    "An extraneous solution satisfies a transformed equation but not the original domain or equality.",
  ),
  "A11.10": c(
    "Simplify (3 + 4i)(2 − i) and find the product of 3 + 4i with its conjugate.",
    ["Distribute and replace i² with −1.", "Combine real and imaginary terms.", "Use the conjugate product a² + b² for the second calculation."],
    "(3 + 4i)(2 − i) = 10 + 5i; (3 + 4i)(3 − 4i) = 25.",
    "Complex arithmetic remains distributive, and conjugates produce a real sum of squares.",
  ),

  "A12.1": c(
    "Determine whether the relation {(1, 4), (2, 5), (1, 7)} is a function of the first coordinate.",
    ["List the output paired with each input.", "Notice that input 1 is paired with both 4 and 7.", "Apply the one-output-per-input definition."],
    "No; input 1 has two different outputs.",
    "A relation fails to be a function when one allowed input is assigned more than one output.",
  ),
  "A12.2": c(
    "For f(x) = 3x² − 2x + 1, evaluate f(−2).",
    ["Replace every x with the grouped input −2.", "Compute 3(−2)² − 2(−2) + 1.", "Interpret the result as an input-output pair."],
    "f(−2) = 17, so (−2, 17) lies on the graph.",
    "Function notation names the output assigned to a specific input.",
  ),
  "A12.3": c(
    "For f(x) = x² − 5x + 4, solve f(x) = 4.",
    ["Set x² − 5x + 4 equal to 4.", "Simplify to x² − 5x = 0 and factor.", "Solve both factor equations and verify the outputs."],
    "x = 0 or x = 5.",
    "One requested output can correspond to several different inputs without violating the function definition.",
  ),
  "A12.4": c(
    "Find the real domain of g(x) = √(2x − 6)/(x − 5).",
    ["Require the even-root radicand 2x − 6 to be nonnegative.", "Exclude x = 5 because the denominator cannot be zero.", "Intersect the two conditions."],
    "[3, 5) ∪ (5, ∞).",
    "A combined expression inherits every domain condition from its radicals and denominators.",
  ),
  "A12.5": c(
    "For f(x) = −(x − 2)² + 9 with domain 0 ≤ x ≤ 5, find the range and intervals of increase and decrease.",
    ["Read the vertex (2, 9) and downward opening.", "Evaluate the endpoints and compare with the vertex.", "Track output direction on each side of the vertex within the restricted domain."],
    "Range [0, 9]; increasing on [0, 2] and decreasing on [2, 5].",
    "Range and behavior depend on both the function rule and the stated domain.",
  ),
  "A12.6": c(
    "Evaluate f(−2), f(1), and f(4) when f(x) = x + 3 for x < 1, f(x) = x² for 1 ≤ x ≤ 3, and f(x) = 10 − x for x > 3.",
    ["Compare each input with the piecewise interval conditions.", "Use exactly the rule whose condition contains the input.", "Check the included endpoints at x = 1 and x = 3."],
    "f(−2) = 1, f(1) = 1, and f(4) = 6.",
    "Piecewise evaluation begins with the input condition, not with whichever formula looks easiest.",
  ),
  "A12.7": c(
    "Let f(x) = √(x − 1) and g(x) = 1/(x − 3). Find the domain of f + g and f/g.",
    ["Use x ≥ 1 for f and x ≠ 3 for g.", "Intersect those conditions for f + g.", "For f/g, also require g(x) ≠ 0, which already holds wherever g is defined."],
    "Both domains are [1, 3) ∪ (3, ∞).",
    "Function arithmetic uses the shared domain, with division adding a nonzero-divisor requirement.",
  ),
  "A12.8": c(
    "Classify the families of y = 4x − 1, y = x², y = 2ˣ, and y = 1/x using change pattern and domain.",
    ["Identify constant difference, power-two curvature, constant ratio, and reciprocal restriction.", "State the natural real domain of each formula.", "Name one characteristic graph feature for each family."],
    "Linear, quadratic, exponential, and rational, respectively.",
    "Family classification uses structure, change, restrictions, and graph behavior together.",
  ),

  "A13.1": c(
    "A table gives A: 10, 14, 18, 22 and B: 10, 15, 22.5, 33.75. Classify each pattern.",
    ["Compute consecutive differences for A.", "Compute consecutive ratios for B.", "Write a rule type that matches each constant pattern."],
    "A is linear with constant difference 4; B is exponential with constant ratio 1.5.",
    "Equal additions signal linear change, while equal multipliers signal exponential change.",
  ),
  "A13.2": c(
    "A population starts at 2,400 and grows by 6% each year. Write the explicit value after n years and find the value after 4 years.",
    ["Convert 6% growth to multiplier 1.06.", "Write aₙ = 2400(1.06)ⁿ.", "Evaluate at n = 4 and round only the contextual count."],
    "aₙ = 2400(1.06)ⁿ; a₄ ≈ 3,030.",
    "Repeated percent growth forms a geometric sequence because each term is the previous term times one constant factor.",
  ),
  "A13.3": c(
    "For f(x) = 5(0.8)ˣ, identify the initial value, growth or decay, and output after 3 periods.",
    ["Evaluate f(0) to identify the initial value.", "Compare the base 0.8 with 1.", "Evaluate f(3) exactly before rounding."],
    "Initial value 5; decay by 20% per period; f(3) = 2.56.",
    "The coefficient gives the zero-input output and the base gives the per-period multiplier.",
  ),
  "A13.4": c(
    "Describe the transformations and horizontal asymptote of y = −2·3^(x−1) + 4.",
    ["Start from y = 3ˣ.", "Read the right shift, vertical reflection/stretch, and upward shift.", "Move the parent asymptote y = 0 by the vertical shift."],
    "Shift right 1, reflect across the x-axis, stretch by 2, shift up 4; horizontal asymptote y = 4.",
    "Exponential transformations move the entire graph, including its asymptote.",
  ),
  "A13.5": c(
    "A medicine dose starts at 120 mg and decreases by 18% each hour. Build a model and find the amount after 6 hours.",
    ["Use decay multiplier 1 − 0.18 = 0.82.", "Write M(t) = 120(0.82)ᵗ for t ≥ 0.", "Evaluate at t = 6 and interpret the model’s domain and units."],
    "M(t) = 120(0.82)ᵗ; M(6) ≈ 36.5 mg.",
    "A growth or decay model combines an initial value, per-period multiplier, time unit, and realistic domain.",
  ),
  "A13.6": c(
    "Find the balance after 5 years on $2,000 at 6% annual interest compounded monthly.",
    ["Use A = P(1 + r/n)^(nt) with P = 2000, r = 0.06, n = 12, and t = 5.", "Compute the monthly multiplier and 60 periods.", "Round the final currency amount only once."],
    "A = 2000(1.005)^60 ≈ $2,697.70.",
    "Compounding divides the nominal annual rate among periods and applies that multiplier repeatedly.",
  ),
  "A13.7": c(
    "A quantity follows P(t) = 800e^(0.035t). Find its continuous growth rate and value after 10 years.",
    ["Read k = 0.035 as the continuous rate parameter.", "Evaluate P(10) = 800e^0.35.", "State the units and distinguish k from an effective annual percentage."],
    "Continuous rate parameter 3.5% per year; P(10) ≈ 1,135.25.",
    "The base e packages continuous compounding, while the exponent carries rate times time.",
  ),
  "A13.8": c(
    "Rewrite 2⁵ = 32 logarithmically and evaluate log₃(1/27).",
    ["Translate base, exponent, and result without changing their roles.", "Rewrite 1/27 as 3⁻³.", "Read the exponent required to produce the argument."],
    "log₂(32) = 5 and log₃(1/27) = −3.",
    "A logarithm is the exponent that connects a valid base with a positive argument.",
  ),
  "A13.9": c(
    "Expand log_b[(x²√y)/z³] under positive-variable conditions.",
    ["Use the quotient law to separate numerator and denominator.", "Use the product law within the numerator.", "Use power notation √y = y^(1/2) and move exponents forward."],
    "2log_b x + (1/2)log_b y − 3log_b z.",
    "Logarithm laws translate multiplication, division, and powers into addition, subtraction, and coefficients.",
  ),
  "A13.10": c(
    "Solve 5·2^(3x) = 70 exactly and then approximate.",
    ["Divide by 5 to isolate the exponential expression.", "Take logarithms and use the power law.", "Solve for x and postpone decimal evaluation until the exact form is complete."],
    "x = ln(14)/(3ln 2) ≈ 1.269.",
    "Logarithms invert exponentiation when a convenient common base is unavailable.",
  ),
  "A13.11": c(
    "Solve log₂(x − 1) + log₂(x − 3) = 3.",
    ["Require x > 3.", "Condense to log₂[(x − 1)(x − 3)] = 3 and exponentiate.", "Solve the quadratic candidates and reject any that violate the log domain."],
    "x = 5.",
    "Logarithmic equations require positive arguments in the original statement, so domain checking is decisive.",
  ),

  "A14.1": c(
    "Classify and state the requested action for 3x² − 5x + 2, 3x² − 5x + 2 = 0, and 3x² − 5x + 2 > 0.",
    ["Identify whether each object makes a claim or only names a value.", "Use the comparison symbol to distinguish equation from inequality.", "Match each object with simplify/evaluate, solve, or find a truth set."],
    "Polynomial expression; quadratic equation; quadratic inequality.",
    "Classification uses both mathematical structure and the action requested by the statement.",
  ),
  "A14.2": c(
    "Classify √(x + 1) = x − 3, 2^(x+1) = 9, and (x + 1)/(x − 2) = 4.",
    ["Identify the operation containing the variable in each equation.", "Name radical, exponential, and rational structure.", "State the first restriction or inverse operation each family requires."],
    "Radical equation, exponential equation, and rational equation.",
    "Equation families are recognized by where the variable occurs, not by isolated symbols elsewhere in the expression.",
  ),
  "A14.3": c(
    "Choose a method for x² − 10x + 7 = 0 when exact roots are required and integer factoring fails.",
    ["Check quickly that no integer factor pair of 7 sums to −10.", "Choose completing the square or the quadratic formula.", "Carry out one method and preserve exact radical form."],
    "x = 5 ± 3√2.",
    "Method choice follows structure and the requested exactness rather than forcing a failed factoring attempt.",
  ),
  "A14.4": c(
    "Label each step as equivalence or implication: x − 3 = 5; (x − 3)² = 25; then x − 3 = ±5.",
    ["Compare the solution set before and after squaring.", "Recognize that squaring loses sign information and can enlarge the set.", "Recover both square-root candidates and check against the original equation."],
    "Squaring is a one-way implication here; only x = 8 solves the original equation, while x = −2 is extraneous.",
    "One-way operations produce candidates and make original-equation checking mandatory.",
  ),
  "A14.5": c(
    "A calculator reports the roots of x² − 2 = 0 as ±1.414. Give an exact answer and a justified three-decimal approximation.",
    ["Solve the equation symbolically with both square roots.", "Preserve ±√2 as the exact structure.", "Round √2 only after selecting three decimal places."],
    "x = ±√2 exactly; x ≈ ±1.414 to three decimal places.",
    "Technology supports approximation, while exact form preserves the value and makes the rounding decision auditable.",
  ),
  "A14.6": c(
    "Cross-check the solutions of x² = 2x + 3 graphically and algebraically.",
    ["Interpret solutions as intersections of y = x² and y = 2x + 3.", "Move all terms to one side and factor x² − 2x − 3.", "Compare the exact roots with the graph’s intersection count and locations."],
    "x = −1 and x = 3, with intersections (−1, 1) and (3, 9).",
    "The graph supports the number and approximate location of solutions; factoring supplies exact values.",
  ),
  "A14.7": c(
    "A rectangular enclosure uses 60 m of fencing and must maximize area. Build, solve, and interpret a complete model.",
    ["Let width be x and use 2x + 2L = 60 to write L = 30 − x.", "Write A(x) = x(30 − x) with contextual domain 0 < x < 30.", "Find the vertex, verify the maximum, and report dimensions with units."],
    "A(x) = −x² + 30x has maximum 225 m² at x = 15 m, so the enclosure is 15 m by 15 m.",
    "A complete Algebra model defines quantities, derives a valid domain, chooses a method, checks the result, and interprets it in context.",
  ),
});

export function getLessonCase(lessonId) {
  return LESSON_CASES[lessonId] ?? null;
}
